SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = {schema}, pg_catalog;


INSERT INTO code_ahc (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (1, 'ACTIVE', 'Active', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code_ahc (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (2, 'HOLD', 'Hold', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code_ahc (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (3, 'CLOSED', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO menu__tbl (menu_group, menu_id, menu_sts, menu_id_parent, menu_name, menu_seq, menu_desc, menu_desc_ext, menu_desc_ext2, menu_cmd, menu_image, menu_snotes, menu_subcmd) VALUES ('S', 1, 'ACTIVE', NULL, 'MAIN', NULL, 'Main System', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO menu__tbl (menu_group, menu_id, menu_sts, menu_id_parent, menu_name, menu_seq, menu_desc, menu_desc_ext, menu_desc_ext2, menu_cmd, menu_image, menu_snotes, menu_subcmd) VALUES ('S', 3, 'ACTIVE', 1, 'Dashboard__model', 1, 'Dashboard', NULL, NULL, '%%%NAMESPACE%%%Dashboard__model', NULL, NULL, NULL);
INSERT INTO menu__tbl (menu_group, menu_id, menu_sts, menu_id_parent, menu_name, menu_seq, menu_desc, menu_desc_ext, menu_desc_ext2, menu_cmd, menu_image, menu_snotes, menu_subcmd) VALUES ('S', 700, 'ACTIVE', 1, 'Reports', 70000, 'Reports', NULL, NULL, '%%%NAMESPACE%%%Reports/Overview', NULL, NULL, NULL);
INSERT INTO menu__tbl (menu_group, menu_id, menu_sts, menu_id_parent, menu_name, menu_seq, menu_desc, menu_desc_ext, menu_desc_ext2, menu_cmd, menu_image, menu_snotes, menu_subcmd) VALUES ('S', 800, 'ACTIVE', 1, 'Admin', 80000, 'Administration', NULL, NULL, '%%%NAMESPACE%%%Admin/Overview', NULL, NULL, NULL);
INSERT INTO menu__tbl (menu_group, menu_id, menu_sts, menu_id_parent, menu_name, menu_seq, menu_desc, menu_desc_ext, menu_desc_ext2, menu_cmd, menu_image, menu_snotes, menu_subcmd) VALUES ('S', 900, 'ACTIVE', 1, 'Dev', 90000, 'Developer', NULL, NULL, '%%%NAMESPACE%%%Dev/Overview', NULL, NULL, NULL);


INSERT INTO single (single_dummy, single_ident, dual_bigint, single_varchar50) VALUES ('X', 1, NULL, NULL);



INSERT INTO code2_app (code_name, code_desc, code_code_desc, code_snotes, code_attrib_desc, code_schema, code_type) VALUES ('doc_scope_doc_ctgr', 'Scope - Documents', NULL, NULL, NULL, '{schema}', 'app');






INSERT INTO code_param_type (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'C', 'Character', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code_param_type (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'N', 'Number', NULL, NULL, NULL, NULL, NULL, NULL);



INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('EMAIL', 'NOTIF_ADMIN', 'Notifications Email - Administrative', 'C', NULL, NULL, true, false, false);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('USERS', 'HASH_SEED_S', 'Hash Seed System Users', 'C', NULL, NULL, false, false, true);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('HOUSE', 'ADDR', 'HOUSE Address', 'C', NULL, NULL, true, false, false);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('HOUSE', 'BPHONE', 'HOUSE Business Phone', 'C', NULL, NULL, true, false, false);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('HOUSE', 'CITY', 'HOUSE City', 'C', NULL, NULL, true, false, false);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('HOUSE', 'CONTACT', 'HOUSE Contact', 'C', NULL, NULL, true, false, false);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('HOUSE', 'EMAIL', 'HOUSE Email', 'C', NULL, NULL, true, false, false);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('HOUSE', 'FAX', 'HOUSE Fax', 'C', NULL, NULL, true, false, false);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('SQL', 'doc_ctgr_table', 'Code table - Document Types by Scope', 'C', NULL, NULL, false, false, true);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('SQL', 'get_cust_id', 'SQL Function get_cust_id', 'C', NULL, NULL, false, false, true);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('SQL', 'get_item_id', 'SQL Function get_item_id', 'C', NULL, NULL, false, false, true);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('SQL', 'check_scope_id', 'SQL Function check_scope_id', 'C', NULL, NULL, false, false, true);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('HOUSE', 'ZIP', 'HOUSE ZIP', 'C', NULL, NULL, true, false, false);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('HOUSE', 'STATE', 'HOUSE State', 'C', NULL, NULL, true, false, false);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('HOUSE', 'NAME', 'HOUSE Name', 'C', NULL, NULL, true, false, false);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('DEVICEURL', 'PRINTBAR', 'Device URL - Bar Code Printer', 'C', NULL, NULL, true, true, false);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('DEVICEURL', 'SCAN', 'Device URL - Document Scanner', 'C', NULL, NULL, true, true, false);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('EMAIL', 'NOTIF_SYS', 'Notifications Email - System', 'C', NULL, NULL, true, false, true);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('SYSTEM', 'CLIENT_SYS_URL', 'Client Portal URL', 'C', NULL, NULL, false, false, true);
INSERT INTO param__tbl (param_process, param_attrib, param_desc, param_type, code_name, param_snotes, is_param_app, is_param_user, is_param_sys) VALUES ('SYSTEM', 'SYS_URL', 'System URL', 'C', NULL, NULL, false, false, true);



INSERT INTO param_app (param_app_process, param_app_attrib, param_app_val) VALUES ('HOUSE', 'STATE', 'IL');
INSERT INTO param_app (param_app_process, param_app_attrib, param_app_val) VALUES ('HOUSE', 'CITY', 'Anytown');
INSERT INTO param_app (param_app_process, param_app_attrib, param_app_val) VALUES ('HOUSE', 'CONTACT', 'John Contact');
INSERT INTO param_app (param_app_process, param_app_attrib, param_app_val) VALUES ('HOUSE', 'ADDR', '111 Main St');
INSERT INTO param_app (param_app_process, param_app_attrib, param_app_val) VALUES ('HOUSE', 'BPHONE', '(222) 222-2222');
INSERT INTO param_app (param_app_process, param_app_attrib, param_app_val) VALUES ('HOUSE', 'EMAIL', 'user@company.com');
INSERT INTO param_app (param_app_process, param_app_attrib, param_app_val) VALUES ('HOUSE', 'FAX', '(333) 333-3333');
INSERT INTO param_app (param_app_process, param_app_attrib, param_app_val) VALUES ('HOUSE', 'NAME', 'COMPANY NAME');
INSERT INTO param_app (param_app_process, param_app_attrib, param_app_val) VALUES ('EMAIL', 'NOTIF_ADMIN', 'user@company.com');
INSERT INTO param_app (param_app_process, param_app_attrib, param_app_val) VALUES ('HOUSE', 'ZIP', '11111');






INSERT INTO number__tbl (number_val) VALUES (1);
INSERT INTO number__tbl (number_val) VALUES (2);
INSERT INTO number__tbl (number_val) VALUES (3);
INSERT INTO number__tbl (number_val) VALUES (4);
INSERT INTO number__tbl (number_val) VALUES (5);
INSERT INTO number__tbl (number_val) VALUES (6);
INSERT INTO number__tbl (number_val) VALUES (7);
INSERT INTO number__tbl (number_val) VALUES (8);
INSERT INTO number__tbl (number_val) VALUES (9);
INSERT INTO number__tbl (number_val) VALUES (10);
INSERT INTO number__tbl (number_val) VALUES (11);
INSERT INTO number__tbl (number_val) VALUES (12);
INSERT INTO number__tbl (number_val) VALUES (13);
INSERT INTO number__tbl (number_val) VALUES (14);
INSERT INTO number__tbl (number_val) VALUES (15);
INSERT INTO number__tbl (number_val) VALUES (16);
INSERT INTO number__tbl (number_val) VALUES (17);
INSERT INTO number__tbl (number_val) VALUES (18);
INSERT INTO number__tbl (number_val) VALUES (19);
INSERT INTO number__tbl (number_val) VALUES (20);
INSERT INTO number__tbl (number_val) VALUES (21);
INSERT INTO number__tbl (number_val) VALUES (22);
INSERT INTO number__tbl (number_val) VALUES (23);
INSERT INTO number__tbl (number_val) VALUES (24);
INSERT INTO number__tbl (number_val) VALUES (25);
INSERT INTO number__tbl (number_val) VALUES (26);
INSERT INTO number__tbl (number_val) VALUES (27);
INSERT INTO number__tbl (number_val) VALUES (28);
INSERT INTO number__tbl (number_val) VALUES (29);
INSERT INTO number__tbl (number_val) VALUES (30);
INSERT INTO number__tbl (number_val) VALUES (31);
INSERT INTO number__tbl (number_val) VALUES (32);
INSERT INTO number__tbl (number_val) VALUES (33);
INSERT INTO number__tbl (number_val) VALUES (34);
INSERT INTO number__tbl (number_val) VALUES (35);
INSERT INTO number__tbl (number_val) VALUES (36);
INSERT INTO number__tbl (number_val) VALUES (37);
INSERT INTO number__tbl (number_val) VALUES (38);
INSERT INTO number__tbl (number_val) VALUES (39);
INSERT INTO number__tbl (number_val) VALUES (40);
INSERT INTO number__tbl (number_val) VALUES (41);
INSERT INTO number__tbl (number_val) VALUES (42);
INSERT INTO number__tbl (number_val) VALUES (43);
INSERT INTO number__tbl (number_val) VALUES (44);
INSERT INTO number__tbl (number_val) VALUES (45);
INSERT INTO number__tbl (number_val) VALUES (46);
INSERT INTO number__tbl (number_val) VALUES (47);
INSERT INTO number__tbl (number_val) VALUES (48);
INSERT INTO number__tbl (number_val) VALUES (49);
INSERT INTO number__tbl (number_val) VALUES (50);
INSERT INTO number__tbl (number_val) VALUES (51);
INSERT INTO number__tbl (number_val) VALUES (52);
INSERT INTO number__tbl (number_val) VALUES (53);
INSERT INTO number__tbl (number_val) VALUES (54);
INSERT INTO number__tbl (number_val) VALUES (55);
INSERT INTO number__tbl (number_val) VALUES (56);
INSERT INTO number__tbl (number_val) VALUES (57);
INSERT INTO number__tbl (number_val) VALUES (58);
INSERT INTO number__tbl (number_val) VALUES (59);
INSERT INTO number__tbl (number_val) VALUES (60);
INSERT INTO number__tbl (number_val) VALUES (61);
INSERT INTO number__tbl (number_val) VALUES (62);
INSERT INTO number__tbl (number_val) VALUES (63);
INSERT INTO number__tbl (number_val) VALUES (64);
INSERT INTO number__tbl (number_val) VALUES (65);
INSERT INTO number__tbl (number_val) VALUES (66);
INSERT INTO number__tbl (number_val) VALUES (67);
INSERT INTO number__tbl (number_val) VALUES (68);
INSERT INTO number__tbl (number_val) VALUES (69);
INSERT INTO number__tbl (number_val) VALUES (70);
INSERT INTO number__tbl (number_val) VALUES (71);
INSERT INTO number__tbl (number_val) VALUES (72);
INSERT INTO number__tbl (number_val) VALUES (73);
INSERT INTO number__tbl (number_val) VALUES (74);
INSERT INTO number__tbl (number_val) VALUES (75);
INSERT INTO number__tbl (number_val) VALUES (76);
INSERT INTO number__tbl (number_val) VALUES (77);
INSERT INTO number__tbl (number_val) VALUES (78);
INSERT INTO number__tbl (number_val) VALUES (79);
INSERT INTO number__tbl (number_val) VALUES (80);
INSERT INTO number__tbl (number_val) VALUES (81);
INSERT INTO number__tbl (number_val) VALUES (82);
INSERT INTO number__tbl (number_val) VALUES (83);
INSERT INTO number__tbl (number_val) VALUES (84);
INSERT INTO number__tbl (number_val) VALUES (85);
INSERT INTO number__tbl (number_val) VALUES (86);
INSERT INTO number__tbl (number_val) VALUES (87);
INSERT INTO number__tbl (number_val) VALUES (88);
INSERT INTO number__tbl (number_val) VALUES (89);
INSERT INTO number__tbl (number_val) VALUES (90);
INSERT INTO number__tbl (number_val) VALUES (91);
INSERT INTO number__tbl (number_val) VALUES (92);
INSERT INTO number__tbl (number_val) VALUES (93);
INSERT INTO number__tbl (number_val) VALUES (94);
INSERT INTO number__tbl (number_val) VALUES (95);
INSERT INTO number__tbl (number_val) VALUES (96);
INSERT INTO number__tbl (number_val) VALUES (97);
INSERT INTO number__tbl (number_val) VALUES (98);
INSERT INTO number__tbl (number_val) VALUES (99);
INSERT INTO number__tbl (number_val) VALUES (100);
INSERT INTO number__tbl (number_val) VALUES (101);
INSERT INTO number__tbl (number_val) VALUES (102);
INSERT INTO number__tbl (number_val) VALUES (103);
INSERT INTO number__tbl (number_val) VALUES (104);
INSERT INTO number__tbl (number_val) VALUES (105);
INSERT INTO number__tbl (number_val) VALUES (106);
INSERT INTO number__tbl (number_val) VALUES (107);
INSERT INTO number__tbl (number_val) VALUES (108);
INSERT INTO number__tbl (number_val) VALUES (109);
INSERT INTO number__tbl (number_val) VALUES (110);
INSERT INTO number__tbl (number_val) VALUES (111);
INSERT INTO number__tbl (number_val) VALUES (112);
INSERT INTO number__tbl (number_val) VALUES (113);
INSERT INTO number__tbl (number_val) VALUES (114);
INSERT INTO number__tbl (number_val) VALUES (115);
INSERT INTO number__tbl (number_val) VALUES (116);
INSERT INTO number__tbl (number_val) VALUES (117);
INSERT INTO number__tbl (number_val) VALUES (118);
INSERT INTO number__tbl (number_val) VALUES (119);
INSERT INTO number__tbl (number_val) VALUES (120);
INSERT INTO number__tbl (number_val) VALUES (121);
INSERT INTO number__tbl (number_val) VALUES (122);
INSERT INTO number__tbl (number_val) VALUES (123);
INSERT INTO number__tbl (number_val) VALUES (124);
INSERT INTO number__tbl (number_val) VALUES (125);
INSERT INTO number__tbl (number_val) VALUES (126);
INSERT INTO number__tbl (number_val) VALUES (127);
INSERT INTO number__tbl (number_val) VALUES (128);
INSERT INTO number__tbl (number_val) VALUES (129);
INSERT INTO number__tbl (number_val) VALUES (130);
INSERT INTO number__tbl (number_val) VALUES (131);
INSERT INTO number__tbl (number_val) VALUES (132);
INSERT INTO number__tbl (number_val) VALUES (133);
INSERT INTO number__tbl (number_val) VALUES (134);
INSERT INTO number__tbl (number_val) VALUES (135);
INSERT INTO number__tbl (number_val) VALUES (136);
INSERT INTO number__tbl (number_val) VALUES (137);
INSERT INTO number__tbl (number_val) VALUES (138);
INSERT INTO number__tbl (number_val) VALUES (139);
INSERT INTO number__tbl (number_val) VALUES (140);
INSERT INTO number__tbl (number_val) VALUES (141);
INSERT INTO number__tbl (number_val) VALUES (142);
INSERT INTO number__tbl (number_val) VALUES (143);
INSERT INTO number__tbl (number_val) VALUES (144);
INSERT INTO number__tbl (number_val) VALUES (145);
INSERT INTO number__tbl (number_val) VALUES (146);
INSERT INTO number__tbl (number_val) VALUES (147);
INSERT INTO number__tbl (number_val) VALUES (148);
INSERT INTO number__tbl (number_val) VALUES (149);
INSERT INTO number__tbl (number_val) VALUES (150);
INSERT INTO number__tbl (number_val) VALUES (151);
INSERT INTO number__tbl (number_val) VALUES (152);
INSERT INTO number__tbl (number_val) VALUES (153);
INSERT INTO number__tbl (number_val) VALUES (154);
INSERT INTO number__tbl (number_val) VALUES (155);
INSERT INTO number__tbl (number_val) VALUES (156);
INSERT INTO number__tbl (number_val) VALUES (157);
INSERT INTO number__tbl (number_val) VALUES (158);
INSERT INTO number__tbl (number_val) VALUES (159);
INSERT INTO number__tbl (number_val) VALUES (160);
INSERT INTO number__tbl (number_val) VALUES (161);
INSERT INTO number__tbl (number_val) VALUES (162);
INSERT INTO number__tbl (number_val) VALUES (163);
INSERT INTO number__tbl (number_val) VALUES (164);
INSERT INTO number__tbl (number_val) VALUES (165);
INSERT INTO number__tbl (number_val) VALUES (166);
INSERT INTO number__tbl (number_val) VALUES (167);
INSERT INTO number__tbl (number_val) VALUES (168);
INSERT INTO number__tbl (number_val) VALUES (169);
INSERT INTO number__tbl (number_val) VALUES (170);
INSERT INTO number__tbl (number_val) VALUES (171);
INSERT INTO number__tbl (number_val) VALUES (172);
INSERT INTO number__tbl (number_val) VALUES (173);
INSERT INTO number__tbl (number_val) VALUES (174);
INSERT INTO number__tbl (number_val) VALUES (175);
INSERT INTO number__tbl (number_val) VALUES (176);
INSERT INTO number__tbl (number_val) VALUES (177);
INSERT INTO number__tbl (number_val) VALUES (178);
INSERT INTO number__tbl (number_val) VALUES (179);
INSERT INTO number__tbl (number_val) VALUES (180);
INSERT INTO number__tbl (number_val) VALUES (181);
INSERT INTO number__tbl (number_val) VALUES (182);
INSERT INTO number__tbl (number_val) VALUES (183);
INSERT INTO number__tbl (number_val) VALUES (184);
INSERT INTO number__tbl (number_val) VALUES (185);
INSERT INTO number__tbl (number_val) VALUES (186);
INSERT INTO number__tbl (number_val) VALUES (187);
INSERT INTO number__tbl (number_val) VALUES (188);
INSERT INTO number__tbl (number_val) VALUES (189);
INSERT INTO number__tbl (number_val) VALUES (190);
INSERT INTO number__tbl (number_val) VALUES (191);
INSERT INTO number__tbl (number_val) VALUES (192);
INSERT INTO number__tbl (number_val) VALUES (193);
INSERT INTO number__tbl (number_val) VALUES (194);
INSERT INTO number__tbl (number_val) VALUES (195);
INSERT INTO number__tbl (number_val) VALUES (196);
INSERT INTO number__tbl (number_val) VALUES (197);
INSERT INTO number__tbl (number_val) VALUES (198);
INSERT INTO number__tbl (number_val) VALUES (199);
INSERT INTO number__tbl (number_val) VALUES (200);
INSERT INTO number__tbl (number_val) VALUES (201);
INSERT INTO number__tbl (number_val) VALUES (202);
INSERT INTO number__tbl (number_val) VALUES (203);
INSERT INTO number__tbl (number_val) VALUES (204);
INSERT INTO number__tbl (number_val) VALUES (205);
INSERT INTO number__tbl (number_val) VALUES (206);
INSERT INTO number__tbl (number_val) VALUES (207);
INSERT INTO number__tbl (number_val) VALUES (208);
INSERT INTO number__tbl (number_val) VALUES (209);
INSERT INTO number__tbl (number_val) VALUES (210);
INSERT INTO number__tbl (number_val) VALUES (211);
INSERT INTO number__tbl (number_val) VALUES (212);
INSERT INTO number__tbl (number_val) VALUES (213);
INSERT INTO number__tbl (number_val) VALUES (214);
INSERT INTO number__tbl (number_val) VALUES (215);
INSERT INTO number__tbl (number_val) VALUES (216);
INSERT INTO number__tbl (number_val) VALUES (217);
INSERT INTO number__tbl (number_val) VALUES (218);
INSERT INTO number__tbl (number_val) VALUES (219);
INSERT INTO number__tbl (number_val) VALUES (220);
INSERT INTO number__tbl (number_val) VALUES (221);
INSERT INTO number__tbl (number_val) VALUES (222);
INSERT INTO number__tbl (number_val) VALUES (223);
INSERT INTO number__tbl (number_val) VALUES (224);
INSERT INTO number__tbl (number_val) VALUES (225);
INSERT INTO number__tbl (number_val) VALUES (226);
INSERT INTO number__tbl (number_val) VALUES (227);
INSERT INTO number__tbl (number_val) VALUES (228);
INSERT INTO number__tbl (number_val) VALUES (229);
INSERT INTO number__tbl (number_val) VALUES (230);
INSERT INTO number__tbl (number_val) VALUES (231);
INSERT INTO number__tbl (number_val) VALUES (232);
INSERT INTO number__tbl (number_val) VALUES (233);
INSERT INTO number__tbl (number_val) VALUES (234);
INSERT INTO number__tbl (number_val) VALUES (235);
INSERT INTO number__tbl (number_val) VALUES (236);
INSERT INTO number__tbl (number_val) VALUES (237);
INSERT INTO number__tbl (number_val) VALUES (238);
INSERT INTO number__tbl (number_val) VALUES (239);
INSERT INTO number__tbl (number_val) VALUES (240);
INSERT INTO number__tbl (number_val) VALUES (241);
INSERT INTO number__tbl (number_val) VALUES (242);
INSERT INTO number__tbl (number_val) VALUES (243);
INSERT INTO number__tbl (number_val) VALUES (244);
INSERT INTO number__tbl (number_val) VALUES (245);
INSERT INTO number__tbl (number_val) VALUES (246);
INSERT INTO number__tbl (number_val) VALUES (247);
INSERT INTO number__tbl (number_val) VALUES (248);
INSERT INTO number__tbl (number_val) VALUES (249);
INSERT INTO number__tbl (number_val) VALUES (250);
INSERT INTO number__tbl (number_val) VALUES (251);
INSERT INTO number__tbl (number_val) VALUES (252);
INSERT INTO number__tbl (number_val) VALUES (253);
INSERT INTO number__tbl (number_val) VALUES (254);
INSERT INTO number__tbl (number_val) VALUES (255);
INSERT INTO number__tbl (number_val) VALUES (256);
INSERT INTO number__tbl (number_val) VALUES (257);
INSERT INTO number__tbl (number_val) VALUES (258);
INSERT INTO number__tbl (number_val) VALUES (259);
INSERT INTO number__tbl (number_val) VALUES (260);
INSERT INTO number__tbl (number_val) VALUES (261);
INSERT INTO number__tbl (number_val) VALUES (262);
INSERT INTO number__tbl (number_val) VALUES (263);
INSERT INTO number__tbl (number_val) VALUES (264);
INSERT INTO number__tbl (number_val) VALUES (265);
INSERT INTO number__tbl (number_val) VALUES (266);
INSERT INTO number__tbl (number_val) VALUES (267);
INSERT INTO number__tbl (number_val) VALUES (268);
INSERT INTO number__tbl (number_val) VALUES (269);
INSERT INTO number__tbl (number_val) VALUES (270);
INSERT INTO number__tbl (number_val) VALUES (271);
INSERT INTO number__tbl (number_val) VALUES (272);
INSERT INTO number__tbl (number_val) VALUES (273);
INSERT INTO number__tbl (number_val) VALUES (274);
INSERT INTO number__tbl (number_val) VALUES (275);
INSERT INTO number__tbl (number_val) VALUES (276);
INSERT INTO number__tbl (number_val) VALUES (277);
INSERT INTO number__tbl (number_val) VALUES (278);
INSERT INTO number__tbl (number_val) VALUES (279);
INSERT INTO number__tbl (number_val) VALUES (280);
INSERT INTO number__tbl (number_val) VALUES (281);
INSERT INTO number__tbl (number_val) VALUES (282);
INSERT INTO number__tbl (number_val) VALUES (283);
INSERT INTO number__tbl (number_val) VALUES (284);
INSERT INTO number__tbl (number_val) VALUES (285);
INSERT INTO number__tbl (number_val) VALUES (286);
INSERT INTO number__tbl (number_val) VALUES (287);
INSERT INTO number__tbl (number_val) VALUES (288);
INSERT INTO number__tbl (number_val) VALUES (289);
INSERT INTO number__tbl (number_val) VALUES (290);
INSERT INTO number__tbl (number_val) VALUES (291);
INSERT INTO number__tbl (number_val) VALUES (292);
INSERT INTO number__tbl (number_val) VALUES (293);
INSERT INTO number__tbl (number_val) VALUES (294);
INSERT INTO number__tbl (number_val) VALUES (295);
INSERT INTO number__tbl (number_val) VALUES (296);
INSERT INTO number__tbl (number_val) VALUES (297);
INSERT INTO number__tbl (number_val) VALUES (298);
INSERT INTO number__tbl (number_val) VALUES (299);
INSERT INTO number__tbl (number_val) VALUES (300);
INSERT INTO number__tbl (number_val) VALUES (301);
INSERT INTO number__tbl (number_val) VALUES (302);
INSERT INTO number__tbl (number_val) VALUES (303);
INSERT INTO number__tbl (number_val) VALUES (304);
INSERT INTO number__tbl (number_val) VALUES (305);
INSERT INTO number__tbl (number_val) VALUES (306);
INSERT INTO number__tbl (number_val) VALUES (307);
INSERT INTO number__tbl (number_val) VALUES (308);
INSERT INTO number__tbl (number_val) VALUES (309);
INSERT INTO number__tbl (number_val) VALUES (310);
INSERT INTO number__tbl (number_val) VALUES (311);
INSERT INTO number__tbl (number_val) VALUES (312);
INSERT INTO number__tbl (number_val) VALUES (313);
INSERT INTO number__tbl (number_val) VALUES (314);
INSERT INTO number__tbl (number_val) VALUES (315);
INSERT INTO number__tbl (number_val) VALUES (316);
INSERT INTO number__tbl (number_val) VALUES (317);
INSERT INTO number__tbl (number_val) VALUES (318);
INSERT INTO number__tbl (number_val) VALUES (319);
INSERT INTO number__tbl (number_val) VALUES (320);
INSERT INTO number__tbl (number_val) VALUES (321);
INSERT INTO number__tbl (number_val) VALUES (322);
INSERT INTO number__tbl (number_val) VALUES (323);
INSERT INTO number__tbl (number_val) VALUES (324);
INSERT INTO number__tbl (number_val) VALUES (325);
INSERT INTO number__tbl (number_val) VALUES (326);
INSERT INTO number__tbl (number_val) VALUES (327);
INSERT INTO number__tbl (number_val) VALUES (328);
INSERT INTO number__tbl (number_val) VALUES (329);
INSERT INTO number__tbl (number_val) VALUES (330);
INSERT INTO number__tbl (number_val) VALUES (331);
INSERT INTO number__tbl (number_val) VALUES (332);
INSERT INTO number__tbl (number_val) VALUES (333);
INSERT INTO number__tbl (number_val) VALUES (334);
INSERT INTO number__tbl (number_val) VALUES (335);
INSERT INTO number__tbl (number_val) VALUES (336);
INSERT INTO number__tbl (number_val) VALUES (337);
INSERT INTO number__tbl (number_val) VALUES (338);
INSERT INTO number__tbl (number_val) VALUES (339);
INSERT INTO number__tbl (number_val) VALUES (340);
INSERT INTO number__tbl (number_val) VALUES (341);
INSERT INTO number__tbl (number_val) VALUES (342);
INSERT INTO number__tbl (number_val) VALUES (343);
INSERT INTO number__tbl (number_val) VALUES (344);
INSERT INTO number__tbl (number_val) VALUES (345);
INSERT INTO number__tbl (number_val) VALUES (346);
INSERT INTO number__tbl (number_val) VALUES (347);
INSERT INTO number__tbl (number_val) VALUES (348);
INSERT INTO number__tbl (number_val) VALUES (349);
INSERT INTO number__tbl (number_val) VALUES (350);
INSERT INTO number__tbl (number_val) VALUES (351);
INSERT INTO number__tbl (number_val) VALUES (352);
INSERT INTO number__tbl (number_val) VALUES (353);
INSERT INTO number__tbl (number_val) VALUES (354);
INSERT INTO number__tbl (number_val) VALUES (355);
INSERT INTO number__tbl (number_val) VALUES (356);
INSERT INTO number__tbl (number_val) VALUES (357);
INSERT INTO number__tbl (number_val) VALUES (358);
INSERT INTO number__tbl (number_val) VALUES (359);
INSERT INTO number__tbl (number_val) VALUES (360);
INSERT INTO number__tbl (number_val) VALUES (361);
INSERT INTO number__tbl (number_val) VALUES (362);
INSERT INTO number__tbl (number_val) VALUES (363);
INSERT INTO number__tbl (number_val) VALUES (364);
INSERT INTO number__tbl (number_val) VALUES (365);
INSERT INTO number__tbl (number_val) VALUES (366);
INSERT INTO number__tbl (number_val) VALUES (367);
INSERT INTO number__tbl (number_val) VALUES (368);
INSERT INTO number__tbl (number_val) VALUES (369);
INSERT INTO number__tbl (number_val) VALUES (370);
INSERT INTO number__tbl (number_val) VALUES (371);
INSERT INTO number__tbl (number_val) VALUES (372);
INSERT INTO number__tbl (number_val) VALUES (373);
INSERT INTO number__tbl (number_val) VALUES (374);
INSERT INTO number__tbl (number_val) VALUES (375);
INSERT INTO number__tbl (number_val) VALUES (376);
INSERT INTO number__tbl (number_val) VALUES (377);
INSERT INTO number__tbl (number_val) VALUES (378);
INSERT INTO number__tbl (number_val) VALUES (379);
INSERT INTO number__tbl (number_val) VALUES (380);
INSERT INTO number__tbl (number_val) VALUES (381);
INSERT INTO number__tbl (number_val) VALUES (382);
INSERT INTO number__tbl (number_val) VALUES (383);
INSERT INTO number__tbl (number_val) VALUES (384);
INSERT INTO number__tbl (number_val) VALUES (385);
INSERT INTO number__tbl (number_val) VALUES (386);
INSERT INTO number__tbl (number_val) VALUES (387);
INSERT INTO number__tbl (number_val) VALUES (388);
INSERT INTO number__tbl (number_val) VALUES (389);
INSERT INTO number__tbl (number_val) VALUES (390);
INSERT INTO number__tbl (number_val) VALUES (391);
INSERT INTO number__tbl (number_val) VALUES (392);
INSERT INTO number__tbl (number_val) VALUES (393);
INSERT INTO number__tbl (number_val) VALUES (394);
INSERT INTO number__tbl (number_val) VALUES (395);
INSERT INTO number__tbl (number_val) VALUES (396);
INSERT INTO number__tbl (number_val) VALUES (397);
INSERT INTO number__tbl (number_val) VALUES (398);
INSERT INTO number__tbl (number_val) VALUES (399);
INSERT INTO number__tbl (number_val) VALUES (400);
INSERT INTO number__tbl (number_val) VALUES (401);
INSERT INTO number__tbl (number_val) VALUES (402);
INSERT INTO number__tbl (number_val) VALUES (403);
INSERT INTO number__tbl (number_val) VALUES (404);
INSERT INTO number__tbl (number_val) VALUES (405);
INSERT INTO number__tbl (number_val) VALUES (406);
INSERT INTO number__tbl (number_val) VALUES (407);
INSERT INTO number__tbl (number_val) VALUES (408);
INSERT INTO number__tbl (number_val) VALUES (409);
INSERT INTO number__tbl (number_val) VALUES (410);
INSERT INTO number__tbl (number_val) VALUES (411);
INSERT INTO number__tbl (number_val) VALUES (412);
INSERT INTO number__tbl (number_val) VALUES (413);
INSERT INTO number__tbl (number_val) VALUES (414);
INSERT INTO number__tbl (number_val) VALUES (415);
INSERT INTO number__tbl (number_val) VALUES (416);
INSERT INTO number__tbl (number_val) VALUES (417);
INSERT INTO number__tbl (number_val) VALUES (418);
INSERT INTO number__tbl (number_val) VALUES (419);
INSERT INTO number__tbl (number_val) VALUES (420);
INSERT INTO number__tbl (number_val) VALUES (421);
INSERT INTO number__tbl (number_val) VALUES (422);
INSERT INTO number__tbl (number_val) VALUES (423);
INSERT INTO number__tbl (number_val) VALUES (424);
INSERT INTO number__tbl (number_val) VALUES (425);
INSERT INTO number__tbl (number_val) VALUES (426);
INSERT INTO number__tbl (number_val) VALUES (427);
INSERT INTO number__tbl (number_val) VALUES (428);
INSERT INTO number__tbl (number_val) VALUES (429);
INSERT INTO number__tbl (number_val) VALUES (430);
INSERT INTO number__tbl (number_val) VALUES (431);
INSERT INTO number__tbl (number_val) VALUES (432);
INSERT INTO number__tbl (number_val) VALUES (433);
INSERT INTO number__tbl (number_val) VALUES (434);
INSERT INTO number__tbl (number_val) VALUES (435);
INSERT INTO number__tbl (number_val) VALUES (436);
INSERT INTO number__tbl (number_val) VALUES (437);
INSERT INTO number__tbl (number_val) VALUES (438);
INSERT INTO number__tbl (number_val) VALUES (439);
INSERT INTO number__tbl (number_val) VALUES (440);
INSERT INTO number__tbl (number_val) VALUES (441);
INSERT INTO number__tbl (number_val) VALUES (442);
INSERT INTO number__tbl (number_val) VALUES (443);
INSERT INTO number__tbl (number_val) VALUES (444);
INSERT INTO number__tbl (number_val) VALUES (445);
INSERT INTO number__tbl (number_val) VALUES (446);
INSERT INTO number__tbl (number_val) VALUES (447);
INSERT INTO number__tbl (number_val) VALUES (448);
INSERT INTO number__tbl (number_val) VALUES (449);
INSERT INTO number__tbl (number_val) VALUES (450);
INSERT INTO number__tbl (number_val) VALUES (451);
INSERT INTO number__tbl (number_val) VALUES (452);
INSERT INTO number__tbl (number_val) VALUES (453);
INSERT INTO number__tbl (number_val) VALUES (454);
INSERT INTO number__tbl (number_val) VALUES (455);
INSERT INTO number__tbl (number_val) VALUES (456);
INSERT INTO number__tbl (number_val) VALUES (457);
INSERT INTO number__tbl (number_val) VALUES (458);
INSERT INTO number__tbl (number_val) VALUES (459);
INSERT INTO number__tbl (number_val) VALUES (460);
INSERT INTO number__tbl (number_val) VALUES (461);
INSERT INTO number__tbl (number_val) VALUES (462);
INSERT INTO number__tbl (number_val) VALUES (463);
INSERT INTO number__tbl (number_val) VALUES (464);
INSERT INTO number__tbl (number_val) VALUES (465);
INSERT INTO number__tbl (number_val) VALUES (466);
INSERT INTO number__tbl (number_val) VALUES (467);
INSERT INTO number__tbl (number_val) VALUES (468);
INSERT INTO number__tbl (number_val) VALUES (469);
INSERT INTO number__tbl (number_val) VALUES (470);
INSERT INTO number__tbl (number_val) VALUES (471);
INSERT INTO number__tbl (number_val) VALUES (472);
INSERT INTO number__tbl (number_val) VALUES (473);
INSERT INTO number__tbl (number_val) VALUES (474);
INSERT INTO number__tbl (number_val) VALUES (475);
INSERT INTO number__tbl (number_val) VALUES (476);
INSERT INTO number__tbl (number_val) VALUES (477);
INSERT INTO number__tbl (number_val) VALUES (478);
INSERT INTO number__tbl (number_val) VALUES (479);
INSERT INTO number__tbl (number_val) VALUES (480);
INSERT INTO number__tbl (number_val) VALUES (481);
INSERT INTO number__tbl (number_val) VALUES (482);
INSERT INTO number__tbl (number_val) VALUES (483);
INSERT INTO number__tbl (number_val) VALUES (484);
INSERT INTO number__tbl (number_val) VALUES (485);
INSERT INTO number__tbl (number_val) VALUES (486);
INSERT INTO number__tbl (number_val) VALUES (487);
INSERT INTO number__tbl (number_val) VALUES (488);
INSERT INTO number__tbl (number_val) VALUES (489);
INSERT INTO number__tbl (number_val) VALUES (490);
INSERT INTO number__tbl (number_val) VALUES (491);
INSERT INTO number__tbl (number_val) VALUES (492);
INSERT INTO number__tbl (number_val) VALUES (493);
INSERT INTO number__tbl (number_val) VALUES (494);
INSERT INTO number__tbl (number_val) VALUES (495);
INSERT INTO number__tbl (number_val) VALUES (496);
INSERT INTO number__tbl (number_val) VALUES (497);
INSERT INTO number__tbl (number_val) VALUES (498);
INSERT INTO number__tbl (number_val) VALUES (499);
INSERT INTO number__tbl (number_val) VALUES (500);
INSERT INTO number__tbl (number_val) VALUES (501);
INSERT INTO number__tbl (number_val) VALUES (502);
INSERT INTO number__tbl (number_val) VALUES (503);
INSERT INTO number__tbl (number_val) VALUES (504);
INSERT INTO number__tbl (number_val) VALUES (505);
INSERT INTO number__tbl (number_val) VALUES (506);
INSERT INTO number__tbl (number_val) VALUES (507);
INSERT INTO number__tbl (number_val) VALUES (508);
INSERT INTO number__tbl (number_val) VALUES (509);
INSERT INTO number__tbl (number_val) VALUES (510);
INSERT INTO number__tbl (number_val) VALUES (511);
INSERT INTO number__tbl (number_val) VALUES (512);
INSERT INTO number__tbl (number_val) VALUES (513);
INSERT INTO number__tbl (number_val) VALUES (514);
INSERT INTO number__tbl (number_val) VALUES (515);
INSERT INTO number__tbl (number_val) VALUES (516);
INSERT INTO number__tbl (number_val) VALUES (517);
INSERT INTO number__tbl (number_val) VALUES (518);
INSERT INTO number__tbl (number_val) VALUES (519);
INSERT INTO number__tbl (number_val) VALUES (520);
INSERT INTO number__tbl (number_val) VALUES (521);
INSERT INTO number__tbl (number_val) VALUES (522);
INSERT INTO number__tbl (number_val) VALUES (523);
INSERT INTO number__tbl (number_val) VALUES (524);
INSERT INTO number__tbl (number_val) VALUES (525);
INSERT INTO number__tbl (number_val) VALUES (526);
INSERT INTO number__tbl (number_val) VALUES (527);
INSERT INTO number__tbl (number_val) VALUES (528);
INSERT INTO number__tbl (number_val) VALUES (529);
INSERT INTO number__tbl (number_val) VALUES (530);
INSERT INTO number__tbl (number_val) VALUES (531);
INSERT INTO number__tbl (number_val) VALUES (532);
INSERT INTO number__tbl (number_val) VALUES (533);
INSERT INTO number__tbl (number_val) VALUES (534);
INSERT INTO number__tbl (number_val) VALUES (535);
INSERT INTO number__tbl (number_val) VALUES (536);
INSERT INTO number__tbl (number_val) VALUES (537);
INSERT INTO number__tbl (number_val) VALUES (538);
INSERT INTO number__tbl (number_val) VALUES (539);
INSERT INTO number__tbl (number_val) VALUES (540);
INSERT INTO number__tbl (number_val) VALUES (541);
INSERT INTO number__tbl (number_val) VALUES (542);
INSERT INTO number__tbl (number_val) VALUES (543);
INSERT INTO number__tbl (number_val) VALUES (544);
INSERT INTO number__tbl (number_val) VALUES (545);
INSERT INTO number__tbl (number_val) VALUES (546);
INSERT INTO number__tbl (number_val) VALUES (547);
INSERT INTO number__tbl (number_val) VALUES (548);
INSERT INTO number__tbl (number_val) VALUES (549);
INSERT INTO number__tbl (number_val) VALUES (550);
INSERT INTO number__tbl (number_val) VALUES (551);
INSERT INTO number__tbl (number_val) VALUES (552);
INSERT INTO number__tbl (number_val) VALUES (553);
INSERT INTO number__tbl (number_val) VALUES (554);
INSERT INTO number__tbl (number_val) VALUES (555);
INSERT INTO number__tbl (number_val) VALUES (556);
INSERT INTO number__tbl (number_val) VALUES (557);
INSERT INTO number__tbl (number_val) VALUES (558);
INSERT INTO number__tbl (number_val) VALUES (559);
INSERT INTO number__tbl (number_val) VALUES (560);
INSERT INTO number__tbl (number_val) VALUES (561);
INSERT INTO number__tbl (number_val) VALUES (562);
INSERT INTO number__tbl (number_val) VALUES (563);
INSERT INTO number__tbl (number_val) VALUES (564);
INSERT INTO number__tbl (number_val) VALUES (565);
INSERT INTO number__tbl (number_val) VALUES (566);
INSERT INTO number__tbl (number_val) VALUES (567);
INSERT INTO number__tbl (number_val) VALUES (568);
INSERT INTO number__tbl (number_val) VALUES (569);
INSERT INTO number__tbl (number_val) VALUES (570);
INSERT INTO number__tbl (number_val) VALUES (571);
INSERT INTO number__tbl (number_val) VALUES (572);
INSERT INTO number__tbl (number_val) VALUES (573);
INSERT INTO number__tbl (number_val) VALUES (574);
INSERT INTO number__tbl (number_val) VALUES (575);
INSERT INTO number__tbl (number_val) VALUES (576);
INSERT INTO number__tbl (number_val) VALUES (577);
INSERT INTO number__tbl (number_val) VALUES (578);
INSERT INTO number__tbl (number_val) VALUES (579);
INSERT INTO number__tbl (number_val) VALUES (580);
INSERT INTO number__tbl (number_val) VALUES (581);
INSERT INTO number__tbl (number_val) VALUES (582);
INSERT INTO number__tbl (number_val) VALUES (583);
INSERT INTO number__tbl (number_val) VALUES (584);
INSERT INTO number__tbl (number_val) VALUES (585);
INSERT INTO number__tbl (number_val) VALUES (586);
INSERT INTO number__tbl (number_val) VALUES (587);
INSERT INTO number__tbl (number_val) VALUES (588);
INSERT INTO number__tbl (number_val) VALUES (589);
INSERT INTO number__tbl (number_val) VALUES (590);
INSERT INTO number__tbl (number_val) VALUES (591);
INSERT INTO number__tbl (number_val) VALUES (592);
INSERT INTO number__tbl (number_val) VALUES (593);
INSERT INTO number__tbl (number_val) VALUES (594);
INSERT INTO number__tbl (number_val) VALUES (595);
INSERT INTO number__tbl (number_val) VALUES (596);
INSERT INTO number__tbl (number_val) VALUES (597);
INSERT INTO number__tbl (number_val) VALUES (598);
INSERT INTO number__tbl (number_val) VALUES (599);
INSERT INTO number__tbl (number_val) VALUES (600);
INSERT INTO number__tbl (number_val) VALUES (601);
INSERT INTO number__tbl (number_val) VALUES (602);
INSERT INTO number__tbl (number_val) VALUES (603);
INSERT INTO number__tbl (number_val) VALUES (604);
INSERT INTO number__tbl (number_val) VALUES (605);
INSERT INTO number__tbl (number_val) VALUES (606);
INSERT INTO number__tbl (number_val) VALUES (607);
INSERT INTO number__tbl (number_val) VALUES (608);
INSERT INTO number__tbl (number_val) VALUES (609);
INSERT INTO number__tbl (number_val) VALUES (610);
INSERT INTO number__tbl (number_val) VALUES (611);
INSERT INTO number__tbl (number_val) VALUES (612);
INSERT INTO number__tbl (number_val) VALUES (613);
INSERT INTO number__tbl (number_val) VALUES (614);
INSERT INTO number__tbl (number_val) VALUES (615);
INSERT INTO number__tbl (number_val) VALUES (616);
INSERT INTO number__tbl (number_val) VALUES (617);
INSERT INTO number__tbl (number_val) VALUES (618);
INSERT INTO number__tbl (number_val) VALUES (619);
INSERT INTO number__tbl (number_val) VALUES (620);
INSERT INTO number__tbl (number_val) VALUES (621);
INSERT INTO number__tbl (number_val) VALUES (622);
INSERT INTO number__tbl (number_val) VALUES (623);
INSERT INTO number__tbl (number_val) VALUES (624);
INSERT INTO number__tbl (number_val) VALUES (625);
INSERT INTO number__tbl (number_val) VALUES (626);
INSERT INTO number__tbl (number_val) VALUES (627);
INSERT INTO number__tbl (number_val) VALUES (628);
INSERT INTO number__tbl (number_val) VALUES (629);
INSERT INTO number__tbl (number_val) VALUES (630);
INSERT INTO number__tbl (number_val) VALUES (631);
INSERT INTO number__tbl (number_val) VALUES (632);
INSERT INTO number__tbl (number_val) VALUES (633);
INSERT INTO number__tbl (number_val) VALUES (634);
INSERT INTO number__tbl (number_val) VALUES (635);
INSERT INTO number__tbl (number_val) VALUES (636);
INSERT INTO number__tbl (number_val) VALUES (637);
INSERT INTO number__tbl (number_val) VALUES (638);
INSERT INTO number__tbl (number_val) VALUES (639);
INSERT INTO number__tbl (number_val) VALUES (640);
INSERT INTO number__tbl (number_val) VALUES (641);
INSERT INTO number__tbl (number_val) VALUES (642);
INSERT INTO number__tbl (number_val) VALUES (643);
INSERT INTO number__tbl (number_val) VALUES (644);
INSERT INTO number__tbl (number_val) VALUES (645);
INSERT INTO number__tbl (number_val) VALUES (646);
INSERT INTO number__tbl (number_val) VALUES (647);
INSERT INTO number__tbl (number_val) VALUES (648);
INSERT INTO number__tbl (number_val) VALUES (649);
INSERT INTO number__tbl (number_val) VALUES (650);
INSERT INTO number__tbl (number_val) VALUES (651);
INSERT INTO number__tbl (number_val) VALUES (652);
INSERT INTO number__tbl (number_val) VALUES (653);
INSERT INTO number__tbl (number_val) VALUES (654);
INSERT INTO number__tbl (number_val) VALUES (655);
INSERT INTO number__tbl (number_val) VALUES (656);
INSERT INTO number__tbl (number_val) VALUES (657);
INSERT INTO number__tbl (number_val) VALUES (658);
INSERT INTO number__tbl (number_val) VALUES (659);
INSERT INTO number__tbl (number_val) VALUES (660);
INSERT INTO number__tbl (number_val) VALUES (661);
INSERT INTO number__tbl (number_val) VALUES (662);
INSERT INTO number__tbl (number_val) VALUES (663);
INSERT INTO number__tbl (number_val) VALUES (664);
INSERT INTO number__tbl (number_val) VALUES (665);
INSERT INTO number__tbl (number_val) VALUES (666);
INSERT INTO number__tbl (number_val) VALUES (667);
INSERT INTO number__tbl (number_val) VALUES (668);
INSERT INTO number__tbl (number_val) VALUES (669);
INSERT INTO number__tbl (number_val) VALUES (670);
INSERT INTO number__tbl (number_val) VALUES (671);
INSERT INTO number__tbl (number_val) VALUES (672);
INSERT INTO number__tbl (number_val) VALUES (673);
INSERT INTO number__tbl (number_val) VALUES (674);
INSERT INTO number__tbl (number_val) VALUES (675);
INSERT INTO number__tbl (number_val) VALUES (676);
INSERT INTO number__tbl (number_val) VALUES (677);
INSERT INTO number__tbl (number_val) VALUES (678);
INSERT INTO number__tbl (number_val) VALUES (679);
INSERT INTO number__tbl (number_val) VALUES (680);
INSERT INTO number__tbl (number_val) VALUES (681);
INSERT INTO number__tbl (number_val) VALUES (682);
INSERT INTO number__tbl (number_val) VALUES (683);
INSERT INTO number__tbl (number_val) VALUES (684);
INSERT INTO number__tbl (number_val) VALUES (685);
INSERT INTO number__tbl (number_val) VALUES (686);
INSERT INTO number__tbl (number_val) VALUES (687);
INSERT INTO number__tbl (number_val) VALUES (688);
INSERT INTO number__tbl (number_val) VALUES (689);
INSERT INTO number__tbl (number_val) VALUES (690);
INSERT INTO number__tbl (number_val) VALUES (691);
INSERT INTO number__tbl (number_val) VALUES (692);
INSERT INTO number__tbl (number_val) VALUES (693);
INSERT INTO number__tbl (number_val) VALUES (694);
INSERT INTO number__tbl (number_val) VALUES (695);
INSERT INTO number__tbl (number_val) VALUES (696);
INSERT INTO number__tbl (number_val) VALUES (697);
INSERT INTO number__tbl (number_val) VALUES (698);
INSERT INTO number__tbl (number_val) VALUES (699);
INSERT INTO number__tbl (number_val) VALUES (700);
INSERT INTO number__tbl (number_val) VALUES (701);
INSERT INTO number__tbl (number_val) VALUES (702);
INSERT INTO number__tbl (number_val) VALUES (703);
INSERT INTO number__tbl (number_val) VALUES (704);
INSERT INTO number__tbl (number_val) VALUES (705);
INSERT INTO number__tbl (number_val) VALUES (706);
INSERT INTO number__tbl (number_val) VALUES (707);
INSERT INTO number__tbl (number_val) VALUES (708);
INSERT INTO number__tbl (number_val) VALUES (709);
INSERT INTO number__tbl (number_val) VALUES (710);
INSERT INTO number__tbl (number_val) VALUES (711);
INSERT INTO number__tbl (number_val) VALUES (712);
INSERT INTO number__tbl (number_val) VALUES (713);
INSERT INTO number__tbl (number_val) VALUES (714);
INSERT INTO number__tbl (number_val) VALUES (715);
INSERT INTO number__tbl (number_val) VALUES (716);
INSERT INTO number__tbl (number_val) VALUES (717);
INSERT INTO number__tbl (number_val) VALUES (718);
INSERT INTO number__tbl (number_val) VALUES (719);
INSERT INTO number__tbl (number_val) VALUES (720);
INSERT INTO number__tbl (number_val) VALUES (721);
INSERT INTO number__tbl (number_val) VALUES (722);
INSERT INTO number__tbl (number_val) VALUES (723);
INSERT INTO number__tbl (number_val) VALUES (724);
INSERT INTO number__tbl (number_val) VALUES (725);
INSERT INTO number__tbl (number_val) VALUES (726);
INSERT INTO number__tbl (number_val) VALUES (727);
INSERT INTO number__tbl (number_val) VALUES (728);
INSERT INTO number__tbl (number_val) VALUES (729);
INSERT INTO number__tbl (number_val) VALUES (730);
INSERT INTO number__tbl (number_val) VALUES (731);
INSERT INTO number__tbl (number_val) VALUES (732);
INSERT INTO number__tbl (number_val) VALUES (733);
INSERT INTO number__tbl (number_val) VALUES (734);
INSERT INTO number__tbl (number_val) VALUES (735);
INSERT INTO number__tbl (number_val) VALUES (736);
INSERT INTO number__tbl (number_val) VALUES (737);
INSERT INTO number__tbl (number_val) VALUES (738);
INSERT INTO number__tbl (number_val) VALUES (739);
INSERT INTO number__tbl (number_val) VALUES (740);
INSERT INTO number__tbl (number_val) VALUES (741);
INSERT INTO number__tbl (number_val) VALUES (742);
INSERT INTO number__tbl (number_val) VALUES (743);
INSERT INTO number__tbl (number_val) VALUES (744);
INSERT INTO number__tbl (number_val) VALUES (745);
INSERT INTO number__tbl (number_val) VALUES (746);
INSERT INTO number__tbl (number_val) VALUES (747);
INSERT INTO number__tbl (number_val) VALUES (748);
INSERT INTO number__tbl (number_val) VALUES (749);
INSERT INTO number__tbl (number_val) VALUES (750);
INSERT INTO number__tbl (number_val) VALUES (751);
INSERT INTO number__tbl (number_val) VALUES (752);
INSERT INTO number__tbl (number_val) VALUES (753);
INSERT INTO number__tbl (number_val) VALUES (754);
INSERT INTO number__tbl (number_val) VALUES (755);
INSERT INTO number__tbl (number_val) VALUES (756);
INSERT INTO number__tbl (number_val) VALUES (757);
INSERT INTO number__tbl (number_val) VALUES (758);
INSERT INTO number__tbl (number_val) VALUES (759);
INSERT INTO number__tbl (number_val) VALUES (760);
INSERT INTO number__tbl (number_val) VALUES (761);
INSERT INTO number__tbl (number_val) VALUES (762);
INSERT INTO number__tbl (number_val) VALUES (763);
INSERT INTO number__tbl (number_val) VALUES (764);
INSERT INTO number__tbl (number_val) VALUES (765);
INSERT INTO number__tbl (number_val) VALUES (766);
INSERT INTO number__tbl (number_val) VALUES (767);
INSERT INTO number__tbl (number_val) VALUES (768);
INSERT INTO number__tbl (number_val) VALUES (769);
INSERT INTO number__tbl (number_val) VALUES (770);
INSERT INTO number__tbl (number_val) VALUES (771);
INSERT INTO number__tbl (number_val) VALUES (772);
INSERT INTO number__tbl (number_val) VALUES (773);
INSERT INTO number__tbl (number_val) VALUES (774);
INSERT INTO number__tbl (number_val) VALUES (775);
INSERT INTO number__tbl (number_val) VALUES (776);
INSERT INTO number__tbl (number_val) VALUES (777);
INSERT INTO number__tbl (number_val) VALUES (778);
INSERT INTO number__tbl (number_val) VALUES (779);
INSERT INTO number__tbl (number_val) VALUES (780);
INSERT INTO number__tbl (number_val) VALUES (781);
INSERT INTO number__tbl (number_val) VALUES (782);
INSERT INTO number__tbl (number_val) VALUES (783);
INSERT INTO number__tbl (number_val) VALUES (784);
INSERT INTO number__tbl (number_val) VALUES (785);
INSERT INTO number__tbl (number_val) VALUES (786);
INSERT INTO number__tbl (number_val) VALUES (787);
INSERT INTO number__tbl (number_val) VALUES (788);
INSERT INTO number__tbl (number_val) VALUES (789);
INSERT INTO number__tbl (number_val) VALUES (790);
INSERT INTO number__tbl (number_val) VALUES (791);
INSERT INTO number__tbl (number_val) VALUES (792);
INSERT INTO number__tbl (number_val) VALUES (793);
INSERT INTO number__tbl (number_val) VALUES (794);
INSERT INTO number__tbl (number_val) VALUES (795);
INSERT INTO number__tbl (number_val) VALUES (796);
INSERT INTO number__tbl (number_val) VALUES (797);
INSERT INTO number__tbl (number_val) VALUES (798);
INSERT INTO number__tbl (number_val) VALUES (799);
INSERT INTO number__tbl (number_val) VALUES (800);
INSERT INTO number__tbl (number_val) VALUES (801);
INSERT INTO number__tbl (number_val) VALUES (802);
INSERT INTO number__tbl (number_val) VALUES (803);
INSERT INTO number__tbl (number_val) VALUES (804);
INSERT INTO number__tbl (number_val) VALUES (805);
INSERT INTO number__tbl (number_val) VALUES (806);
INSERT INTO number__tbl (number_val) VALUES (807);
INSERT INTO number__tbl (number_val) VALUES (808);
INSERT INTO number__tbl (number_val) VALUES (809);
INSERT INTO number__tbl (number_val) VALUES (810);
INSERT INTO number__tbl (number_val) VALUES (811);
INSERT INTO number__tbl (number_val) VALUES (812);
INSERT INTO number__tbl (number_val) VALUES (813);
INSERT INTO number__tbl (number_val) VALUES (814);
INSERT INTO number__tbl (number_val) VALUES (815);
INSERT INTO number__tbl (number_val) VALUES (816);
INSERT INTO number__tbl (number_val) VALUES (817);
INSERT INTO number__tbl (number_val) VALUES (818);
INSERT INTO number__tbl (number_val) VALUES (819);
INSERT INTO number__tbl (number_val) VALUES (820);
INSERT INTO number__tbl (number_val) VALUES (821);
INSERT INTO number__tbl (number_val) VALUES (822);
INSERT INTO number__tbl (number_val) VALUES (823);
INSERT INTO number__tbl (number_val) VALUES (824);
INSERT INTO number__tbl (number_val) VALUES (825);
INSERT INTO number__tbl (number_val) VALUES (826);
INSERT INTO number__tbl (number_val) VALUES (827);
INSERT INTO number__tbl (number_val) VALUES (828);
INSERT INTO number__tbl (number_val) VALUES (829);
INSERT INTO number__tbl (number_val) VALUES (830);
INSERT INTO number__tbl (number_val) VALUES (831);
INSERT INTO number__tbl (number_val) VALUES (832);
INSERT INTO number__tbl (number_val) VALUES (833);
INSERT INTO number__tbl (number_val) VALUES (834);
INSERT INTO number__tbl (number_val) VALUES (835);
INSERT INTO number__tbl (number_val) VALUES (836);
INSERT INTO number__tbl (number_val) VALUES (837);
INSERT INTO number__tbl (number_val) VALUES (838);
INSERT INTO number__tbl (number_val) VALUES (839);
INSERT INTO number__tbl (number_val) VALUES (840);
INSERT INTO number__tbl (number_val) VALUES (841);
INSERT INTO number__tbl (number_val) VALUES (842);
INSERT INTO number__tbl (number_val) VALUES (843);
INSERT INTO number__tbl (number_val) VALUES (844);
INSERT INTO number__tbl (number_val) VALUES (845);
INSERT INTO number__tbl (number_val) VALUES (846);
INSERT INTO number__tbl (number_val) VALUES (847);
INSERT INTO number__tbl (number_val) VALUES (848);
INSERT INTO number__tbl (number_val) VALUES (849);
INSERT INTO number__tbl (number_val) VALUES (850);
INSERT INTO number__tbl (number_val) VALUES (851);
INSERT INTO number__tbl (number_val) VALUES (852);
INSERT INTO number__tbl (number_val) VALUES (853);
INSERT INTO number__tbl (number_val) VALUES (854);
INSERT INTO number__tbl (number_val) VALUES (855);
INSERT INTO number__tbl (number_val) VALUES (856);
INSERT INTO number__tbl (number_val) VALUES (857);
INSERT INTO number__tbl (number_val) VALUES (858);
INSERT INTO number__tbl (number_val) VALUES (859);
INSERT INTO number__tbl (number_val) VALUES (860);
INSERT INTO number__tbl (number_val) VALUES (861);
INSERT INTO number__tbl (number_val) VALUES (862);
INSERT INTO number__tbl (number_val) VALUES (863);
INSERT INTO number__tbl (number_val) VALUES (864);
INSERT INTO number__tbl (number_val) VALUES (865);
INSERT INTO number__tbl (number_val) VALUES (866);
INSERT INTO number__tbl (number_val) VALUES (867);
INSERT INTO number__tbl (number_val) VALUES (868);
INSERT INTO number__tbl (number_val) VALUES (869);
INSERT INTO number__tbl (number_val) VALUES (870);
INSERT INTO number__tbl (number_val) VALUES (871);
INSERT INTO number__tbl (number_val) VALUES (872);
INSERT INTO number__tbl (number_val) VALUES (873);
INSERT INTO number__tbl (number_val) VALUES (874);
INSERT INTO number__tbl (number_val) VALUES (875);
INSERT INTO number__tbl (number_val) VALUES (876);
INSERT INTO number__tbl (number_val) VALUES (877);
INSERT INTO number__tbl (number_val) VALUES (878);
INSERT INTO number__tbl (number_val) VALUES (879);
INSERT INTO number__tbl (number_val) VALUES (880);
INSERT INTO number__tbl (number_val) VALUES (881);
INSERT INTO number__tbl (number_val) VALUES (882);
INSERT INTO number__tbl (number_val) VALUES (883);
INSERT INTO number__tbl (number_val) VALUES (884);
INSERT INTO number__tbl (number_val) VALUES (885);
INSERT INTO number__tbl (number_val) VALUES (886);
INSERT INTO number__tbl (number_val) VALUES (887);
INSERT INTO number__tbl (number_val) VALUES (888);
INSERT INTO number__tbl (number_val) VALUES (889);
INSERT INTO number__tbl (number_val) VALUES (890);
INSERT INTO number__tbl (number_val) VALUES (891);
INSERT INTO number__tbl (number_val) VALUES (892);
INSERT INTO number__tbl (number_val) VALUES (893);
INSERT INTO number__tbl (number_val) VALUES (894);
INSERT INTO number__tbl (number_val) VALUES (895);
INSERT INTO number__tbl (number_val) VALUES (896);
INSERT INTO number__tbl (number_val) VALUES (897);
INSERT INTO number__tbl (number_val) VALUES (898);
INSERT INTO number__tbl (number_val) VALUES (899);
INSERT INTO number__tbl (number_val) VALUES (900);
INSERT INTO number__tbl (number_val) VALUES (901);
INSERT INTO number__tbl (number_val) VALUES (902);
INSERT INTO number__tbl (number_val) VALUES (903);
INSERT INTO number__tbl (number_val) VALUES (904);
INSERT INTO number__tbl (number_val) VALUES (905);
INSERT INTO number__tbl (number_val) VALUES (906);
INSERT INTO number__tbl (number_val) VALUES (907);
INSERT INTO number__tbl (number_val) VALUES (908);
INSERT INTO number__tbl (number_val) VALUES (909);
INSERT INTO number__tbl (number_val) VALUES (910);
INSERT INTO number__tbl (number_val) VALUES (911);
INSERT INTO number__tbl (number_val) VALUES (912);
INSERT INTO number__tbl (number_val) VALUES (913);
INSERT INTO number__tbl (number_val) VALUES (914);
INSERT INTO number__tbl (number_val) VALUES (915);
INSERT INTO number__tbl (number_val) VALUES (916);
INSERT INTO number__tbl (number_val) VALUES (917);
INSERT INTO number__tbl (number_val) VALUES (918);
INSERT INTO number__tbl (number_val) VALUES (919);
INSERT INTO number__tbl (number_val) VALUES (920);
INSERT INTO number__tbl (number_val) VALUES (921);
INSERT INTO number__tbl (number_val) VALUES (922);
INSERT INTO number__tbl (number_val) VALUES (923);
INSERT INTO number__tbl (number_val) VALUES (924);
INSERT INTO number__tbl (number_val) VALUES (925);
INSERT INTO number__tbl (number_val) VALUES (926);
INSERT INTO number__tbl (number_val) VALUES (927);
INSERT INTO number__tbl (number_val) VALUES (928);
INSERT INTO number__tbl (number_val) VALUES (929);
INSERT INTO number__tbl (number_val) VALUES (930);
INSERT INTO number__tbl (number_val) VALUES (931);
INSERT INTO number__tbl (number_val) VALUES (932);
INSERT INTO number__tbl (number_val) VALUES (933);
INSERT INTO number__tbl (number_val) VALUES (934);
INSERT INTO number__tbl (number_val) VALUES (935);
INSERT INTO number__tbl (number_val) VALUES (936);
INSERT INTO number__tbl (number_val) VALUES (937);
INSERT INTO number__tbl (number_val) VALUES (938);
INSERT INTO number__tbl (number_val) VALUES (939);
INSERT INTO number__tbl (number_val) VALUES (940);
INSERT INTO number__tbl (number_val) VALUES (941);
INSERT INTO number__tbl (number_val) VALUES (942);
INSERT INTO number__tbl (number_val) VALUES (943);
INSERT INTO number__tbl (number_val) VALUES (944);
INSERT INTO number__tbl (number_val) VALUES (945);
INSERT INTO number__tbl (number_val) VALUES (946);
INSERT INTO number__tbl (number_val) VALUES (947);
INSERT INTO number__tbl (number_val) VALUES (948);
INSERT INTO number__tbl (number_val) VALUES (949);
INSERT INTO number__tbl (number_val) VALUES (950);
INSERT INTO number__tbl (number_val) VALUES (951);
INSERT INTO number__tbl (number_val) VALUES (952);
INSERT INTO number__tbl (number_val) VALUES (953);
INSERT INTO number__tbl (number_val) VALUES (954);
INSERT INTO number__tbl (number_val) VALUES (955);
INSERT INTO number__tbl (number_val) VALUES (956);
INSERT INTO number__tbl (number_val) VALUES (957);
INSERT INTO number__tbl (number_val) VALUES (958);
INSERT INTO number__tbl (number_val) VALUES (959);
INSERT INTO number__tbl (number_val) VALUES (960);
INSERT INTO number__tbl (number_val) VALUES (961);
INSERT INTO number__tbl (number_val) VALUES (962);
INSERT INTO number__tbl (number_val) VALUES (963);
INSERT INTO number__tbl (number_val) VALUES (964);
INSERT INTO number__tbl (number_val) VALUES (965);
INSERT INTO number__tbl (number_val) VALUES (966);
INSERT INTO number__tbl (number_val) VALUES (967);
INSERT INTO number__tbl (number_val) VALUES (968);
INSERT INTO number__tbl (number_val) VALUES (969);
INSERT INTO number__tbl (number_val) VALUES (970);
INSERT INTO number__tbl (number_val) VALUES (971);
INSERT INTO number__tbl (number_val) VALUES (972);
INSERT INTO number__tbl (number_val) VALUES (973);
INSERT INTO number__tbl (number_val) VALUES (974);
INSERT INTO number__tbl (number_val) VALUES (975);
INSERT INTO number__tbl (number_val) VALUES (976);
INSERT INTO number__tbl (number_val) VALUES (977);
INSERT INTO number__tbl (number_val) VALUES (978);
INSERT INTO number__tbl (number_val) VALUES (979);
INSERT INTO number__tbl (number_val) VALUES (980);
INSERT INTO number__tbl (number_val) VALUES (981);
INSERT INTO number__tbl (number_val) VALUES (982);
INSERT INTO number__tbl (number_val) VALUES (983);
INSERT INTO number__tbl (number_val) VALUES (984);
INSERT INTO number__tbl (number_val) VALUES (985);
INSERT INTO number__tbl (number_val) VALUES (986);
INSERT INTO number__tbl (number_val) VALUES (987);
INSERT INTO number__tbl (number_val) VALUES (988);
INSERT INTO number__tbl (number_val) VALUES (989);
INSERT INTO number__tbl (number_val) VALUES (990);
INSERT INTO number__tbl (number_val) VALUES (991);
INSERT INTO number__tbl (number_val) VALUES (992);
INSERT INTO number__tbl (number_val) VALUES (993);
INSERT INTO number__tbl (number_val) VALUES (994);
INSERT INTO number__tbl (number_val) VALUES (995);
INSERT INTO number__tbl (number_val) VALUES (996);
INSERT INTO number__tbl (number_val) VALUES (997);
INSERT INTO number__tbl (number_val) VALUES (998);
INSERT INTO number__tbl (number_val) VALUES (999);



INSERT INTO sys_func (sys_func_seq, sys_func_sts, sys_func_name, sys_func_desc, sys_func_snotes, sys_func_code, sys_func_attrib) VALUES (1, 'ACTIVE', 'DEFAULT', 'Default', NULL, NULL, NULL);



INSERT INTO sys_role (sys_role_seq, sys_role_sts, sys_role_name, sys_role_desc, sys_role_snotes, sys_role_code, sys_role_attrib) VALUES (0, 'ACTIVE', '*', 'All Users', NULL, NULL, NULL);
INSERT INTO sys_role (sys_role_seq, sys_role_sts, sys_role_name, sys_role_desc, sys_role_snotes, sys_role_code, sys_role_attrib) VALUES (97, 'ACTIVE', 'DADMIN', 'Data Administration', NULL, NULL, NULL);
INSERT INTO sys_role (sys_role_seq, sys_role_sts, sys_role_name, sys_role_desc, sys_role_snotes, sys_role_code, sys_role_attrib) VALUES (98, 'ACTIVE', 'SYSADMIN', 'System Administration', NULL, NULL, NULL);
INSERT INTO sys_role (sys_role_seq, sys_role_sts, sys_role_name, sys_role_desc, sys_role_snotes, sys_role_code, sys_role_attrib) VALUES (99, 'ACTIVE', 'DEV', 'System Developer', NULL, NULL, NULL);
INSERT INTO sys_role (sys_role_seq, sys_role_sts, sys_role_name, sys_role_desc, sys_role_snotes, sys_role_code, sys_role_attrib) VALUES (91, 'ACTIVE', 'X_B', 'General Browse', NULL, NULL, NULL);
INSERT INTO sys_role (sys_role_seq, sys_role_sts, sys_role_name, sys_role_desc, sys_role_snotes, sys_role_code, sys_role_attrib) VALUES (92, 'ACTIVE', 'X_X', 'General BIUD', NULL, NULL, NULL);


INSERT INTO sys_menu_role (menu_id, sys_menu_role_snotes, sys_role_name) VALUES (3, NULL, '*');
INSERT INTO sys_menu_role (menu_id, sys_menu_role_snotes, sys_role_name) VALUES (700, NULL, 'SYSADMIN');
INSERT INTO sys_menu_role (menu_id, sys_menu_role_snotes, sys_role_name) VALUES (800, NULL, 'SYSADMIN');
INSERT INTO sys_menu_role (menu_id, sys_menu_role_snotes, sys_role_name) VALUES (800, NULL, 'DEV');
INSERT INTO sys_menu_role (menu_id, sys_menu_role_snotes, sys_role_name) VALUES (900, NULL, 'DEV');


INSERT INTO code_txt_type (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (1, 'TEXT', 'Text', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code_txt_type (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (2, 'HTML', 'HTML', NULL, NULL, NULL, NULL, NULL, NULL);



INSERT INTO txt__tbl (txt_process, txt_attrib, txt_type, txt_title, txt_body, txt_bcc, txt_desc) VALUES ('EMAIL', 'RESETPASS', 'HTML', 'Password Reset', '<p>Dear <%-data.SYS_USER_NAME%>,<br />
<br />
A password reset has been requested on your account. If you did not initiate the request, please contact us at <%-data.SUPPORT_EMAIL%> immediately.<br />
<br />
Please follow the link below to reset your password:<br />
<a href="<%-data.RESET_LINK%>"><%-data.RESET_LINK%></a></p>
', NULL, '<%-data.SYS_USER_NAME%> User Name
<%-data.SUPPORT_EMAIL%> Support Email
<%-data.RESET_LINK%> Reset Link');
INSERT INTO txt__tbl (txt_process, txt_attrib, txt_type, txt_title, txt_body, txt_bcc, txt_desc) VALUES ('CMS', 'Dashboard__model', 'HTML', 'Dashboard Message of the Day', '<p>Welcome to the jsHarmony System</p>
', NULL, 'Dashboard Message of the Day');
INSERT INTO txt__tbl (txt_process, txt_attrib, txt_type, txt_title, txt_body, txt_bcc, txt_desc) VALUES ('EMAIL', 'SUGGEST_FEATURE', 'HTML', 'Suggest a Feature Email', '<p><%-data.SYS_USER_NAME%> Suggests:</p>

<p style="margin-left:40px"><%-data.MESSAGE_TEXT%></p>

<p>While using: <a href="<%-data.URL%>"><%-data.URL%></a></p>
', NULL, '<%-data.SYS_USER_NAME%> User Email
<%-data.MESSAGE_TEXT%> Message
<%-data.URL%> User Current Page');


INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'CANADA', 'AB', 'Alberta', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'CANADA', 'BC', 'British Columbia', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'CANADA', 'MB', 'Manitoba', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'CANADA', 'NB', 'New Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'CANADA', 'NL', 'Newfoundland and Labrador', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'CANADA', 'NS', 'Nova Scotia', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'CANADA', 'NT', 'Northwest Territories', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'CANADA', 'NU', 'Nunavut', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'CANADA', 'ON', 'Ontario', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'CANADA', 'PE', 'Prince Edward Island', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'CANADA', 'QC', 'Quebec', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'CANADA', 'SK', 'Saskatchewan', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'CANADA', 'YT', 'Yukon', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'AG', 'Aguascalientes', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'BN', 'Baja California', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'BS', 'Baja California Sur', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'CA', 'Coahuila', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'CH', 'Chihuahua', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'CL', 'Colima', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'CM', 'Compeche', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'CP', 'Chiapas', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'DF', 'Federal District', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'DU', 'Durango', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'GR', 'Guerrero', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'GT', 'Guanajuato', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'HI', 'Hidalgo', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'JA', 'Jalisco', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'MC', 'Michoacan', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'MR', 'Morelos', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'MX', 'Mexico', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'NA', 'Nayarit', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'NL', 'Nuevo Leon', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'OA', 'Oaxaca', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'PU', 'Puebla', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'QE', 'Queretaro', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'QR', 'Quintana Roo', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'SI', 'Sinaloa', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'SL', 'San Luis Potosí', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'SO', 'Sonora', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'TB', 'Tabasco', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'TL', 'Tlaxcala', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'TM', 'Tamaulipas', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'VE', 'Veracruz', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'YU', 'Yucatán', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'ZA', 'Zacatecas', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'AK', 'Alaska', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'AL', 'Alabama', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'AR', 'Arkansas', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'AS', 'American Samoa', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'AZ', 'Arizona', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'CA', 'California', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'CO', 'Colorado', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'CT', 'Connecticut', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'DC', 'District of Columbia', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'DE', 'Delaware', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'FL', 'Florida', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'FM', 'Federated States of Micronesia', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'GA', 'Georgia', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'GU', 'Guam', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'HI', 'Hawaii', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'IA', 'Iowa', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'ID', 'Idaho', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'IL', 'Illinois', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'IN', 'Indiana', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'KS', 'Kansas', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'KY', 'Kentucky', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'LA', 'Louisiana', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'MA', 'Massachusetts', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'MD', 'Maryland', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'ME', 'Maine', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'MH', 'Marshall Islands', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'MI', 'Michigan', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'MN', 'Minnesota', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'MO', 'Missouri', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'MP', 'Northern Mariana Islands', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'MS', 'Mississippi', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'MT', 'Montana', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'NC', 'North Carolina', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'ND', 'North Dakota', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'NE', 'Nebraska', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'NH', 'New Hampshire', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'NJ', 'New Jersey', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'NM', 'New Mexico', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'NV', 'Nevada', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'NY', 'New York', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'OH', 'Ohio', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'OK', 'Oklahoma', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'OR', 'Oregon', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'PA', 'Pennsylvania', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'PR', 'Puerto Rico', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'PW', 'Palau', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'RI', 'Rhode Island', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'SC', 'South Carolina', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'SD', 'South Dakota', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'TN', 'Tennessee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'TX', 'Texas', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'UT', 'Utah', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'VA', 'Virginia', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'VI', 'Virgin Islands', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'VT', 'Vermont', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'WA', 'Washington', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'WI', 'Wisconsin', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'WV', 'West Virginia', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code2_country_state (code_seq, code_val1, code_val2, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'WY', 'Wyoming', NULL, NULL, NULL, NULL, NULL, NULL);



INSERT INTO code2_sys (code_name, code_desc, code_code_desc, code_snotes, code_attrib_desc, code_schema, code_type) VALUES ('country_state', 'Country - States', NULL, NULL, NULL, '{schema}', 'sys');




INSERT INTO code_ac (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (1, 'ACTIVE', 'Active', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code_ac (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (2, 'CLOSED', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL);



INSERT INTO code_ac1 (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (1, 'A', 'Active', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code_ac1 (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (2, 'C', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL);



INSERT INTO code_country (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'CANADA', 'CANADA', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code_country (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MEXICO', 'MEXICO', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code_country (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'USA', 'USA', NULL, NULL, NULL, NULL, NULL, NULL);



INSERT INTO code_doc_scope (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (1, 'S', 'System', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code_doc_scope (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (3, 'sys_user_code', 'User', 'sys_user', NULL, NULL, NULL, NULL, NULL);



INSERT INTO code_sys (code_name, code_desc, code_code_desc, code_snotes, code_attrib_desc, code_schema, code_type) VALUES ('ac', 'ACTIVE-CLOSED', NULL, NULL, NULL, '{schema}', 'sys');
INSERT INTO code_sys (code_name, code_desc, code_code_desc, code_snotes, code_attrib_desc, code_schema, code_type) VALUES ('ac1', 'ACTIVE-CLOSED 1 Character', NULL, NULL, NULL, '{schema}', 'sys');
INSERT INTO code_sys (code_name, code_desc, code_code_desc, code_snotes, code_attrib_desc, code_schema, code_type) VALUES ('ahc', 'ACTIVE-HOLD-CLOSED', NULL, NULL, NULL, '{schema}', 'sys');
INSERT INTO code_sys (code_name, code_desc, code_code_desc, code_snotes, code_attrib_desc, code_schema, code_type) VALUES ('country', 'Country', NULL, NULL, NULL, '{schema}', 'sys');
INSERT INTO code_sys (code_name, code_desc, code_code_desc, code_snotes, code_attrib_desc, code_schema, code_type) VALUES ('doc_scope', 'Document Scope', 'Client User Y/N', NULL, NULL, '{schema}', 'sys');
INSERT INTO code_sys (code_name, code_desc, code_code_desc, code_snotes, code_attrib_desc, code_schema, code_type) VALUES ('note_scope', 'Note Scope', NULL, NULL, NULL, '{schema}', 'sys');
INSERT INTO code_sys (code_name, code_desc, code_code_desc, code_snotes, code_attrib_desc, code_schema, code_type) VALUES ('note_type', 'Note Type', NULL, NULL, NULL, '{schema}', 'sys');
INSERT INTO code_sys (code_name, code_desc, code_code_desc, code_snotes, code_attrib_desc, code_schema, code_type) VALUES ('param_type', 'Parameter Type', NULL, NULL, NULL, '{schema}', 'sys');
INSERT INTO code_sys (code_name, code_desc, code_code_desc, code_snotes, code_attrib_desc, code_schema, code_type) VALUES ('job_action', 'Job Action Type', NULL, NULL, NULL, '{schema}', 'sys');
INSERT INTO code_sys (code_name, code_desc, code_code_desc, code_snotes, code_attrib_desc, code_schema, code_type) VALUES ('job_source', 'Job Source', NULL, NULL, NULL, '{schema}', 'sys');
INSERT INTO code_sys (code_name, code_desc, code_code_desc, code_snotes, code_attrib_desc, code_schema, code_type) VALUES ('txt_type', 'Text Type', NULL, NULL, NULL, '{schema}', 'sys');
INSERT INTO code_sys (code_name, code_desc, code_code_desc, code_snotes, code_attrib_desc, code_schema, code_type) VALUES ('version_sts', 'Version Status', NULL, NULL, NULL, '{schema}', 'sys');



INSERT INTO code_note_scope (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (1, 'S', 'System', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code_note_scope (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (3, 'sys_user_code', 'User', 'sys_user', NULL, NULL, NULL, NULL, NULL);



INSERT INTO code_note_type (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (1, 'U', 'User', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code_note_type (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (2, 'C', 'Client', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code_note_type (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (3, 'S', 'System', NULL, NULL, NULL, NULL, NULL, NULL);



INSERT INTO code_job_action (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MESSAGE', 'Message', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code_job_action (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'REPORT', 'Report Program', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code_job_action (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'TASK', 'jsHarmony Task', NULL, NULL, NULL, NULL, NULL, NULL);



INSERT INTO code_job_source (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'MAIN', 'Main Interface', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code_job_source (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (NULL, 'CLIENT', 'Client Interface', NULL, NULL, NULL, NULL, NULL, NULL);



INSERT INTO code_version_sts (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (1, 'OK', 'OK', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO code_version_sts (code_seq, code_val, code_txt, code_code, code_end_dt, code_end_reason, code_snotes, code_notes, code_attrib) VALUES (2, 'ERROR', 'Error', NULL, NULL, NULL, NULL, NULL, NULL);




INSERT INTO param_sys (param_sys_process, param_sys_attrib, param_sys_val) VALUES ('USERS', 'HASH_SEED_S', 'NOT CONFIGURED');
INSERT INTO param_sys (param_sys_process, param_sys_attrib, param_sys_val) VALUES ('SQL', 'doc_ctgr_table', 'code2_doc_scope_doc_ctgr');
INSERT INTO param_sys (param_sys_process, param_sys_attrib, param_sys_val) VALUES ('SYSTEM', 'CLIENT_SYS_URL', 'https://localhost');
INSERT INTO param_sys (param_sys_process, param_sys_attrib, param_sys_val) VALUES ('EMAIL', 'NOTIF_SYS', 'user@company.com');
