INSERT INTO {{schema}}_dual (dummy, dual_ident, dual_integer, dual_text) VALUES ('X', 1, NULL, NULL);

insert into {{schema}}_ucod_ac (codseq, codeval, codetxt, codecode, codeattrib) VALUES (1, 'ACTIVE', 'Active', NULL, NULL);
insert into {{schema}}_ucod_ac (codseq, codeval, codetxt, codecode, codeattrib) VALUES (3, 'CLOSED', 'Closed', NULL, NULL);

insert into {{schema}}_ucod_ac1 (codseq, codeval, codetxt, codecode, codeattrib) VALUES (1, 'A', 'Active', NULL, NULL);
insert into {{schema}}_ucod_ac1 (codseq, codeval, codetxt, codecode, codeattrib) VALUES (2, 'C', 'Closed', NULL, NULL);

insert into {{schema}}_ucod_ahc (codseq, codeval, codetxt, codecode, codeattrib) VALUES (1, 'ACTIVE', 'Active', NULL, NULL);
insert into {{schema}}_ucod_ahc (codseq, codeval, codetxt, codecode, codeattrib) VALUES (3, 'CLOSED', 'Closed', NULL, NULL);
insert into {{schema}}_ucod_ahc (codseq, codeval, codetxt, codecode, codeattrib) VALUES (2, 'HOLD', 'Hold', NULL, NULL);

insert into {{schema}}_ucod_country(codseq,codeval,codetxt,codecode,codeattrib) values (NULL,'USA','United States',NULL,NULL);
insert into {{schema}}_ucod_country(codseq,codeval,codetxt,codecode,codeattrib) values (NULL,'CANADA','Canada',NULL,NULL);
insert into {{schema}}_ucod_country(codseq,codeval,codetxt,codecode,codeattrib) values (NULL,'MEXICO','Mexico',NULL,NULL);

insert into {{schema}}_ucod_d_scope (codseq, codeval, codetxt, codecode, codeattrib) VALUES (2, 'C', 'Customer', NULL, NULL);
insert into {{schema}}_ucod_d_scope (codseq, codeval, codetxt, codecode, codeattrib) VALUES (1, 'S', 'System', NULL, NULL);
insert into {{schema}}_ucod_d_scope (codseq, codeval, codetxt, codecode, codeattrib) VALUES (3, 'O', 'Order', NULL, NULL);
insert into {{schema}}_ucod_d_scope (codseq, codeval, codetxt, codecode, codeattrib) VALUES (4, 'VEN', 'Vendor', NULL, NULL);
insert into {{schema}}_ucod_d_scope (codseq, codeval, codetxt, codecode, codeattrib) VALUES (5, 'PE', 'User', NULL, NULL);

insert into {{schema}}_ucod_n_scope (codseq, codeval, codetxt, codecode, codeattrib) VALUES (2, 'C', 'Customer', NULL, NULL);
insert into {{schema}}_ucod_n_scope (codseq, codeval, codetxt, codecode, codeattrib) VALUES (1, 'S', 'System', NULL, NULL);
insert into {{schema}}_ucod_n_scope (codseq, codeval, codetxt, codecode, codeattrib) VALUES (3, 'CT', 'Cust Contact', NULL, NULL);
insert into {{schema}}_ucod_n_scope (codseq, codeval, codetxt, codecode, codeattrib) VALUES (4, 'VEN', 'Vendor', NULL, NULL);
insert into {{schema}}_ucod_n_scope (codseq, codeval, codetxt, codecode, codeattrib) VALUES (5, 'PE', 'User', NULL, NULL);

insert into {{schema}}_ucod_n_type (codseq, codeval, codetxt, codecode, codeattrib) VALUES (2, 'C', 'Client', NULL, NULL);
insert into {{schema}}_ucod_n_type (codseq, codeval, codetxt, codecode, codeattrib) VALUES (3, 'S', 'System', NULL, NULL);
insert into {{schema}}_ucod_n_type (codseq, codeval, codetxt, codecode, codeattrib) VALUES (1, 'U', 'User', NULL, NULL);

insert into {{schema}}_ucod_ppd_type (codseq, codeval, codetxt, codecode, codeattrib) VALUES (NULL, 'C', 'Character', NULL, NULL);
insert into {{schema}}_ucod_ppd_type (codseq, codeval, codetxt, codecode, codeattrib) VALUES (NULL, 'N', 'Number', NULL, NULL);

insert into {{schema}}_ucod_rqst_atype (codseq, codeval, codetxt, codecode, codeattrib) VALUES (NULL, 'MESSAGE', 'Message', NULL, NULL);
insert into {{schema}}_ucod_rqst_atype (codseq, codeval, codetxt, codecode, codeattrib) VALUES (NULL, 'REPORT', 'Report Program', NULL, NULL);

insert into {{schema}}_ucod_rqst_source (codseq, codeval, codetxt, codecode, codeattrib) VALUES (NULL, 'MAIN', 'Main Interface', NULL, NULL);
insert into {{schema}}_ucod_rqst_source (codseq, codeval, codetxt, codecode, codeattrib) VALUES (NULL, 'CLIENT', 'Client Interface', NULL, NULL);

insert into {{schema}}_ucod_txt_type (codseq, codeval, codetxt, codecode, codeattrib) VALUES (2, 'HTML', 'HTML', NULL, NULL);
insert into {{schema}}_ucod_txt_type (codseq, codeval, codetxt, codecode, codeattrib) VALUES (1, 'TEXT', 'Text', NULL, NULL);

insert into {{schema}}_ucod_v_sts (codseq, codeval, codetxt, codecode, codeattrib) VALUES (2, 'ERROR', 'Error', NULL, NULL);
insert into {{schema}}_ucod_v_sts (codseq, codeval, codetxt, codecode, codeattrib) VALUES (1, 'OK', 'OK', NULL, NULL);

insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('CANADA','AB','Alberta');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('CANADA','BC','British Columbia');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('CANADA','MB','Manitoba');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('CANADA','NB','New Brunswick');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('CANADA','NL','Newfoundland and Labrador');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('CANADA','NS','Nova Scotia');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('CANADA','NT','Northwest Territories');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('CANADA','NU','Nunavut');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('CANADA','ON','Ontario');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('CANADA','PE','Prince Edward Island');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('CANADA','QC','Quebec');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('CANADA','SK','Saskatchewan');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('CANADA','YT','Yukon');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','AG','Aguascalientes');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','BN','Baja California');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','BS','Baja California Sur');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','CA','Coahuila');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','CH','Chihuahua');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','CL','Colima');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','CM','Compeche');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','CP','Chiapas');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','DF','Federal District');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','DU','Durango');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','GR','Guerrero');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','GT','Guanajuato');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','HI','Hidalgo');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','JA','Jalisco');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','MC','Michoacan');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','MR','Morelos');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','MX','Mexico');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','NA','Nayarit');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','NL','Nuevo Leon');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','OA','Oaxaca');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','PU','Puebla');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','QE','Queretaro');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','QR','Quintana Roo');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','SI','Sinaloa');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','SL','San Luis Potos�');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','SO','Sonora');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','TB','Tabasco');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','TL','Tlaxcala');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','TM','Tamaulipas');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','VE','Veracruz');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','YU','Yucat�n');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('MEXICO','ZA','Zacatecas');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','AK','Alaska');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','AL','Alabama');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','AR','Arkansas');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','AS','American Samoa');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','AZ','Arizona');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','CA','California');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','CO','Colorado');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','CT','Connecticut');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','DC','District of Columbia');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','DE','Delaware');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','FL','Florida');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','FM','Federated States of Micronesia');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','GA','Georgia');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','GU','Guam');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','HI','Hawaii');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','IA','Iowa');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','ID','Idaho');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','IL','Illinois');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','IN','Indiana');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','KS','Kansas');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','KY','Kentucky');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','LA','Louisiana');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','MA','Massachusetts');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','MD','Maryland');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','ME','Maine');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','MH','Marshall Islands');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','MI','Michigan');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','MN','Minnesota');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','MO','Missouri');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','MP','Northern Mariana Islands');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','MS','Mississippi');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','MT','Montana');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','NC','North Carolina');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','ND','North Dakota');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','NE','Nebraska');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','NH','New Hampshire');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','NJ','New Jersey');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','NM','New Mexico');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','NV','Nevada');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','NY','New York');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','OH','Ohio');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','OK','Oklahoma');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','OR','Oregon');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','PA','Pennsylvania');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','PR','Puerto Rico');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','PW','Palau');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','RI','Rhode Island');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','SC','South Carolina');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','SD','South Dakota');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','TN','Tennessee');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','TX','Texas');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','UT','Utah');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','VA','Virginia');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','VI','Virgin Islands');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','VT','Vermont');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','WA','Washington');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','WI','Wisconsin');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','WV','West Virginia');
insert into {{schema}}_ucod2_country_state(codeval1,codeval2,codetxt) values ('USA','WY','Wyoming');

INSERT INTO {{schema}}_cr (cr_seq, cr_sts, cr_name, cr_desc, cr_code, cr_attrib) VALUES (1, 'ACTIVE', 'CSYSADMIN', 'Administrator', NULL,NULL);
INSERT INTO {{schema}}_cr (cr_seq, cr_sts, cr_name, cr_desc, cr_code, cr_attrib) VALUES (2, 'ACTIVE', 'CX_B', 'Browse', NULL, NULL);
INSERT INTO {{schema}}_cr (cr_seq, cr_sts, cr_name, cr_desc, cr_code, cr_attrib) VALUES (3, 'ACTIVE', 'CX_X', 'Entry / Update', NULL, NULL);
INSERT INTO {{schema}}_cr (cr_seq, cr_sts, cr_name, cr_desc, cr_code, cr_attrib) VALUES (1, 'ACTIVE', 'CUSER', 'Client User', NULL, NULL);
INSERT INTO {{schema}}_cr (cr_seq, cr_sts, cr_name, cr_desc, cr_code, cr_attrib) VALUES (0, 'ACTIVE', 'C*', 'All Users', NULL, NULL);

INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('EMAIL', 'NOTIF_ADMIN', 'Notifications Email - Administrative', 'C', NULL,  1, 0, 0);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('USERS', 'HASH_SEED_S', 'Hash Seed System Users', 'C', NULL,  0, 0, 1);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('HOUSE', 'ADDR', 'HOUSE Address', 'C', NULL,  1, 0, 0);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('HOUSE', 'BPHONE', 'HOUSE Business Phone', 'C', NULL,  1, 0, 0);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('HOUSE', 'CITY', 'HOUSE City', 'C', NULL,  1, 0, 0);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('HOUSE', 'CONTACT', 'HOUSE Contact', 'C', NULL,  1, 0, 0);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('HOUSE', 'EMAIL', 'HOUSE Email', 'C', NULL,  1, 0, 0);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('HOUSE', 'FAX', 'HOUSE Fax', 'C', NULL,  1, 0, 0);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('SQL', 'DSCOPE_DCTGR', 'Code table - Document Types by Scope', 'C', NULL,  0, 0, 1);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('SQL', 'GETCID', 'SQL Function GET_C_ID', 'C', NULL,  0, 0, 1);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('SQL', 'GETEID', 'SQL Function GET_E_ID', 'C', NULL,  0, 0, 1);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('HOUSE', 'ZIP', 'HOUSE ZIP', 'C', NULL,  1, 0, 0);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('HOUSE', 'STATE', 'HOUSE State', 'C', NULL,  1, 0, 0);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('HOUSE', 'NAME', 'HOUSE Name', 'C', NULL,  1, 0, 0);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('DEVICEURL', 'PRINTBAR', 'Device URL - Bar Code Printer', 'C', NULL,  1, 1, 0);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('DEVICEURL', 'SCAN', 'Device URL - Document Scanner', 'C', NULL,  1, 1, 0);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('EMAIL', 'NOTIF_SYS', 'Notifications Email - System', 'C', NULL,  1, 0, 1);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('SYSTEM', 'CLIENT_SYS_URL', 'Client Portal URL', 'C', NULL,  0, 0, 1);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('SYSTEM', 'SYS_URL', 'System URL', 'C', NULL,  0, 0, 1);
INSERT INTO {{schema}}_ppd (ppd_process, ppd_attrib, ppd_desc, ppd_type, codename, ppd_gpp, ppd_ppp, ppd_xpp) VALUES ('USERS', 'HASH_SEED_C', 'Hash Seed Client Users', 'C', NULL,  0, 0, 1);

INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 1, 'ACTIVE', NULL, 'MAIN', NULL, 'Main System', NULL, NULL, NULL, NULL, NULL);

INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 3, 'ACTIVE', 1, 'DASHBOARD', 1, 'Dashboard', NULL, NULL, '%%%NAMESPACE%%%DASHBOARD', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 700, 'ACTIVE', 1, 'REPORTS', 70000, 'Reports', NULL, NULL, '%%%NAMESPACE%%%REPORTS', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 800, 'ACTIVE', 1, 'ADMINISTRATION', 80000, 'Administration', NULL, NULL, '%%%NAMESPACE%%%ADMIN_OVERVIEW', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 900, 'ACTIVE', 1, 'DEV', 90000, 'Developer', NULL, NULL, '%%%NAMESPACE%%%DEV_OVERVIEW', NULL, NULL);

INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 70801, 'ACTIVE', 700, 'REPORTS_USERS', NULL, 'User Listing', NULL, NULL, '%%%NAMESPACE%%%reports/RPE', NULL, NULL);

INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 80000, 'ACTIVE', 800, 'ADMINISTRATION_USERS', NULL, 'System Users', NULL, NULL, '%%%NAMESPACE%%%PEL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 80081, 'ACTIVE', 800, 'ADMINISTRATION_PPARAMETERS', NULL, 'User Settings', NULL, NULL, '%%%NAMESPACE%%%PPPL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 80082, 'ACTIVE', 800, 'ADMINISTRATION_GPARAMETERS', NULL, 'System Settings', NULL, NULL, '%%%NAMESPACE%%%GPPL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 80083, 'ACTIVE', 800, 'ADMINISTRATION_CODETABLES', NULL, '1D Code Tables', NULL, NULL, '%%%NAMESPACE%%%GCOD_HL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 80084, 'ACTIVE', 800, 'ADMINISTRATION_CODE2TABLES', NULL, '2D Code Tables', NULL, NULL, '%%%NAMESPACE%%%GCOD2_HL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 80085, 'ACTIVE', 800, 'ADMINISTRATION_TEXTMAINTENANCE', NULL, 'Text Maint', NULL, NULL, '%%%NAMESPACE%%%TXTL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 80086, 'ACTIVE', 800, 'ADMINISTRATION_HELPMAINTENANCE', NULL, 'Help Maint', NULL, NULL, '%%%NAMESPACE%%%HL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 80087, 'ACTIVE', 800, 'ADMINISTRATION_AUDITTRAIL', NULL, 'Audit Trail', NULL, NULL, '%%%NAMESPACE%%%AUDL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 80095, 'ACTIVE', 800, 'ADMINISTRATION_LOG', NULL, 'Logs', NULL, NULL, '%%%NAMESPACE%%%LOG', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 80096, 'ACTIVE', 800, 'ADMINISTRATION_RESTART_SYSTEM', NULL, 'Restart System', NULL, NULL, '%%%NAMESPACE%%%RESTART_SYSTEM', NULL, NULL);

INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 90012, 'ACTIVE', 900, 'DEV_X_SML', 90011, 'Menu Items', NULL, NULL, '%%%NAMESPACE%%%X_SMLW', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 90011, 'ACTIVE', 900, 'DEV_X_SRL', 90012, 'User Roles', NULL, NULL, '%%%NAMESPACE%%%X_SRL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 90020, 'ACTIVE', 900, 'DEV_X_CRL', 90013, 'Client User Roles', NULL, NULL, '%%%NAMESPACE%%%X_CRL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 90013, 'ACTIVE', 900, 'DEV_X_PPDL', 90021, 'Settings Definitions', NULL, NULL, '%%%NAMESPACE%%%X_PPDL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 90014, 'ACTIVE', 900, 'DEV_X_GPPL', 90022, 'System Settings', NULL, NULL, '%%%NAMESPACE%%%X_GPPL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 90015, 'ACTIVE', 900, 'DEV_X_XPPL', 90023, 'Developer Settings', NULL, NULL, '%%%NAMESPACE%%%X_XPPL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 90016, 'ACTIVE', 900, 'DEV_X_GCOD_HL', 90031, 'Admin 1D Codes', NULL, NULL, '%%%NAMESPACE%%%X_GCOD_HL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 90017, 'ACTIVE', 900, 'DEV_X_GCOD2_HL', 90032, 'Admin 2D Codes', NULL, NULL, '%%%NAMESPACE%%%X_GCOD2_HL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 90018, 'ACTIVE', 900, 'DEV_X_UCOD_HL', 90033, 'System 1D Codes', NULL, NULL, '%%%NAMESPACE%%%X_UCOD_HL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 90019, 'ACTIVE', 900, 'DEV_X_UCOD2_HL', 90034, 'System 2D Codes', NULL, NULL, '%%%NAMESPACE%%%X_UCOD2_HL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 90021, 'ACTIVE', 900, 'DEV_X_TXTL', 90041, 'Text Maint', NULL, NULL, '%%%NAMESPACE%%%X_TXTL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 90022, 'ACTIVE', 900, 'DEV_X_HPL', 90042, 'Help Panels', NULL, NULL, '%%%NAMESPACE%%%X_HPL', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 90023, 'ACTIVE', 900, 'DEV_DB', 90043, 'DB SQL', NULL, NULL, '%%%NAMESPACE%%%DEV_DB', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 90024, 'ACTIVE', 900, 'DEV_DB_SCRIPTS', 90044, 'DB Scripts', NULL, NULL, '%%%NAMESPACE%%%DEV_DB_SCRIPTS', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 90025, 'ACTIVE', 900, 'DEV_DB_SCHEMA', 90045, 'DB Schema', NULL, NULL, '%%%NAMESPACE%%%DEV_DB_SCHEMA', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('S', 90026, 'ACTIVE', 900, 'DEV_MODELS', 90046, 'Model Viewer', NULL, NULL, '%%%NAMESPACE%%%DEV_MODELS', NULL, NULL);

INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('C', 2, 'ACTIVE', NULL, 'CLIENT', NULL, 'Customer', NULL, NULL, NULL, NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('C', 200, 'ACTIVE', 2, 'C_DASHBOARD', NULL, 'Dashboard', NULL, NULL, '%%%NAMESPACE%%%C_DASHBOARD', NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('C', 270, 'ACTIVE', 2, 'C_ADMINISTRATION', NULL, 'Administration', NULL, NULL, NULL, NULL, NULL);
INSERT INTO {{schema}}_sm (sm_utype, sm_id, sm_sts, sm_id_parent, sm_name, sm_seq, sm_desc, sm_descl, sm_descvl, sm_cmd, sm_image, sm_subcmd) VALUES ('C', 2700, 'ACTIVE', 270, 'C_ADMINISTRATION_USERS', NULL, 'Cust Users', NULL, NULL, '%%%NAMESPACE%%%CPEL_CLIENT', NULL, NULL);

INSERT INTO {{schema}}_sr (sr_seq, sr_sts, sr_name, sr_desc, sr_code, sr_attrib) VALUES (0, 'ACTIVE', '*', 'All Users', NULL, NULL);
INSERT INTO {{schema}}_sr (sr_seq, sr_sts, sr_name, sr_desc, sr_code, sr_attrib) VALUES (97, 'ACTIVE', 'DADMIN', 'Data Administration', NULL, NULL);
INSERT INTO {{schema}}_sr (sr_seq, sr_sts, sr_name, sr_desc, sr_code, sr_attrib) VALUES (98, 'ACTIVE', 'SYSADMIN', 'System Administration', NULL, NULL);
INSERT INTO {{schema}}_sr (sr_seq, sr_sts, sr_name, sr_desc, sr_code, sr_attrib) VALUES (99, 'ACTIVE', 'DEV', 'Developer', NULL, NULL);
INSERT INTO {{schema}}_sr (sr_seq, sr_sts, sr_name, sr_desc, sr_code, sr_attrib) VALUES (91, 'ACTIVE', 'X_B', 'General Browse', NULL, NULL);
INSERT INTO {{schema}}_sr (sr_seq, sr_sts, sr_name, sr_desc, sr_code, sr_attrib) VALUES (92, 'ACTIVE', 'X_X', 'General BIUD', NULL, NULL);

INSERT INTO {{schema}}_sf (sf_seq, sf_sts, sf_name, sf_desc, sf_code, sf_attrib) VALUES (1, 'ACTIVE', 'TBD', 'TBD', NULL, NULL);

INSERT INTO {{schema}}_txt (txt_process, txt_attrib, txt_type, txt_tval, txt_val, txt_bcc, txt_desc) VALUES ('EMAIL', 'RESETPASS', 'HTML', 'Password Reset', '<p>Dear <%-data.PE_NAME%>,<br />
<br />
A password reset has been requested on your account. If you did not initiate the request, please contact us at <%-data.SUPPORT_EMAIL%> immediately.<br />
<br />
Please follow the link below to reset your password:<br />
<a href="<%-data.RESET_LINK%>"><%-data.RESET_LINK%></a></p>
', NULL, '<%-data.PE_NAME%> User Name
<%-data.SUPPORT_EMAIL%> Support Email
<%-data.RESET_LINK%> Reset Link');
INSERT INTO {{schema}}_txt (txt_process, txt_attrib, txt_type, txt_tval, txt_val, txt_bcc, txt_desc) VALUES ('CMS', 'AGREEMENT', 'HTML', 'Client Agreement', NULL, NULL, 'Client Agreement');
INSERT INTO {{schema}}_txt (txt_process, txt_attrib, txt_type, txt_tval, txt_val, txt_bcc, txt_desc) VALUES ('CMS', 'AGREEMENT_DONE', 'HTML', 'Client Agreement Complete', '<p>Thank you for completing sign-up.</p>
', NULL, 'Client Agreement Complete');
INSERT INTO {{schema}}_txt (txt_process, txt_attrib, txt_type, txt_tval, txt_val, txt_bcc, txt_desc) VALUES ('SMS', 'WELCOME', 'TEXT', 'Welcome', 'Your account has been initialized.', NULL, 'SMS Welcome Message');
INSERT INTO {{schema}}_txt (txt_process, txt_attrib, txt_type, txt_tval, txt_val, txt_bcc, txt_desc) VALUES ('CMS', 'C_DASHBOARD', 'HTML', 'Client Dashboard Message of the Day', '<p>Welcome to the jsHarmony Client Portal</p>
', NULL, 'Client Dashboard Message of the Day');
INSERT INTO {{schema}}_txt (txt_process, txt_attrib, txt_type, txt_tval, txt_val, txt_bcc, txt_desc) VALUES ('CMS', 'DASHBOARD', 'HTML', 'Dashboard Message of the Day', '<p>Welcome to the jsHarmony System</p>
', NULL, 'Dashboard Message of the Day');

INSERT INTO {{schema}}_crm (sm_id, crm_snotes, cr_name) VALUES (200, NULL, 'CX_B');
INSERT INTO {{schema}}_crm (sm_id, crm_snotes, cr_name) VALUES (270, NULL, 'CSYSADMIN');
INSERT INTO {{schema}}_crm (sm_id, crm_snotes, cr_name) VALUES (2700, NULL, 'CSYSADMIN');
INSERT INTO {{schema}}_crm (sm_id, crm_snotes, cr_name) VALUES (200, NULL, 'CX_X');
INSERT INTO {{schema}}_crm (sm_id, crm_snotes, cr_name) VALUES (200, NULL, 'CUSER');

INSERT INTO {{schema}}_gcod2_h (codename, codemean, codecodemean, codeattribmean, codeschema) VALUES ('d_scope_d_ctgr', 'Scope - Documents', NULL, NULL, '{{schema}}');

INSERT INTO {{schema}}_gpp (gpp_process, gpp_attrib, gpp_val) VALUES ('HOUSE', 'STATE', 'IL');
INSERT INTO {{schema}}_gpp (gpp_process, gpp_attrib, gpp_val) VALUES ('HOUSE', 'CITY', 'Anytown');
INSERT INTO {{schema}}_gpp (gpp_process, gpp_attrib, gpp_val) VALUES ('HOUSE', 'CONTACT', 'John Contact');
INSERT INTO {{schema}}_gpp (gpp_process, gpp_attrib, gpp_val) VALUES ('HOUSE', 'ADDR', '111 Main St');
INSERT INTO {{schema}}_gpp (gpp_process, gpp_attrib, gpp_val) VALUES ('HOUSE', 'BPHONE', '(222) 222-2222');
INSERT INTO {{schema}}_gpp (gpp_process, gpp_attrib, gpp_val) VALUES ('HOUSE', 'EMAIL', 'user@company.com');
INSERT INTO {{schema}}_gpp (gpp_process, gpp_attrib, gpp_val) VALUES ('HOUSE', 'FAX', '(333) 333-3333');
INSERT INTO {{schema}}_gpp (gpp_process, gpp_attrib, gpp_val) VALUES ('HOUSE', 'NAME', 'COMPANY NAME');
INSERT INTO {{schema}}_gpp (gpp_process, gpp_attrib, gpp_val) VALUES ('EMAIL', 'NOTIF_ADMIN', 'user@company.com');
INSERT INTO {{schema}}_gpp (gpp_process, gpp_attrib, gpp_val) VALUES ('HOUSE', 'ZIP', '11111');

INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (2700, 'SYSADMIN');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (900, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (80000, 'SYSADMIN');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (270, 'SYSADMIN');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (200, 'SYSADMIN');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (800, 'SYSADMIN');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (2, 'SYSADMIN');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (90011, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (90012, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (90013, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (90014, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (90015, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (800, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (80000, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (90016, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (90017, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (90018, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (90019, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (90020, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (90021, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (90022, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (90023, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (90024, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (90025, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (90026, 'DEV');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (80086, 'SYSADMIN');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (80095, 'SYSADMIN');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (80096, 'SYSADMIN');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (3, '*');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (80087, 'SYSADMIN');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (80085,  'SYSADMIN');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (80083, 'SYSADMIN');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (80084, 'SYSADMIN');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (80081, 'SYSADMIN');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (80082, 'SYSADMIN');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (70801, 'SYSADMIN');
INSERT INTO {{schema}}_srm (sm_id, sr_name) VALUES (700, 'SYSADMIN');

INSERT INTO {{schema}}_ucod_h (codename, codemean, codecodemean, codeattribmean, codeschema) VALUES ('ac', 'ACTIVE-CLOSED', NULL, NULL, '{{schema}}');
INSERT INTO {{schema}}_ucod_h (codename, codemean, codecodemean, codeattribmean, codeschema) VALUES ('ac1', 'ACTIVE-CLOSED 1 Character', NULL, NULL, '{{schema}}');
INSERT INTO {{schema}}_ucod_h (codename, codemean, codecodemean, codeattribmean, codeschema) VALUES ('ahc', 'ACTIVE-HOLD-CLOSED', NULL, NULL, '{{schema}}');
INSERT INTO {{schema}}_ucod_h (codename, codemean, codecodemean, codeattribmean, codeschema) VALUES ('country', 'Country', NULL, NULL, '{{schema}}');
INSERT INTO {{schema}}_ucod_h (codename, codemean, codecodemean, codeattribmean, codeschema) VALUES ('d_scope', 'Document Scope', 'Client User Y/N', NULL, '{{schema}}');
INSERT INTO {{schema}}_ucod_h (codename, codemean, codecodemean, codeattribmean, codeschema) VALUES ('n_scope', 'Note Scope', NULL, NULL, '{{schema}}');
INSERT INTO {{schema}}_ucod_h (codename, codemean, codecodemean, codeattribmean, codeschema) VALUES ('n_type', 'Note Type', NULL, NULL, '{{schema}}');
INSERT INTO {{schema}}_ucod_h (codename, codemean, codecodemean, codeattribmean, codeschema) VALUES ('ppd_type', 'Parameter Type', NULL, NULL, '{{schema}}');
INSERT INTO {{schema}}_ucod_h (codename, codemean, codecodemean, codeattribmean, codeschema) VALUES ('rqst_atype', 'Request Action Type', NULL, NULL, '{{schema}}');
INSERT INTO {{schema}}_ucod_h (codename, codemean, codecodemean, codeattribmean, codeschema) VALUES ('rqst_source', 'Request Source', NULL, NULL, '{{schema}}');
INSERT INTO {{schema}}_ucod_h (codename, codemean, codecodemean, codeattribmean, codeschema) VALUES ('txt_type', 'Text Type', NULL, NULL, '{{schema}}');
INSERT INTO {{schema}}_ucod_h (codename, codemean, codecodemean, codeattribmean, codeschema) VALUES ('v_sts', 'Version Status', NULL, NULL, '{{schema}}');

INSERT INTO {{schema}}_ucod2_h (codename, codemean, codecodemean, codeattribmean, codeschema) VALUES ('country_state', 'Country - States', NULL, NULL, '{{schema}}');

INSERT INTO {{schema}}_xpp (xpp_process, xpp_attrib, xpp_val) VALUES ('USERS', 'HASH_SEED_C', 'NOT CONFIGURED');
INSERT INTO {{schema}}_xpp (xpp_process, xpp_attrib, xpp_val) VALUES ('USERS', 'HASH_SEED_S', 'NOT CONFIGURED');
INSERT INTO {{schema}}_xpp (xpp_process, xpp_attrib, xpp_val) VALUES ('SQL', 'DSCOPE_DCTGR', 'gcod2_d_scope_d_ctgr');
INSERT INTO {{schema}}_xpp (xpp_process, xpp_attrib, xpp_val) VALUES ('SQL', 'GETCID', 'get_c_id');
INSERT INTO {{schema}}_xpp (xpp_process, xpp_attrib, xpp_val) VALUES ('SQL', 'GETEID', 'get_e_id');
INSERT INTO {{schema}}_xpp (xpp_process, xpp_attrib, xpp_val) VALUES ('SYSTEM', 'CLIENT_SYS_URL', 'https://localhost');
INSERT INTO {{schema}}_xpp (xpp_process, xpp_attrib, xpp_val) VALUES ('EMAIL', 'NOTIF_SYS', 'user@company.com');

INSERT INTO {{schema}}_numbers (n) VALUES (1);
INSERT INTO {{schema}}_numbers (n) VALUES (2);
INSERT INTO {{schema}}_numbers (n) VALUES (3);
INSERT INTO {{schema}}_numbers (n) VALUES (4);
INSERT INTO {{schema}}_numbers (n) VALUES (5);
INSERT INTO {{schema}}_numbers (n) VALUES (6);
INSERT INTO {{schema}}_numbers (n) VALUES (7);
INSERT INTO {{schema}}_numbers (n) VALUES (8);
INSERT INTO {{schema}}_numbers (n) VALUES (9);
INSERT INTO {{schema}}_numbers (n) VALUES (10);
INSERT INTO {{schema}}_numbers (n) VALUES (11);
INSERT INTO {{schema}}_numbers (n) VALUES (12);
INSERT INTO {{schema}}_numbers (n) VALUES (13);
INSERT INTO {{schema}}_numbers (n) VALUES (14);
INSERT INTO {{schema}}_numbers (n) VALUES (15);
INSERT INTO {{schema}}_numbers (n) VALUES (16);
INSERT INTO {{schema}}_numbers (n) VALUES (17);
INSERT INTO {{schema}}_numbers (n) VALUES (18);
INSERT INTO {{schema}}_numbers (n) VALUES (19);
INSERT INTO {{schema}}_numbers (n) VALUES (20);
INSERT INTO {{schema}}_numbers (n) VALUES (21);
INSERT INTO {{schema}}_numbers (n) VALUES (22);
INSERT INTO {{schema}}_numbers (n) VALUES (23);
INSERT INTO {{schema}}_numbers (n) VALUES (24);
INSERT INTO {{schema}}_numbers (n) VALUES (25);
INSERT INTO {{schema}}_numbers (n) VALUES (26);
INSERT INTO {{schema}}_numbers (n) VALUES (27);
INSERT INTO {{schema}}_numbers (n) VALUES (28);
INSERT INTO {{schema}}_numbers (n) VALUES (29);
INSERT INTO {{schema}}_numbers (n) VALUES (30);
INSERT INTO {{schema}}_numbers (n) VALUES (31);
INSERT INTO {{schema}}_numbers (n) VALUES (32);
INSERT INTO {{schema}}_numbers (n) VALUES (33);
INSERT INTO {{schema}}_numbers (n) VALUES (34);
INSERT INTO {{schema}}_numbers (n) VALUES (35);
INSERT INTO {{schema}}_numbers (n) VALUES (36);
INSERT INTO {{schema}}_numbers (n) VALUES (37);
INSERT INTO {{schema}}_numbers (n) VALUES (38);
INSERT INTO {{schema}}_numbers (n) VALUES (39);
INSERT INTO {{schema}}_numbers (n) VALUES (40);
INSERT INTO {{schema}}_numbers (n) VALUES (41);
INSERT INTO {{schema}}_numbers (n) VALUES (42);
INSERT INTO {{schema}}_numbers (n) VALUES (43);
INSERT INTO {{schema}}_numbers (n) VALUES (44);
INSERT INTO {{schema}}_numbers (n) VALUES (45);
INSERT INTO {{schema}}_numbers (n) VALUES (46);
INSERT INTO {{schema}}_numbers (n) VALUES (47);
INSERT INTO {{schema}}_numbers (n) VALUES (48);
INSERT INTO {{schema}}_numbers (n) VALUES (49);
INSERT INTO {{schema}}_numbers (n) VALUES (50);
INSERT INTO {{schema}}_numbers (n) VALUES (51);
INSERT INTO {{schema}}_numbers (n) VALUES (52);
INSERT INTO {{schema}}_numbers (n) VALUES (53);
INSERT INTO {{schema}}_numbers (n) VALUES (54);
INSERT INTO {{schema}}_numbers (n) VALUES (55);
INSERT INTO {{schema}}_numbers (n) VALUES (56);
INSERT INTO {{schema}}_numbers (n) VALUES (57);
INSERT INTO {{schema}}_numbers (n) VALUES (58);
INSERT INTO {{schema}}_numbers (n) VALUES (59);
INSERT INTO {{schema}}_numbers (n) VALUES (60);
INSERT INTO {{schema}}_numbers (n) VALUES (61);
INSERT INTO {{schema}}_numbers (n) VALUES (62);
INSERT INTO {{schema}}_numbers (n) VALUES (63);
INSERT INTO {{schema}}_numbers (n) VALUES (64);
INSERT INTO {{schema}}_numbers (n) VALUES (65);
INSERT INTO {{schema}}_numbers (n) VALUES (66);
INSERT INTO {{schema}}_numbers (n) VALUES (67);
INSERT INTO {{schema}}_numbers (n) VALUES (68);
INSERT INTO {{schema}}_numbers (n) VALUES (69);
INSERT INTO {{schema}}_numbers (n) VALUES (70);
INSERT INTO {{schema}}_numbers (n) VALUES (71);
INSERT INTO {{schema}}_numbers (n) VALUES (72);
INSERT INTO {{schema}}_numbers (n) VALUES (73);
INSERT INTO {{schema}}_numbers (n) VALUES (74);
INSERT INTO {{schema}}_numbers (n) VALUES (75);
INSERT INTO {{schema}}_numbers (n) VALUES (76);
INSERT INTO {{schema}}_numbers (n) VALUES (77);
INSERT INTO {{schema}}_numbers (n) VALUES (78);
INSERT INTO {{schema}}_numbers (n) VALUES (79);
INSERT INTO {{schema}}_numbers (n) VALUES (80);
INSERT INTO {{schema}}_numbers (n) VALUES (81);
INSERT INTO {{schema}}_numbers (n) VALUES (82);
INSERT INTO {{schema}}_numbers (n) VALUES (83);
INSERT INTO {{schema}}_numbers (n) VALUES (84);
INSERT INTO {{schema}}_numbers (n) VALUES (85);
INSERT INTO {{schema}}_numbers (n) VALUES (86);
INSERT INTO {{schema}}_numbers (n) VALUES (87);
INSERT INTO {{schema}}_numbers (n) VALUES (88);
INSERT INTO {{schema}}_numbers (n) VALUES (89);
INSERT INTO {{schema}}_numbers (n) VALUES (90);
INSERT INTO {{schema}}_numbers (n) VALUES (91);
INSERT INTO {{schema}}_numbers (n) VALUES (92);
INSERT INTO {{schema}}_numbers (n) VALUES (93);
INSERT INTO {{schema}}_numbers (n) VALUES (94);
INSERT INTO {{schema}}_numbers (n) VALUES (95);
INSERT INTO {{schema}}_numbers (n) VALUES (96);
INSERT INTO {{schema}}_numbers (n) VALUES (97);
INSERT INTO {{schema}}_numbers (n) VALUES (98);
INSERT INTO {{schema}}_numbers (n) VALUES (99);
INSERT INTO {{schema}}_numbers (n) VALUES (100);
INSERT INTO {{schema}}_numbers (n) VALUES (101);
INSERT INTO {{schema}}_numbers (n) VALUES (102);
INSERT INTO {{schema}}_numbers (n) VALUES (103);
INSERT INTO {{schema}}_numbers (n) VALUES (104);
INSERT INTO {{schema}}_numbers (n) VALUES (105);
INSERT INTO {{schema}}_numbers (n) VALUES (106);
INSERT INTO {{schema}}_numbers (n) VALUES (107);
INSERT INTO {{schema}}_numbers (n) VALUES (108);
INSERT INTO {{schema}}_numbers (n) VALUES (109);
INSERT INTO {{schema}}_numbers (n) VALUES (110);
INSERT INTO {{schema}}_numbers (n) VALUES (111);
INSERT INTO {{schema}}_numbers (n) VALUES (112);
INSERT INTO {{schema}}_numbers (n) VALUES (113);
INSERT INTO {{schema}}_numbers (n) VALUES (114);
INSERT INTO {{schema}}_numbers (n) VALUES (115);
INSERT INTO {{schema}}_numbers (n) VALUES (116);
INSERT INTO {{schema}}_numbers (n) VALUES (117);
INSERT INTO {{schema}}_numbers (n) VALUES (118);
INSERT INTO {{schema}}_numbers (n) VALUES (119);
INSERT INTO {{schema}}_numbers (n) VALUES (120);
INSERT INTO {{schema}}_numbers (n) VALUES (121);
INSERT INTO {{schema}}_numbers (n) VALUES (122);
INSERT INTO {{schema}}_numbers (n) VALUES (123);
INSERT INTO {{schema}}_numbers (n) VALUES (124);
INSERT INTO {{schema}}_numbers (n) VALUES (125);
INSERT INTO {{schema}}_numbers (n) VALUES (126);
INSERT INTO {{schema}}_numbers (n) VALUES (127);
INSERT INTO {{schema}}_numbers (n) VALUES (128);
INSERT INTO {{schema}}_numbers (n) VALUES (129);
INSERT INTO {{schema}}_numbers (n) VALUES (130);
INSERT INTO {{schema}}_numbers (n) VALUES (131);
INSERT INTO {{schema}}_numbers (n) VALUES (132);
INSERT INTO {{schema}}_numbers (n) VALUES (133);
INSERT INTO {{schema}}_numbers (n) VALUES (134);
INSERT INTO {{schema}}_numbers (n) VALUES (135);
INSERT INTO {{schema}}_numbers (n) VALUES (136);
INSERT INTO {{schema}}_numbers (n) VALUES (137);
INSERT INTO {{schema}}_numbers (n) VALUES (138);
INSERT INTO {{schema}}_numbers (n) VALUES (139);
INSERT INTO {{schema}}_numbers (n) VALUES (140);
INSERT INTO {{schema}}_numbers (n) VALUES (141);
INSERT INTO {{schema}}_numbers (n) VALUES (142);
INSERT INTO {{schema}}_numbers (n) VALUES (143);
INSERT INTO {{schema}}_numbers (n) VALUES (144);
INSERT INTO {{schema}}_numbers (n) VALUES (145);
INSERT INTO {{schema}}_numbers (n) VALUES (146);
INSERT INTO {{schema}}_numbers (n) VALUES (147);
INSERT INTO {{schema}}_numbers (n) VALUES (148);
INSERT INTO {{schema}}_numbers (n) VALUES (149);
INSERT INTO {{schema}}_numbers (n) VALUES (150);
INSERT INTO {{schema}}_numbers (n) VALUES (151);
INSERT INTO {{schema}}_numbers (n) VALUES (152);
INSERT INTO {{schema}}_numbers (n) VALUES (153);
INSERT INTO {{schema}}_numbers (n) VALUES (154);
INSERT INTO {{schema}}_numbers (n) VALUES (155);
INSERT INTO {{schema}}_numbers (n) VALUES (156);
INSERT INTO {{schema}}_numbers (n) VALUES (157);
INSERT INTO {{schema}}_numbers (n) VALUES (158);
INSERT INTO {{schema}}_numbers (n) VALUES (159);
INSERT INTO {{schema}}_numbers (n) VALUES (160);
INSERT INTO {{schema}}_numbers (n) VALUES (161);
INSERT INTO {{schema}}_numbers (n) VALUES (162);
INSERT INTO {{schema}}_numbers (n) VALUES (163);
INSERT INTO {{schema}}_numbers (n) VALUES (164);
INSERT INTO {{schema}}_numbers (n) VALUES (165);
INSERT INTO {{schema}}_numbers (n) VALUES (166);
INSERT INTO {{schema}}_numbers (n) VALUES (167);
INSERT INTO {{schema}}_numbers (n) VALUES (168);
INSERT INTO {{schema}}_numbers (n) VALUES (169);
INSERT INTO {{schema}}_numbers (n) VALUES (170);
INSERT INTO {{schema}}_numbers (n) VALUES (171);
INSERT INTO {{schema}}_numbers (n) VALUES (172);
INSERT INTO {{schema}}_numbers (n) VALUES (173);
INSERT INTO {{schema}}_numbers (n) VALUES (174);
INSERT INTO {{schema}}_numbers (n) VALUES (175);
INSERT INTO {{schema}}_numbers (n) VALUES (176);
INSERT INTO {{schema}}_numbers (n) VALUES (177);
INSERT INTO {{schema}}_numbers (n) VALUES (178);
INSERT INTO {{schema}}_numbers (n) VALUES (179);
INSERT INTO {{schema}}_numbers (n) VALUES (180);
INSERT INTO {{schema}}_numbers (n) VALUES (181);
INSERT INTO {{schema}}_numbers (n) VALUES (182);
INSERT INTO {{schema}}_numbers (n) VALUES (183);
INSERT INTO {{schema}}_numbers (n) VALUES (184);
INSERT INTO {{schema}}_numbers (n) VALUES (185);
INSERT INTO {{schema}}_numbers (n) VALUES (186);
INSERT INTO {{schema}}_numbers (n) VALUES (187);
INSERT INTO {{schema}}_numbers (n) VALUES (188);
INSERT INTO {{schema}}_numbers (n) VALUES (189);
INSERT INTO {{schema}}_numbers (n) VALUES (190);
INSERT INTO {{schema}}_numbers (n) VALUES (191);
INSERT INTO {{schema}}_numbers (n) VALUES (192);
INSERT INTO {{schema}}_numbers (n) VALUES (193);
INSERT INTO {{schema}}_numbers (n) VALUES (194);
INSERT INTO {{schema}}_numbers (n) VALUES (195);
INSERT INTO {{schema}}_numbers (n) VALUES (196);
INSERT INTO {{schema}}_numbers (n) VALUES (197);
INSERT INTO {{schema}}_numbers (n) VALUES (198);
INSERT INTO {{schema}}_numbers (n) VALUES (199);
INSERT INTO {{schema}}_numbers (n) VALUES (200);
INSERT INTO {{schema}}_numbers (n) VALUES (201);
INSERT INTO {{schema}}_numbers (n) VALUES (202);
INSERT INTO {{schema}}_numbers (n) VALUES (203);
INSERT INTO {{schema}}_numbers (n) VALUES (204);
INSERT INTO {{schema}}_numbers (n) VALUES (205);
INSERT INTO {{schema}}_numbers (n) VALUES (206);
INSERT INTO {{schema}}_numbers (n) VALUES (207);
INSERT INTO {{schema}}_numbers (n) VALUES (208);
INSERT INTO {{schema}}_numbers (n) VALUES (209);
INSERT INTO {{schema}}_numbers (n) VALUES (210);
INSERT INTO {{schema}}_numbers (n) VALUES (211);
INSERT INTO {{schema}}_numbers (n) VALUES (212);
INSERT INTO {{schema}}_numbers (n) VALUES (213);
INSERT INTO {{schema}}_numbers (n) VALUES (214);
INSERT INTO {{schema}}_numbers (n) VALUES (215);
INSERT INTO {{schema}}_numbers (n) VALUES (216);
INSERT INTO {{schema}}_numbers (n) VALUES (217);
INSERT INTO {{schema}}_numbers (n) VALUES (218);
INSERT INTO {{schema}}_numbers (n) VALUES (219);
INSERT INTO {{schema}}_numbers (n) VALUES (220);
INSERT INTO {{schema}}_numbers (n) VALUES (221);
INSERT INTO {{schema}}_numbers (n) VALUES (222);
INSERT INTO {{schema}}_numbers (n) VALUES (223);
INSERT INTO {{schema}}_numbers (n) VALUES (224);
INSERT INTO {{schema}}_numbers (n) VALUES (225);
INSERT INTO {{schema}}_numbers (n) VALUES (226);
INSERT INTO {{schema}}_numbers (n) VALUES (227);
INSERT INTO {{schema}}_numbers (n) VALUES (228);
INSERT INTO {{schema}}_numbers (n) VALUES (229);
INSERT INTO {{schema}}_numbers (n) VALUES (230);
INSERT INTO {{schema}}_numbers (n) VALUES (231);
INSERT INTO {{schema}}_numbers (n) VALUES (232);
INSERT INTO {{schema}}_numbers (n) VALUES (233);
INSERT INTO {{schema}}_numbers (n) VALUES (234);
INSERT INTO {{schema}}_numbers (n) VALUES (235);
INSERT INTO {{schema}}_numbers (n) VALUES (236);
INSERT INTO {{schema}}_numbers (n) VALUES (237);
INSERT INTO {{schema}}_numbers (n) VALUES (238);
INSERT INTO {{schema}}_numbers (n) VALUES (239);
INSERT INTO {{schema}}_numbers (n) VALUES (240);
INSERT INTO {{schema}}_numbers (n) VALUES (241);
INSERT INTO {{schema}}_numbers (n) VALUES (242);
INSERT INTO {{schema}}_numbers (n) VALUES (243);
INSERT INTO {{schema}}_numbers (n) VALUES (244);
INSERT INTO {{schema}}_numbers (n) VALUES (245);
INSERT INTO {{schema}}_numbers (n) VALUES (246);
INSERT INTO {{schema}}_numbers (n) VALUES (247);
INSERT INTO {{schema}}_numbers (n) VALUES (248);
INSERT INTO {{schema}}_numbers (n) VALUES (249);
INSERT INTO {{schema}}_numbers (n) VALUES (250);
INSERT INTO {{schema}}_numbers (n) VALUES (251);
INSERT INTO {{schema}}_numbers (n) VALUES (252);
INSERT INTO {{schema}}_numbers (n) VALUES (253);
INSERT INTO {{schema}}_numbers (n) VALUES (254);
INSERT INTO {{schema}}_numbers (n) VALUES (255);
INSERT INTO {{schema}}_numbers (n) VALUES (256);
INSERT INTO {{schema}}_numbers (n) VALUES (257);
INSERT INTO {{schema}}_numbers (n) VALUES (258);
INSERT INTO {{schema}}_numbers (n) VALUES (259);
INSERT INTO {{schema}}_numbers (n) VALUES (260);
INSERT INTO {{schema}}_numbers (n) VALUES (261);
INSERT INTO {{schema}}_numbers (n) VALUES (262);
INSERT INTO {{schema}}_numbers (n) VALUES (263);
INSERT INTO {{schema}}_numbers (n) VALUES (264);
INSERT INTO {{schema}}_numbers (n) VALUES (265);
INSERT INTO {{schema}}_numbers (n) VALUES (266);
INSERT INTO {{schema}}_numbers (n) VALUES (267);
INSERT INTO {{schema}}_numbers (n) VALUES (268);
INSERT INTO {{schema}}_numbers (n) VALUES (269);
INSERT INTO {{schema}}_numbers (n) VALUES (270);
INSERT INTO {{schema}}_numbers (n) VALUES (271);
INSERT INTO {{schema}}_numbers (n) VALUES (272);
INSERT INTO {{schema}}_numbers (n) VALUES (273);
INSERT INTO {{schema}}_numbers (n) VALUES (274);
INSERT INTO {{schema}}_numbers (n) VALUES (275);
INSERT INTO {{schema}}_numbers (n) VALUES (276);
INSERT INTO {{schema}}_numbers (n) VALUES (277);
INSERT INTO {{schema}}_numbers (n) VALUES (278);
INSERT INTO {{schema}}_numbers (n) VALUES (279);
INSERT INTO {{schema}}_numbers (n) VALUES (280);
INSERT INTO {{schema}}_numbers (n) VALUES (281);
INSERT INTO {{schema}}_numbers (n) VALUES (282);
INSERT INTO {{schema}}_numbers (n) VALUES (283);
INSERT INTO {{schema}}_numbers (n) VALUES (284);
INSERT INTO {{schema}}_numbers (n) VALUES (285);
INSERT INTO {{schema}}_numbers (n) VALUES (286);
INSERT INTO {{schema}}_numbers (n) VALUES (287);
INSERT INTO {{schema}}_numbers (n) VALUES (288);
INSERT INTO {{schema}}_numbers (n) VALUES (289);
INSERT INTO {{schema}}_numbers (n) VALUES (290);
INSERT INTO {{schema}}_numbers (n) VALUES (291);
INSERT INTO {{schema}}_numbers (n) VALUES (292);
INSERT INTO {{schema}}_numbers (n) VALUES (293);
INSERT INTO {{schema}}_numbers (n) VALUES (294);
INSERT INTO {{schema}}_numbers (n) VALUES (295);
INSERT INTO {{schema}}_numbers (n) VALUES (296);
INSERT INTO {{schema}}_numbers (n) VALUES (297);
INSERT INTO {{schema}}_numbers (n) VALUES (298);
INSERT INTO {{schema}}_numbers (n) VALUES (299);
INSERT INTO {{schema}}_numbers (n) VALUES (300);
INSERT INTO {{schema}}_numbers (n) VALUES (301);
INSERT INTO {{schema}}_numbers (n) VALUES (302);
INSERT INTO {{schema}}_numbers (n) VALUES (303);
INSERT INTO {{schema}}_numbers (n) VALUES (304);
INSERT INTO {{schema}}_numbers (n) VALUES (305);
INSERT INTO {{schema}}_numbers (n) VALUES (306);
INSERT INTO {{schema}}_numbers (n) VALUES (307);
INSERT INTO {{schema}}_numbers (n) VALUES (308);
INSERT INTO {{schema}}_numbers (n) VALUES (309);
INSERT INTO {{schema}}_numbers (n) VALUES (310);
INSERT INTO {{schema}}_numbers (n) VALUES (311);
INSERT INTO {{schema}}_numbers (n) VALUES (312);
INSERT INTO {{schema}}_numbers (n) VALUES (313);
INSERT INTO {{schema}}_numbers (n) VALUES (314);
INSERT INTO {{schema}}_numbers (n) VALUES (315);
INSERT INTO {{schema}}_numbers (n) VALUES (316);
INSERT INTO {{schema}}_numbers (n) VALUES (317);
INSERT INTO {{schema}}_numbers (n) VALUES (318);
INSERT INTO {{schema}}_numbers (n) VALUES (319);
INSERT INTO {{schema}}_numbers (n) VALUES (320);
INSERT INTO {{schema}}_numbers (n) VALUES (321);
INSERT INTO {{schema}}_numbers (n) VALUES (322);
INSERT INTO {{schema}}_numbers (n) VALUES (323);
INSERT INTO {{schema}}_numbers (n) VALUES (324);
INSERT INTO {{schema}}_numbers (n) VALUES (325);
INSERT INTO {{schema}}_numbers (n) VALUES (326);
INSERT INTO {{schema}}_numbers (n) VALUES (327);
INSERT INTO {{schema}}_numbers (n) VALUES (328);
INSERT INTO {{schema}}_numbers (n) VALUES (329);
INSERT INTO {{schema}}_numbers (n) VALUES (330);
INSERT INTO {{schema}}_numbers (n) VALUES (331);
INSERT INTO {{schema}}_numbers (n) VALUES (332);
INSERT INTO {{schema}}_numbers (n) VALUES (333);
INSERT INTO {{schema}}_numbers (n) VALUES (334);
INSERT INTO {{schema}}_numbers (n) VALUES (335);
INSERT INTO {{schema}}_numbers (n) VALUES (336);
INSERT INTO {{schema}}_numbers (n) VALUES (337);
INSERT INTO {{schema}}_numbers (n) VALUES (338);
INSERT INTO {{schema}}_numbers (n) VALUES (339);
INSERT INTO {{schema}}_numbers (n) VALUES (340);
INSERT INTO {{schema}}_numbers (n) VALUES (341);
INSERT INTO {{schema}}_numbers (n) VALUES (342);
INSERT INTO {{schema}}_numbers (n) VALUES (343);
INSERT INTO {{schema}}_numbers (n) VALUES (344);
INSERT INTO {{schema}}_numbers (n) VALUES (345);
INSERT INTO {{schema}}_numbers (n) VALUES (346);
INSERT INTO {{schema}}_numbers (n) VALUES (347);
INSERT INTO {{schema}}_numbers (n) VALUES (348);
INSERT INTO {{schema}}_numbers (n) VALUES (349);
INSERT INTO {{schema}}_numbers (n) VALUES (350);
INSERT INTO {{schema}}_numbers (n) VALUES (351);
INSERT INTO {{schema}}_numbers (n) VALUES (352);
INSERT INTO {{schema}}_numbers (n) VALUES (353);
INSERT INTO {{schema}}_numbers (n) VALUES (354);
INSERT INTO {{schema}}_numbers (n) VALUES (355);
INSERT INTO {{schema}}_numbers (n) VALUES (356);
INSERT INTO {{schema}}_numbers (n) VALUES (357);
INSERT INTO {{schema}}_numbers (n) VALUES (358);
INSERT INTO {{schema}}_numbers (n) VALUES (359);
INSERT INTO {{schema}}_numbers (n) VALUES (360);
INSERT INTO {{schema}}_numbers (n) VALUES (361);
INSERT INTO {{schema}}_numbers (n) VALUES (362);
INSERT INTO {{schema}}_numbers (n) VALUES (363);
INSERT INTO {{schema}}_numbers (n) VALUES (364);
INSERT INTO {{schema}}_numbers (n) VALUES (365);
INSERT INTO {{schema}}_numbers (n) VALUES (366);
INSERT INTO {{schema}}_numbers (n) VALUES (367);
INSERT INTO {{schema}}_numbers (n) VALUES (368);
INSERT INTO {{schema}}_numbers (n) VALUES (369);
INSERT INTO {{schema}}_numbers (n) VALUES (370);
INSERT INTO {{schema}}_numbers (n) VALUES (371);
INSERT INTO {{schema}}_numbers (n) VALUES (372);
INSERT INTO {{schema}}_numbers (n) VALUES (373);
INSERT INTO {{schema}}_numbers (n) VALUES (374);
INSERT INTO {{schema}}_numbers (n) VALUES (375);
INSERT INTO {{schema}}_numbers (n) VALUES (376);
INSERT INTO {{schema}}_numbers (n) VALUES (377);
INSERT INTO {{schema}}_numbers (n) VALUES (378);
INSERT INTO {{schema}}_numbers (n) VALUES (379);
INSERT INTO {{schema}}_numbers (n) VALUES (380);
INSERT INTO {{schema}}_numbers (n) VALUES (381);
INSERT INTO {{schema}}_numbers (n) VALUES (382);
INSERT INTO {{schema}}_numbers (n) VALUES (383);
INSERT INTO {{schema}}_numbers (n) VALUES (384);
INSERT INTO {{schema}}_numbers (n) VALUES (385);
INSERT INTO {{schema}}_numbers (n) VALUES (386);
INSERT INTO {{schema}}_numbers (n) VALUES (387);
INSERT INTO {{schema}}_numbers (n) VALUES (388);
INSERT INTO {{schema}}_numbers (n) VALUES (389);
INSERT INTO {{schema}}_numbers (n) VALUES (390);
INSERT INTO {{schema}}_numbers (n) VALUES (391);
INSERT INTO {{schema}}_numbers (n) VALUES (392);
INSERT INTO {{schema}}_numbers (n) VALUES (393);
INSERT INTO {{schema}}_numbers (n) VALUES (394);
INSERT INTO {{schema}}_numbers (n) VALUES (395);
INSERT INTO {{schema}}_numbers (n) VALUES (396);
INSERT INTO {{schema}}_numbers (n) VALUES (397);
INSERT INTO {{schema}}_numbers (n) VALUES (398);
INSERT INTO {{schema}}_numbers (n) VALUES (399);
INSERT INTO {{schema}}_numbers (n) VALUES (400);
INSERT INTO {{schema}}_numbers (n) VALUES (401);
INSERT INTO {{schema}}_numbers (n) VALUES (402);
INSERT INTO {{schema}}_numbers (n) VALUES (403);
INSERT INTO {{schema}}_numbers (n) VALUES (404);
INSERT INTO {{schema}}_numbers (n) VALUES (405);
INSERT INTO {{schema}}_numbers (n) VALUES (406);
INSERT INTO {{schema}}_numbers (n) VALUES (407);
INSERT INTO {{schema}}_numbers (n) VALUES (408);
INSERT INTO {{schema}}_numbers (n) VALUES (409);
INSERT INTO {{schema}}_numbers (n) VALUES (410);
INSERT INTO {{schema}}_numbers (n) VALUES (411);
INSERT INTO {{schema}}_numbers (n) VALUES (412);
INSERT INTO {{schema}}_numbers (n) VALUES (413);
INSERT INTO {{schema}}_numbers (n) VALUES (414);
INSERT INTO {{schema}}_numbers (n) VALUES (415);
INSERT INTO {{schema}}_numbers (n) VALUES (416);
INSERT INTO {{schema}}_numbers (n) VALUES (417);
INSERT INTO {{schema}}_numbers (n) VALUES (418);
INSERT INTO {{schema}}_numbers (n) VALUES (419);
INSERT INTO {{schema}}_numbers (n) VALUES (420);
INSERT INTO {{schema}}_numbers (n) VALUES (421);
INSERT INTO {{schema}}_numbers (n) VALUES (422);
INSERT INTO {{schema}}_numbers (n) VALUES (423);
INSERT INTO {{schema}}_numbers (n) VALUES (424);
INSERT INTO {{schema}}_numbers (n) VALUES (425);
INSERT INTO {{schema}}_numbers (n) VALUES (426);
INSERT INTO {{schema}}_numbers (n) VALUES (427);
INSERT INTO {{schema}}_numbers (n) VALUES (428);
INSERT INTO {{schema}}_numbers (n) VALUES (429);
INSERT INTO {{schema}}_numbers (n) VALUES (430);
INSERT INTO {{schema}}_numbers (n) VALUES (431);
INSERT INTO {{schema}}_numbers (n) VALUES (432);
INSERT INTO {{schema}}_numbers (n) VALUES (433);
INSERT INTO {{schema}}_numbers (n) VALUES (434);
INSERT INTO {{schema}}_numbers (n) VALUES (435);
INSERT INTO {{schema}}_numbers (n) VALUES (436);
INSERT INTO {{schema}}_numbers (n) VALUES (437);
INSERT INTO {{schema}}_numbers (n) VALUES (438);
INSERT INTO {{schema}}_numbers (n) VALUES (439);
INSERT INTO {{schema}}_numbers (n) VALUES (440);
INSERT INTO {{schema}}_numbers (n) VALUES (441);
INSERT INTO {{schema}}_numbers (n) VALUES (442);
INSERT INTO {{schema}}_numbers (n) VALUES (443);
INSERT INTO {{schema}}_numbers (n) VALUES (444);
INSERT INTO {{schema}}_numbers (n) VALUES (445);
INSERT INTO {{schema}}_numbers (n) VALUES (446);
INSERT INTO {{schema}}_numbers (n) VALUES (447);
INSERT INTO {{schema}}_numbers (n) VALUES (448);
INSERT INTO {{schema}}_numbers (n) VALUES (449);
INSERT INTO {{schema}}_numbers (n) VALUES (450);
INSERT INTO {{schema}}_numbers (n) VALUES (451);
INSERT INTO {{schema}}_numbers (n) VALUES (452);
INSERT INTO {{schema}}_numbers (n) VALUES (453);
INSERT INTO {{schema}}_numbers (n) VALUES (454);
INSERT INTO {{schema}}_numbers (n) VALUES (455);
INSERT INTO {{schema}}_numbers (n) VALUES (456);
INSERT INTO {{schema}}_numbers (n) VALUES (457);
INSERT INTO {{schema}}_numbers (n) VALUES (458);
INSERT INTO {{schema}}_numbers (n) VALUES (459);
INSERT INTO {{schema}}_numbers (n) VALUES (460);
INSERT INTO {{schema}}_numbers (n) VALUES (461);
INSERT INTO {{schema}}_numbers (n) VALUES (462);
INSERT INTO {{schema}}_numbers (n) VALUES (463);
INSERT INTO {{schema}}_numbers (n) VALUES (464);
INSERT INTO {{schema}}_numbers (n) VALUES (465);
INSERT INTO {{schema}}_numbers (n) VALUES (466);
INSERT INTO {{schema}}_numbers (n) VALUES (467);
INSERT INTO {{schema}}_numbers (n) VALUES (468);
INSERT INTO {{schema}}_numbers (n) VALUES (469);
INSERT INTO {{schema}}_numbers (n) VALUES (470);
INSERT INTO {{schema}}_numbers (n) VALUES (471);
INSERT INTO {{schema}}_numbers (n) VALUES (472);
INSERT INTO {{schema}}_numbers (n) VALUES (473);
INSERT INTO {{schema}}_numbers (n) VALUES (474);
INSERT INTO {{schema}}_numbers (n) VALUES (475);
INSERT INTO {{schema}}_numbers (n) VALUES (476);
INSERT INTO {{schema}}_numbers (n) VALUES (477);
INSERT INTO {{schema}}_numbers (n) VALUES (478);
INSERT INTO {{schema}}_numbers (n) VALUES (479);
INSERT INTO {{schema}}_numbers (n) VALUES (480);
INSERT INTO {{schema}}_numbers (n) VALUES (481);
INSERT INTO {{schema}}_numbers (n) VALUES (482);
INSERT INTO {{schema}}_numbers (n) VALUES (483);
INSERT INTO {{schema}}_numbers (n) VALUES (484);
INSERT INTO {{schema}}_numbers (n) VALUES (485);
INSERT INTO {{schema}}_numbers (n) VALUES (486);
INSERT INTO {{schema}}_numbers (n) VALUES (487);
INSERT INTO {{schema}}_numbers (n) VALUES (488);
INSERT INTO {{schema}}_numbers (n) VALUES (489);
INSERT INTO {{schema}}_numbers (n) VALUES (490);
INSERT INTO {{schema}}_numbers (n) VALUES (491);
INSERT INTO {{schema}}_numbers (n) VALUES (492);
INSERT INTO {{schema}}_numbers (n) VALUES (493);
INSERT INTO {{schema}}_numbers (n) VALUES (494);
INSERT INTO {{schema}}_numbers (n) VALUES (495);
INSERT INTO {{schema}}_numbers (n) VALUES (496);
INSERT INTO {{schema}}_numbers (n) VALUES (497);
INSERT INTO {{schema}}_numbers (n) VALUES (498);
INSERT INTO {{schema}}_numbers (n) VALUES (499);
INSERT INTO {{schema}}_numbers (n) VALUES (500);
INSERT INTO {{schema}}_numbers (n) VALUES (501);
INSERT INTO {{schema}}_numbers (n) VALUES (502);
INSERT INTO {{schema}}_numbers (n) VALUES (503);
INSERT INTO {{schema}}_numbers (n) VALUES (504);
INSERT INTO {{schema}}_numbers (n) VALUES (505);
INSERT INTO {{schema}}_numbers (n) VALUES (506);
INSERT INTO {{schema}}_numbers (n) VALUES (507);
INSERT INTO {{schema}}_numbers (n) VALUES (508);
INSERT INTO {{schema}}_numbers (n) VALUES (509);
INSERT INTO {{schema}}_numbers (n) VALUES (510);
INSERT INTO {{schema}}_numbers (n) VALUES (511);
INSERT INTO {{schema}}_numbers (n) VALUES (512);
INSERT INTO {{schema}}_numbers (n) VALUES (513);
INSERT INTO {{schema}}_numbers (n) VALUES (514);
INSERT INTO {{schema}}_numbers (n) VALUES (515);
INSERT INTO {{schema}}_numbers (n) VALUES (516);
INSERT INTO {{schema}}_numbers (n) VALUES (517);
INSERT INTO {{schema}}_numbers (n) VALUES (518);
INSERT INTO {{schema}}_numbers (n) VALUES (519);
INSERT INTO {{schema}}_numbers (n) VALUES (520);
INSERT INTO {{schema}}_numbers (n) VALUES (521);
INSERT INTO {{schema}}_numbers (n) VALUES (522);
INSERT INTO {{schema}}_numbers (n) VALUES (523);
INSERT INTO {{schema}}_numbers (n) VALUES (524);
INSERT INTO {{schema}}_numbers (n) VALUES (525);
INSERT INTO {{schema}}_numbers (n) VALUES (526);
INSERT INTO {{schema}}_numbers (n) VALUES (527);
INSERT INTO {{schema}}_numbers (n) VALUES (528);
INSERT INTO {{schema}}_numbers (n) VALUES (529);
INSERT INTO {{schema}}_numbers (n) VALUES (530);
INSERT INTO {{schema}}_numbers (n) VALUES (531);
INSERT INTO {{schema}}_numbers (n) VALUES (532);
INSERT INTO {{schema}}_numbers (n) VALUES (533);
INSERT INTO {{schema}}_numbers (n) VALUES (534);
INSERT INTO {{schema}}_numbers (n) VALUES (535);
INSERT INTO {{schema}}_numbers (n) VALUES (536);
INSERT INTO {{schema}}_numbers (n) VALUES (537);
INSERT INTO {{schema}}_numbers (n) VALUES (538);
INSERT INTO {{schema}}_numbers (n) VALUES (539);
INSERT INTO {{schema}}_numbers (n) VALUES (540);
INSERT INTO {{schema}}_numbers (n) VALUES (541);
INSERT INTO {{schema}}_numbers (n) VALUES (542);
INSERT INTO {{schema}}_numbers (n) VALUES (543);
INSERT INTO {{schema}}_numbers (n) VALUES (544);
INSERT INTO {{schema}}_numbers (n) VALUES (545);
INSERT INTO {{schema}}_numbers (n) VALUES (546);
INSERT INTO {{schema}}_numbers (n) VALUES (547);
INSERT INTO {{schema}}_numbers (n) VALUES (548);
INSERT INTO {{schema}}_numbers (n) VALUES (549);
INSERT INTO {{schema}}_numbers (n) VALUES (550);
INSERT INTO {{schema}}_numbers (n) VALUES (551);
INSERT INTO {{schema}}_numbers (n) VALUES (552);
INSERT INTO {{schema}}_numbers (n) VALUES (553);
INSERT INTO {{schema}}_numbers (n) VALUES (554);
INSERT INTO {{schema}}_numbers (n) VALUES (555);
INSERT INTO {{schema}}_numbers (n) VALUES (556);
INSERT INTO {{schema}}_numbers (n) VALUES (557);
INSERT INTO {{schema}}_numbers (n) VALUES (558);
INSERT INTO {{schema}}_numbers (n) VALUES (559);
INSERT INTO {{schema}}_numbers (n) VALUES (560);
INSERT INTO {{schema}}_numbers (n) VALUES (561);
INSERT INTO {{schema}}_numbers (n) VALUES (562);
INSERT INTO {{schema}}_numbers (n) VALUES (563);
INSERT INTO {{schema}}_numbers (n) VALUES (564);
INSERT INTO {{schema}}_numbers (n) VALUES (565);
INSERT INTO {{schema}}_numbers (n) VALUES (566);
INSERT INTO {{schema}}_numbers (n) VALUES (567);
INSERT INTO {{schema}}_numbers (n) VALUES (568);
INSERT INTO {{schema}}_numbers (n) VALUES (569);
INSERT INTO {{schema}}_numbers (n) VALUES (570);
INSERT INTO {{schema}}_numbers (n) VALUES (571);
INSERT INTO {{schema}}_numbers (n) VALUES (572);
INSERT INTO {{schema}}_numbers (n) VALUES (573);
INSERT INTO {{schema}}_numbers (n) VALUES (574);
INSERT INTO {{schema}}_numbers (n) VALUES (575);
INSERT INTO {{schema}}_numbers (n) VALUES (576);
INSERT INTO {{schema}}_numbers (n) VALUES (577);
INSERT INTO {{schema}}_numbers (n) VALUES (578);
INSERT INTO {{schema}}_numbers (n) VALUES (579);
INSERT INTO {{schema}}_numbers (n) VALUES (580);
INSERT INTO {{schema}}_numbers (n) VALUES (581);
INSERT INTO {{schema}}_numbers (n) VALUES (582);
INSERT INTO {{schema}}_numbers (n) VALUES (583);
INSERT INTO {{schema}}_numbers (n) VALUES (584);
INSERT INTO {{schema}}_numbers (n) VALUES (585);
INSERT INTO {{schema}}_numbers (n) VALUES (586);
INSERT INTO {{schema}}_numbers (n) VALUES (587);
INSERT INTO {{schema}}_numbers (n) VALUES (588);
INSERT INTO {{schema}}_numbers (n) VALUES (589);
INSERT INTO {{schema}}_numbers (n) VALUES (590);
INSERT INTO {{schema}}_numbers (n) VALUES (591);
INSERT INTO {{schema}}_numbers (n) VALUES (592);
INSERT INTO {{schema}}_numbers (n) VALUES (593);
INSERT INTO {{schema}}_numbers (n) VALUES (594);
INSERT INTO {{schema}}_numbers (n) VALUES (595);
INSERT INTO {{schema}}_numbers (n) VALUES (596);
INSERT INTO {{schema}}_numbers (n) VALUES (597);
INSERT INTO {{schema}}_numbers (n) VALUES (598);
INSERT INTO {{schema}}_numbers (n) VALUES (599);
INSERT INTO {{schema}}_numbers (n) VALUES (600);
INSERT INTO {{schema}}_numbers (n) VALUES (601);
INSERT INTO {{schema}}_numbers (n) VALUES (602);
INSERT INTO {{schema}}_numbers (n) VALUES (603);
INSERT INTO {{schema}}_numbers (n) VALUES (604);
INSERT INTO {{schema}}_numbers (n) VALUES (605);
INSERT INTO {{schema}}_numbers (n) VALUES (606);
INSERT INTO {{schema}}_numbers (n) VALUES (607);
INSERT INTO {{schema}}_numbers (n) VALUES (608);
INSERT INTO {{schema}}_numbers (n) VALUES (609);
INSERT INTO {{schema}}_numbers (n) VALUES (610);
INSERT INTO {{schema}}_numbers (n) VALUES (611);
INSERT INTO {{schema}}_numbers (n) VALUES (612);
INSERT INTO {{schema}}_numbers (n) VALUES (613);
INSERT INTO {{schema}}_numbers (n) VALUES (614);
INSERT INTO {{schema}}_numbers (n) VALUES (615);
INSERT INTO {{schema}}_numbers (n) VALUES (616);
INSERT INTO {{schema}}_numbers (n) VALUES (617);
INSERT INTO {{schema}}_numbers (n) VALUES (618);
INSERT INTO {{schema}}_numbers (n) VALUES (619);
INSERT INTO {{schema}}_numbers (n) VALUES (620);
INSERT INTO {{schema}}_numbers (n) VALUES (621);
INSERT INTO {{schema}}_numbers (n) VALUES (622);
INSERT INTO {{schema}}_numbers (n) VALUES (623);
INSERT INTO {{schema}}_numbers (n) VALUES (624);
INSERT INTO {{schema}}_numbers (n) VALUES (625);
INSERT INTO {{schema}}_numbers (n) VALUES (626);
INSERT INTO {{schema}}_numbers (n) VALUES (627);
INSERT INTO {{schema}}_numbers (n) VALUES (628);
INSERT INTO {{schema}}_numbers (n) VALUES (629);
INSERT INTO {{schema}}_numbers (n) VALUES (630);
INSERT INTO {{schema}}_numbers (n) VALUES (631);
INSERT INTO {{schema}}_numbers (n) VALUES (632);
INSERT INTO {{schema}}_numbers (n) VALUES (633);
INSERT INTO {{schema}}_numbers (n) VALUES (634);
INSERT INTO {{schema}}_numbers (n) VALUES (635);
INSERT INTO {{schema}}_numbers (n) VALUES (636);
INSERT INTO {{schema}}_numbers (n) VALUES (637);
INSERT INTO {{schema}}_numbers (n) VALUES (638);
INSERT INTO {{schema}}_numbers (n) VALUES (639);
INSERT INTO {{schema}}_numbers (n) VALUES (640);
INSERT INTO {{schema}}_numbers (n) VALUES (641);
INSERT INTO {{schema}}_numbers (n) VALUES (642);
INSERT INTO {{schema}}_numbers (n) VALUES (643);
INSERT INTO {{schema}}_numbers (n) VALUES (644);
INSERT INTO {{schema}}_numbers (n) VALUES (645);
INSERT INTO {{schema}}_numbers (n) VALUES (646);
INSERT INTO {{schema}}_numbers (n) VALUES (647);
INSERT INTO {{schema}}_numbers (n) VALUES (648);
INSERT INTO {{schema}}_numbers (n) VALUES (649);
INSERT INTO {{schema}}_numbers (n) VALUES (650);
INSERT INTO {{schema}}_numbers (n) VALUES (651);
INSERT INTO {{schema}}_numbers (n) VALUES (652);
INSERT INTO {{schema}}_numbers (n) VALUES (653);
INSERT INTO {{schema}}_numbers (n) VALUES (654);
INSERT INTO {{schema}}_numbers (n) VALUES (655);
INSERT INTO {{schema}}_numbers (n) VALUES (656);
INSERT INTO {{schema}}_numbers (n) VALUES (657);
INSERT INTO {{schema}}_numbers (n) VALUES (658);
INSERT INTO {{schema}}_numbers (n) VALUES (659);
INSERT INTO {{schema}}_numbers (n) VALUES (660);
INSERT INTO {{schema}}_numbers (n) VALUES (661);
INSERT INTO {{schema}}_numbers (n) VALUES (662);
INSERT INTO {{schema}}_numbers (n) VALUES (663);
INSERT INTO {{schema}}_numbers (n) VALUES (664);
INSERT INTO {{schema}}_numbers (n) VALUES (665);
INSERT INTO {{schema}}_numbers (n) VALUES (666);
INSERT INTO {{schema}}_numbers (n) VALUES (667);
INSERT INTO {{schema}}_numbers (n) VALUES (668);
INSERT INTO {{schema}}_numbers (n) VALUES (669);
INSERT INTO {{schema}}_numbers (n) VALUES (670);
INSERT INTO {{schema}}_numbers (n) VALUES (671);
INSERT INTO {{schema}}_numbers (n) VALUES (672);
INSERT INTO {{schema}}_numbers (n) VALUES (673);
INSERT INTO {{schema}}_numbers (n) VALUES (674);
INSERT INTO {{schema}}_numbers (n) VALUES (675);
INSERT INTO {{schema}}_numbers (n) VALUES (676);
INSERT INTO {{schema}}_numbers (n) VALUES (677);
INSERT INTO {{schema}}_numbers (n) VALUES (678);
INSERT INTO {{schema}}_numbers (n) VALUES (679);
INSERT INTO {{schema}}_numbers (n) VALUES (680);
INSERT INTO {{schema}}_numbers (n) VALUES (681);
INSERT INTO {{schema}}_numbers (n) VALUES (682);
INSERT INTO {{schema}}_numbers (n) VALUES (683);
INSERT INTO {{schema}}_numbers (n) VALUES (684);
INSERT INTO {{schema}}_numbers (n) VALUES (685);
INSERT INTO {{schema}}_numbers (n) VALUES (686);
INSERT INTO {{schema}}_numbers (n) VALUES (687);
INSERT INTO {{schema}}_numbers (n) VALUES (688);
INSERT INTO {{schema}}_numbers (n) VALUES (689);
INSERT INTO {{schema}}_numbers (n) VALUES (690);
INSERT INTO {{schema}}_numbers (n) VALUES (691);
INSERT INTO {{schema}}_numbers (n) VALUES (692);
INSERT INTO {{schema}}_numbers (n) VALUES (693);
INSERT INTO {{schema}}_numbers (n) VALUES (694);
INSERT INTO {{schema}}_numbers (n) VALUES (695);
INSERT INTO {{schema}}_numbers (n) VALUES (696);
INSERT INTO {{schema}}_numbers (n) VALUES (697);
INSERT INTO {{schema}}_numbers (n) VALUES (698);
INSERT INTO {{schema}}_numbers (n) VALUES (699);
INSERT INTO {{schema}}_numbers (n) VALUES (700);
INSERT INTO {{schema}}_numbers (n) VALUES (701);
INSERT INTO {{schema}}_numbers (n) VALUES (702);
INSERT INTO {{schema}}_numbers (n) VALUES (703);
INSERT INTO {{schema}}_numbers (n) VALUES (704);
INSERT INTO {{schema}}_numbers (n) VALUES (705);
INSERT INTO {{schema}}_numbers (n) VALUES (706);
INSERT INTO {{schema}}_numbers (n) VALUES (707);
INSERT INTO {{schema}}_numbers (n) VALUES (708);
INSERT INTO {{schema}}_numbers (n) VALUES (709);
INSERT INTO {{schema}}_numbers (n) VALUES (710);
INSERT INTO {{schema}}_numbers (n) VALUES (711);
INSERT INTO {{schema}}_numbers (n) VALUES (712);
INSERT INTO {{schema}}_numbers (n) VALUES (713);
INSERT INTO {{schema}}_numbers (n) VALUES (714);
INSERT INTO {{schema}}_numbers (n) VALUES (715);
INSERT INTO {{schema}}_numbers (n) VALUES (716);
INSERT INTO {{schema}}_numbers (n) VALUES (717);
INSERT INTO {{schema}}_numbers (n) VALUES (718);
INSERT INTO {{schema}}_numbers (n) VALUES (719);
INSERT INTO {{schema}}_numbers (n) VALUES (720);
INSERT INTO {{schema}}_numbers (n) VALUES (721);
INSERT INTO {{schema}}_numbers (n) VALUES (722);
INSERT INTO {{schema}}_numbers (n) VALUES (723);
INSERT INTO {{schema}}_numbers (n) VALUES (724);
INSERT INTO {{schema}}_numbers (n) VALUES (725);
INSERT INTO {{schema}}_numbers (n) VALUES (726);
INSERT INTO {{schema}}_numbers (n) VALUES (727);
INSERT INTO {{schema}}_numbers (n) VALUES (728);
INSERT INTO {{schema}}_numbers (n) VALUES (729);
INSERT INTO {{schema}}_numbers (n) VALUES (730);
INSERT INTO {{schema}}_numbers (n) VALUES (731);
INSERT INTO {{schema}}_numbers (n) VALUES (732);
INSERT INTO {{schema}}_numbers (n) VALUES (733);
INSERT INTO {{schema}}_numbers (n) VALUES (734);
INSERT INTO {{schema}}_numbers (n) VALUES (735);
INSERT INTO {{schema}}_numbers (n) VALUES (736);
INSERT INTO {{schema}}_numbers (n) VALUES (737);
INSERT INTO {{schema}}_numbers (n) VALUES (738);
INSERT INTO {{schema}}_numbers (n) VALUES (739);
INSERT INTO {{schema}}_numbers (n) VALUES (740);
INSERT INTO {{schema}}_numbers (n) VALUES (741);
INSERT INTO {{schema}}_numbers (n) VALUES (742);
INSERT INTO {{schema}}_numbers (n) VALUES (743);
INSERT INTO {{schema}}_numbers (n) VALUES (744);
INSERT INTO {{schema}}_numbers (n) VALUES (745);
INSERT INTO {{schema}}_numbers (n) VALUES (746);
INSERT INTO {{schema}}_numbers (n) VALUES (747);
INSERT INTO {{schema}}_numbers (n) VALUES (748);
INSERT INTO {{schema}}_numbers (n) VALUES (749);
INSERT INTO {{schema}}_numbers (n) VALUES (750);
INSERT INTO {{schema}}_numbers (n) VALUES (751);
INSERT INTO {{schema}}_numbers (n) VALUES (752);
INSERT INTO {{schema}}_numbers (n) VALUES (753);
INSERT INTO {{schema}}_numbers (n) VALUES (754);
INSERT INTO {{schema}}_numbers (n) VALUES (755);
INSERT INTO {{schema}}_numbers (n) VALUES (756);
INSERT INTO {{schema}}_numbers (n) VALUES (757);
INSERT INTO {{schema}}_numbers (n) VALUES (758);
INSERT INTO {{schema}}_numbers (n) VALUES (759);
INSERT INTO {{schema}}_numbers (n) VALUES (760);
INSERT INTO {{schema}}_numbers (n) VALUES (761);
INSERT INTO {{schema}}_numbers (n) VALUES (762);
INSERT INTO {{schema}}_numbers (n) VALUES (763);
INSERT INTO {{schema}}_numbers (n) VALUES (764);
INSERT INTO {{schema}}_numbers (n) VALUES (765);
INSERT INTO {{schema}}_numbers (n) VALUES (766);
INSERT INTO {{schema}}_numbers (n) VALUES (767);
INSERT INTO {{schema}}_numbers (n) VALUES (768);
INSERT INTO {{schema}}_numbers (n) VALUES (769);
INSERT INTO {{schema}}_numbers (n) VALUES (770);
INSERT INTO {{schema}}_numbers (n) VALUES (771);
INSERT INTO {{schema}}_numbers (n) VALUES (772);
INSERT INTO {{schema}}_numbers (n) VALUES (773);
INSERT INTO {{schema}}_numbers (n) VALUES (774);
INSERT INTO {{schema}}_numbers (n) VALUES (775);
INSERT INTO {{schema}}_numbers (n) VALUES (776);
INSERT INTO {{schema}}_numbers (n) VALUES (777);
INSERT INTO {{schema}}_numbers (n) VALUES (778);
INSERT INTO {{schema}}_numbers (n) VALUES (779);
INSERT INTO {{schema}}_numbers (n) VALUES (780);
INSERT INTO {{schema}}_numbers (n) VALUES (781);
INSERT INTO {{schema}}_numbers (n) VALUES (782);
INSERT INTO {{schema}}_numbers (n) VALUES (783);
INSERT INTO {{schema}}_numbers (n) VALUES (784);
INSERT INTO {{schema}}_numbers (n) VALUES (785);
INSERT INTO {{schema}}_numbers (n) VALUES (786);
INSERT INTO {{schema}}_numbers (n) VALUES (787);
INSERT INTO {{schema}}_numbers (n) VALUES (788);
INSERT INTO {{schema}}_numbers (n) VALUES (789);
INSERT INTO {{schema}}_numbers (n) VALUES (790);
INSERT INTO {{schema}}_numbers (n) VALUES (791);
INSERT INTO {{schema}}_numbers (n) VALUES (792);
INSERT INTO {{schema}}_numbers (n) VALUES (793);
INSERT INTO {{schema}}_numbers (n) VALUES (794);
INSERT INTO {{schema}}_numbers (n) VALUES (795);
INSERT INTO {{schema}}_numbers (n) VALUES (796);
INSERT INTO {{schema}}_numbers (n) VALUES (797);
INSERT INTO {{schema}}_numbers (n) VALUES (798);
INSERT INTO {{schema}}_numbers (n) VALUES (799);
INSERT INTO {{schema}}_numbers (n) VALUES (800);
INSERT INTO {{schema}}_numbers (n) VALUES (801);
INSERT INTO {{schema}}_numbers (n) VALUES (802);
INSERT INTO {{schema}}_numbers (n) VALUES (803);
INSERT INTO {{schema}}_numbers (n) VALUES (804);
INSERT INTO {{schema}}_numbers (n) VALUES (805);
INSERT INTO {{schema}}_numbers (n) VALUES (806);
INSERT INTO {{schema}}_numbers (n) VALUES (807);
INSERT INTO {{schema}}_numbers (n) VALUES (808);
INSERT INTO {{schema}}_numbers (n) VALUES (809);
INSERT INTO {{schema}}_numbers (n) VALUES (810);
INSERT INTO {{schema}}_numbers (n) VALUES (811);
INSERT INTO {{schema}}_numbers (n) VALUES (812);
INSERT INTO {{schema}}_numbers (n) VALUES (813);
INSERT INTO {{schema}}_numbers (n) VALUES (814);
INSERT INTO {{schema}}_numbers (n) VALUES (815);
INSERT INTO {{schema}}_numbers (n) VALUES (816);
INSERT INTO {{schema}}_numbers (n) VALUES (817);
INSERT INTO {{schema}}_numbers (n) VALUES (818);
INSERT INTO {{schema}}_numbers (n) VALUES (819);
INSERT INTO {{schema}}_numbers (n) VALUES (820);
INSERT INTO {{schema}}_numbers (n) VALUES (821);
INSERT INTO {{schema}}_numbers (n) VALUES (822);
INSERT INTO {{schema}}_numbers (n) VALUES (823);
INSERT INTO {{schema}}_numbers (n) VALUES (824);
INSERT INTO {{schema}}_numbers (n) VALUES (825);
INSERT INTO {{schema}}_numbers (n) VALUES (826);
INSERT INTO {{schema}}_numbers (n) VALUES (827);
INSERT INTO {{schema}}_numbers (n) VALUES (828);
INSERT INTO {{schema}}_numbers (n) VALUES (829);
INSERT INTO {{schema}}_numbers (n) VALUES (830);
INSERT INTO {{schema}}_numbers (n) VALUES (831);
INSERT INTO {{schema}}_numbers (n) VALUES (832);
INSERT INTO {{schema}}_numbers (n) VALUES (833);
INSERT INTO {{schema}}_numbers (n) VALUES (834);
INSERT INTO {{schema}}_numbers (n) VALUES (835);
INSERT INTO {{schema}}_numbers (n) VALUES (836);
INSERT INTO {{schema}}_numbers (n) VALUES (837);
INSERT INTO {{schema}}_numbers (n) VALUES (838);
INSERT INTO {{schema}}_numbers (n) VALUES (839);
INSERT INTO {{schema}}_numbers (n) VALUES (840);
INSERT INTO {{schema}}_numbers (n) VALUES (841);
INSERT INTO {{schema}}_numbers (n) VALUES (842);
INSERT INTO {{schema}}_numbers (n) VALUES (843);
INSERT INTO {{schema}}_numbers (n) VALUES (844);
INSERT INTO {{schema}}_numbers (n) VALUES (845);
INSERT INTO {{schema}}_numbers (n) VALUES (846);
INSERT INTO {{schema}}_numbers (n) VALUES (847);
INSERT INTO {{schema}}_numbers (n) VALUES (848);
INSERT INTO {{schema}}_numbers (n) VALUES (849);
INSERT INTO {{schema}}_numbers (n) VALUES (850);
INSERT INTO {{schema}}_numbers (n) VALUES (851);
INSERT INTO {{schema}}_numbers (n) VALUES (852);
INSERT INTO {{schema}}_numbers (n) VALUES (853);
INSERT INTO {{schema}}_numbers (n) VALUES (854);
INSERT INTO {{schema}}_numbers (n) VALUES (855);
INSERT INTO {{schema}}_numbers (n) VALUES (856);
INSERT INTO {{schema}}_numbers (n) VALUES (857);
INSERT INTO {{schema}}_numbers (n) VALUES (858);
INSERT INTO {{schema}}_numbers (n) VALUES (859);
INSERT INTO {{schema}}_numbers (n) VALUES (860);
INSERT INTO {{schema}}_numbers (n) VALUES (861);
INSERT INTO {{schema}}_numbers (n) VALUES (862);
INSERT INTO {{schema}}_numbers (n) VALUES (863);
INSERT INTO {{schema}}_numbers (n) VALUES (864);
INSERT INTO {{schema}}_numbers (n) VALUES (865);
INSERT INTO {{schema}}_numbers (n) VALUES (866);
INSERT INTO {{schema}}_numbers (n) VALUES (867);
INSERT INTO {{schema}}_numbers (n) VALUES (868);
INSERT INTO {{schema}}_numbers (n) VALUES (869);
INSERT INTO {{schema}}_numbers (n) VALUES (870);
INSERT INTO {{schema}}_numbers (n) VALUES (871);
INSERT INTO {{schema}}_numbers (n) VALUES (872);
INSERT INTO {{schema}}_numbers (n) VALUES (873);
INSERT INTO {{schema}}_numbers (n) VALUES (874);
INSERT INTO {{schema}}_numbers (n) VALUES (875);
INSERT INTO {{schema}}_numbers (n) VALUES (876);
INSERT INTO {{schema}}_numbers (n) VALUES (877);
INSERT INTO {{schema}}_numbers (n) VALUES (878);
INSERT INTO {{schema}}_numbers (n) VALUES (879);
INSERT INTO {{schema}}_numbers (n) VALUES (880);
INSERT INTO {{schema}}_numbers (n) VALUES (881);
INSERT INTO {{schema}}_numbers (n) VALUES (882);
INSERT INTO {{schema}}_numbers (n) VALUES (883);
INSERT INTO {{schema}}_numbers (n) VALUES (884);
INSERT INTO {{schema}}_numbers (n) VALUES (885);
INSERT INTO {{schema}}_numbers (n) VALUES (886);
INSERT INTO {{schema}}_numbers (n) VALUES (887);
INSERT INTO {{schema}}_numbers (n) VALUES (888);
INSERT INTO {{schema}}_numbers (n) VALUES (889);
INSERT INTO {{schema}}_numbers (n) VALUES (890);
INSERT INTO {{schema}}_numbers (n) VALUES (891);
INSERT INTO {{schema}}_numbers (n) VALUES (892);
INSERT INTO {{schema}}_numbers (n) VALUES (893);
INSERT INTO {{schema}}_numbers (n) VALUES (894);
INSERT INTO {{schema}}_numbers (n) VALUES (895);
INSERT INTO {{schema}}_numbers (n) VALUES (896);
INSERT INTO {{schema}}_numbers (n) VALUES (897);
INSERT INTO {{schema}}_numbers (n) VALUES (898);
INSERT INTO {{schema}}_numbers (n) VALUES (899);
INSERT INTO {{schema}}_numbers (n) VALUES (900);
INSERT INTO {{schema}}_numbers (n) VALUES (901);
INSERT INTO {{schema}}_numbers (n) VALUES (902);
INSERT INTO {{schema}}_numbers (n) VALUES (903);
INSERT INTO {{schema}}_numbers (n) VALUES (904);
INSERT INTO {{schema}}_numbers (n) VALUES (905);
INSERT INTO {{schema}}_numbers (n) VALUES (906);
INSERT INTO {{schema}}_numbers (n) VALUES (907);
INSERT INTO {{schema}}_numbers (n) VALUES (908);
INSERT INTO {{schema}}_numbers (n) VALUES (909);
INSERT INTO {{schema}}_numbers (n) VALUES (910);
INSERT INTO {{schema}}_numbers (n) VALUES (911);
INSERT INTO {{schema}}_numbers (n) VALUES (912);
INSERT INTO {{schema}}_numbers (n) VALUES (913);
INSERT INTO {{schema}}_numbers (n) VALUES (914);
INSERT INTO {{schema}}_numbers (n) VALUES (915);
INSERT INTO {{schema}}_numbers (n) VALUES (916);
INSERT INTO {{schema}}_numbers (n) VALUES (917);
INSERT INTO {{schema}}_numbers (n) VALUES (918);
INSERT INTO {{schema}}_numbers (n) VALUES (919);
INSERT INTO {{schema}}_numbers (n) VALUES (920);
INSERT INTO {{schema}}_numbers (n) VALUES (921);
INSERT INTO {{schema}}_numbers (n) VALUES (922);
INSERT INTO {{schema}}_numbers (n) VALUES (923);
INSERT INTO {{schema}}_numbers (n) VALUES (924);
INSERT INTO {{schema}}_numbers (n) VALUES (925);
INSERT INTO {{schema}}_numbers (n) VALUES (926);
INSERT INTO {{schema}}_numbers (n) VALUES (927);
INSERT INTO {{schema}}_numbers (n) VALUES (928);
INSERT INTO {{schema}}_numbers (n) VALUES (929);
INSERT INTO {{schema}}_numbers (n) VALUES (930);
INSERT INTO {{schema}}_numbers (n) VALUES (931);
INSERT INTO {{schema}}_numbers (n) VALUES (932);
INSERT INTO {{schema}}_numbers (n) VALUES (933);
INSERT INTO {{schema}}_numbers (n) VALUES (934);
INSERT INTO {{schema}}_numbers (n) VALUES (935);
INSERT INTO {{schema}}_numbers (n) VALUES (936);
INSERT INTO {{schema}}_numbers (n) VALUES (937);
INSERT INTO {{schema}}_numbers (n) VALUES (938);
INSERT INTO {{schema}}_numbers (n) VALUES (939);
INSERT INTO {{schema}}_numbers (n) VALUES (940);
INSERT INTO {{schema}}_numbers (n) VALUES (941);
INSERT INTO {{schema}}_numbers (n) VALUES (942);
INSERT INTO {{schema}}_numbers (n) VALUES (943);
INSERT INTO {{schema}}_numbers (n) VALUES (944);
INSERT INTO {{schema}}_numbers (n) VALUES (945);
INSERT INTO {{schema}}_numbers (n) VALUES (946);
INSERT INTO {{schema}}_numbers (n) VALUES (947);
INSERT INTO {{schema}}_numbers (n) VALUES (948);
INSERT INTO {{schema}}_numbers (n) VALUES (949);
INSERT INTO {{schema}}_numbers (n) VALUES (950);
INSERT INTO {{schema}}_numbers (n) VALUES (951);
INSERT INTO {{schema}}_numbers (n) VALUES (952);
INSERT INTO {{schema}}_numbers (n) VALUES (953);
INSERT INTO {{schema}}_numbers (n) VALUES (954);
INSERT INTO {{schema}}_numbers (n) VALUES (955);
INSERT INTO {{schema}}_numbers (n) VALUES (956);
INSERT INTO {{schema}}_numbers (n) VALUES (957);
INSERT INTO {{schema}}_numbers (n) VALUES (958);
INSERT INTO {{schema}}_numbers (n) VALUES (959);
INSERT INTO {{schema}}_numbers (n) VALUES (960);
INSERT INTO {{schema}}_numbers (n) VALUES (961);
INSERT INTO {{schema}}_numbers (n) VALUES (962);
INSERT INTO {{schema}}_numbers (n) VALUES (963);
INSERT INTO {{schema}}_numbers (n) VALUES (964);
INSERT INTO {{schema}}_numbers (n) VALUES (965);
INSERT INTO {{schema}}_numbers (n) VALUES (966);
INSERT INTO {{schema}}_numbers (n) VALUES (967);
INSERT INTO {{schema}}_numbers (n) VALUES (968);
INSERT INTO {{schema}}_numbers (n) VALUES (969);
INSERT INTO {{schema}}_numbers (n) VALUES (970);
INSERT INTO {{schema}}_numbers (n) VALUES (971);
INSERT INTO {{schema}}_numbers (n) VALUES (972);
INSERT INTO {{schema}}_numbers (n) VALUES (973);
INSERT INTO {{schema}}_numbers (n) VALUES (974);
INSERT INTO {{schema}}_numbers (n) VALUES (975);
INSERT INTO {{schema}}_numbers (n) VALUES (976);
INSERT INTO {{schema}}_numbers (n) VALUES (977);
INSERT INTO {{schema}}_numbers (n) VALUES (978);
INSERT INTO {{schema}}_numbers (n) VALUES (979);
INSERT INTO {{schema}}_numbers (n) VALUES (980);
INSERT INTO {{schema}}_numbers (n) VALUES (981);
INSERT INTO {{schema}}_numbers (n) VALUES (982);
INSERT INTO {{schema}}_numbers (n) VALUES (983);
INSERT INTO {{schema}}_numbers (n) VALUES (984);
INSERT INTO {{schema}}_numbers (n) VALUES (985);
INSERT INTO {{schema}}_numbers (n) VALUES (986);
INSERT INTO {{schema}}_numbers (n) VALUES (987);
INSERT INTO {{schema}}_numbers (n) VALUES (988);
INSERT INTO {{schema}}_numbers (n) VALUES (989);
INSERT INTO {{schema}}_numbers (n) VALUES (990);
INSERT INTO {{schema}}_numbers (n) VALUES (991);
INSERT INTO {{schema}}_numbers (n) VALUES (992);
INSERT INTO {{schema}}_numbers (n) VALUES (993);
INSERT INTO {{schema}}_numbers (n) VALUES (994);
INSERT INTO {{schema}}_numbers (n) VALUES (995);
INSERT INTO {{schema}}_numbers (n) VALUES (996);
INSERT INTO {{schema}}_numbers (n) VALUES (997);
INSERT INTO {{schema}}_numbers (n) VALUES (998);
INSERT INTO {{schema}}_numbers (n) VALUES (999);
