--MS SQL Maestro Professional 12.9.0.2
------------------------------------------
--Host     : hornet.apharmony.local
--Database : TMPL0




-- Data from table "jsharmony.CR"
SET IDENTITY_INSERT jsharmony.CR ON
GO

BEGIN TRANSACTION
GO
INSERT INTO jsharmony.CR (CR_ID, CR_SEQ, CR_STS, CR_Name, CR_Desc, CR_CODE, CR_ATTRIB, CR_SNotes) VALUES (5, 0, N'ACTIVE', N'C*', N'All Users', NULL, NULL, NULL);
INSERT INTO jsharmony.CR (CR_ID, CR_SEQ, CR_STS, CR_Name, CR_Desc, CR_CODE, CR_ATTRIB, CR_SNotes) VALUES (12, 3, N'ACTIVE', N'CADMIN', N'Client Admin', NULL, NULL, NULL);
INSERT INTO jsharmony.CR (CR_ID, CR_SEQ, CR_STS, CR_Name, CR_Desc, CR_CODE, CR_ATTRIB, CR_SNotes) VALUES (6, 5, N'ACTIVE', N'CFULL', N'Internal Menus', NULL, NULL, NULL);
INSERT INTO jsharmony.CR (CR_ID, CR_SEQ, CR_STS, CR_Name, CR_Desc, CR_CODE, CR_ATTRIB, CR_SNotes) VALUES (7, 4, N'ACTIVE', N'CINOUT', N'Checkin/Checkout', NULL, NULL, NULL);
INSERT INTO jsharmony.CR (CR_ID, CR_SEQ, CR_STS, CR_Name, CR_Desc, CR_CODE, CR_ATTRIB, CR_SNotes) VALUES (9, 1, N'ACTIVE', N'CL1', N'Client Level 1', NULL, NULL, NULL);
INSERT INTO jsharmony.CR (CR_ID, CR_SEQ, CR_STS, CR_Name, CR_Desc, CR_CODE, CR_ATTRIB, CR_SNotes) VALUES (11, 2, N'ACTIVE', N'CMGR', N'Client Manager', NULL, NULL, NULL);
INSERT INTO jsharmony.CR (CR_ID, CR_SEQ, CR_STS, CR_Name, CR_Desc, CR_CODE, CR_ATTRIB, CR_SNotes) VALUES (1, 1, N'ACTIVE', N'CSYSADMIN', N'Administrator', NULL, NULL, NULL);
INSERT INTO jsharmony.CR (CR_ID, CR_SEQ, CR_STS, CR_Name, CR_Desc, CR_CODE, CR_ATTRIB, CR_SNotes) VALUES (10, 1, N'ACTIVE', N'CUSER', N'Client User', NULL, NULL, NULL);
INSERT INTO jsharmony.CR (CR_ID, CR_SEQ, CR_STS, CR_Name, CR_Desc, CR_CODE, CR_ATTRIB, CR_SNotes) VALUES (2, 2, N'ACTIVE', N'CX_B', N'Browse', NULL, NULL, NULL);
INSERT INTO jsharmony.CR (CR_ID, CR_SEQ, CR_STS, CR_Name, CR_Desc, CR_CODE, CR_ATTRIB, CR_SNotes) VALUES (3, 3, N'ACTIVE', N'CX_X', N'Entry / Update', NULL, NULL, NULL);
COMMIT
GO

SET IDENTITY_INSERT jsharmony.CR OFF
GO



-- Data from table "jsharmony.DUAL"
SET IDENTITY_INSERT jsharmony.DUAL ON
GO

BEGIN TRANSACTION
GO
INSERT INTO jsharmony.DUAL ([DUMMY], DUAL_IDENT, DUAL_BIGINT, DUAL_NVARCHAR50) VALUES (N'X', 1, NULL, NULL);
COMMIT
GO

SET IDENTITY_INSERT jsharmony.DUAL OFF
GO



-- Data from table "jsharmony.HP"
SET IDENTITY_INSERT jsharmony.HP ON
GO

BEGIN TRANSACTION
GO
INSERT INTO jsharmony.HP (HP_CODE, HP_Desc, HP_ID) VALUES ('C', N'Customer', 15);
INSERT INTO jsharmony.HP (HP_CODE, HP_Desc, HP_ID) VALUES ('E_B', N'Item - Charges', 11);
INSERT INTO jsharmony.HP (HP_CODE, HP_Desc, HP_ID) VALUES ('E_H', N'Item - History', 3);
INSERT INTO jsharmony.HP (HP_CODE, HP_Desc, HP_ID) VALUES ('E_O', N'Item - Overview', 9);
INSERT INTO jsharmony.HP (HP_CODE, HP_Desc, HP_ID) VALUES ('E_POPUP_E', N'New Item (from E)', 6);
INSERT INTO jsharmony.HP (HP_CODE, HP_Desc, HP_ID) VALUES ('E_POPUP_SQ', N'New Item (from SQ)', 5);
INSERT INTO jsharmony.HP (HP_CODE, HP_Desc, HP_ID) VALUES ('EL_C_REL', N'Items - Related', 7);
INSERT INTO jsharmony.HP (HP_CODE, HP_Desc, HP_ID) VALUES ('SCHED', N'Scheduling', 14);
INSERT INTO jsharmony.HP (HP_CODE, HP_Desc, HP_ID) VALUES ('SQ_A', N'Series - Assemblies', 13);
INSERT INTO jsharmony.HP (HP_CODE, HP_Desc, HP_ID) VALUES ('SQ_B', N'Series - Charges', 12);
INSERT INTO jsharmony.HP (HP_CODE, HP_Desc, HP_ID) VALUES ('SQ_H', N'Series - History', 4);
INSERT INTO jsharmony.HP (HP_CODE, HP_Desc, HP_ID) VALUES ('SQ_O', N'Series - Overview', 10);
INSERT INTO jsharmony.HP (HP_CODE, HP_Desc, HP_ID) VALUES ('TO_H', N'Order History', 2);
INSERT INTO jsharmony.HP (HP_CODE, HP_Desc, HP_ID) VALUES ('TOL_C_REL', N'Orders - Related', 8);
INSERT INTO jsharmony.HP (HP_CODE, HP_Desc, HP_ID) VALUES ('TOLSEL_SEL', N'Items Selector', 1);
COMMIT
GO

SET IDENTITY_INSERT jsharmony.HP OFF
GO



-- Data from table "jsharmony.NUMBERS"
BEGIN TRANSACTION
GO
INSERT INTO jsharmony.NUMBERS (N) VALUES (1);
INSERT INTO jsharmony.NUMBERS (N) VALUES (2);
INSERT INTO jsharmony.NUMBERS (N) VALUES (3);
INSERT INTO jsharmony.NUMBERS (N) VALUES (4);
INSERT INTO jsharmony.NUMBERS (N) VALUES (5);
INSERT INTO jsharmony.NUMBERS (N) VALUES (6);
INSERT INTO jsharmony.NUMBERS (N) VALUES (7);
INSERT INTO jsharmony.NUMBERS (N) VALUES (8);
INSERT INTO jsharmony.NUMBERS (N) VALUES (9);
INSERT INTO jsharmony.NUMBERS (N) VALUES (10);
INSERT INTO jsharmony.NUMBERS (N) VALUES (11);
INSERT INTO jsharmony.NUMBERS (N) VALUES (12);
INSERT INTO jsharmony.NUMBERS (N) VALUES (13);
INSERT INTO jsharmony.NUMBERS (N) VALUES (14);
INSERT INTO jsharmony.NUMBERS (N) VALUES (15);
INSERT INTO jsharmony.NUMBERS (N) VALUES (16);
INSERT INTO jsharmony.NUMBERS (N) VALUES (17);
INSERT INTO jsharmony.NUMBERS (N) VALUES (18);
INSERT INTO jsharmony.NUMBERS (N) VALUES (19);
INSERT INTO jsharmony.NUMBERS (N) VALUES (20);
INSERT INTO jsharmony.NUMBERS (N) VALUES (21);
INSERT INTO jsharmony.NUMBERS (N) VALUES (22);
INSERT INTO jsharmony.NUMBERS (N) VALUES (23);
INSERT INTO jsharmony.NUMBERS (N) VALUES (24);
INSERT INTO jsharmony.NUMBERS (N) VALUES (25);
INSERT INTO jsharmony.NUMBERS (N) VALUES (26);
INSERT INTO jsharmony.NUMBERS (N) VALUES (27);
INSERT INTO jsharmony.NUMBERS (N) VALUES (28);
INSERT INTO jsharmony.NUMBERS (N) VALUES (29);
INSERT INTO jsharmony.NUMBERS (N) VALUES (30);
INSERT INTO jsharmony.NUMBERS (N) VALUES (31);
INSERT INTO jsharmony.NUMBERS (N) VALUES (32);
INSERT INTO jsharmony.NUMBERS (N) VALUES (33);
INSERT INTO jsharmony.NUMBERS (N) VALUES (34);
INSERT INTO jsharmony.NUMBERS (N) VALUES (35);
INSERT INTO jsharmony.NUMBERS (N) VALUES (36);
INSERT INTO jsharmony.NUMBERS (N) VALUES (37);
INSERT INTO jsharmony.NUMBERS (N) VALUES (38);
INSERT INTO jsharmony.NUMBERS (N) VALUES (39);
INSERT INTO jsharmony.NUMBERS (N) VALUES (40);
INSERT INTO jsharmony.NUMBERS (N) VALUES (41);
INSERT INTO jsharmony.NUMBERS (N) VALUES (42);
INSERT INTO jsharmony.NUMBERS (N) VALUES (43);
INSERT INTO jsharmony.NUMBERS (N) VALUES (44);
INSERT INTO jsharmony.NUMBERS (N) VALUES (45);
INSERT INTO jsharmony.NUMBERS (N) VALUES (46);
INSERT INTO jsharmony.NUMBERS (N) VALUES (47);
INSERT INTO jsharmony.NUMBERS (N) VALUES (48);
INSERT INTO jsharmony.NUMBERS (N) VALUES (49);
INSERT INTO jsharmony.NUMBERS (N) VALUES (50);
INSERT INTO jsharmony.NUMBERS (N) VALUES (51);
INSERT INTO jsharmony.NUMBERS (N) VALUES (52);
INSERT INTO jsharmony.NUMBERS (N) VALUES (53);
INSERT INTO jsharmony.NUMBERS (N) VALUES (54);
INSERT INTO jsharmony.NUMBERS (N) VALUES (55);
INSERT INTO jsharmony.NUMBERS (N) VALUES (56);
INSERT INTO jsharmony.NUMBERS (N) VALUES (57);
INSERT INTO jsharmony.NUMBERS (N) VALUES (58);
INSERT INTO jsharmony.NUMBERS (N) VALUES (59);
INSERT INTO jsharmony.NUMBERS (N) VALUES (60);
INSERT INTO jsharmony.NUMBERS (N) VALUES (61);
INSERT INTO jsharmony.NUMBERS (N) VALUES (62);
INSERT INTO jsharmony.NUMBERS (N) VALUES (63);
INSERT INTO jsharmony.NUMBERS (N) VALUES (64);
INSERT INTO jsharmony.NUMBERS (N) VALUES (65);
INSERT INTO jsharmony.NUMBERS (N) VALUES (66);
INSERT INTO jsharmony.NUMBERS (N) VALUES (67);
INSERT INTO jsharmony.NUMBERS (N) VALUES (68);
INSERT INTO jsharmony.NUMBERS (N) VALUES (69);
INSERT INTO jsharmony.NUMBERS (N) VALUES (70);
INSERT INTO jsharmony.NUMBERS (N) VALUES (71);
INSERT INTO jsharmony.NUMBERS (N) VALUES (72);
INSERT INTO jsharmony.NUMBERS (N) VALUES (73);
INSERT INTO jsharmony.NUMBERS (N) VALUES (74);
INSERT INTO jsharmony.NUMBERS (N) VALUES (75);
INSERT INTO jsharmony.NUMBERS (N) VALUES (76);
INSERT INTO jsharmony.NUMBERS (N) VALUES (77);
INSERT INTO jsharmony.NUMBERS (N) VALUES (78);
INSERT INTO jsharmony.NUMBERS (N) VALUES (79);
INSERT INTO jsharmony.NUMBERS (N) VALUES (80);
INSERT INTO jsharmony.NUMBERS (N) VALUES (81);
INSERT INTO jsharmony.NUMBERS (N) VALUES (82);
INSERT INTO jsharmony.NUMBERS (N) VALUES (83);
INSERT INTO jsharmony.NUMBERS (N) VALUES (84);
INSERT INTO jsharmony.NUMBERS (N) VALUES (85);
INSERT INTO jsharmony.NUMBERS (N) VALUES (86);
INSERT INTO jsharmony.NUMBERS (N) VALUES (87);
INSERT INTO jsharmony.NUMBERS (N) VALUES (88);
INSERT INTO jsharmony.NUMBERS (N) VALUES (89);
INSERT INTO jsharmony.NUMBERS (N) VALUES (90);
INSERT INTO jsharmony.NUMBERS (N) VALUES (91);
INSERT INTO jsharmony.NUMBERS (N) VALUES (92);
INSERT INTO jsharmony.NUMBERS (N) VALUES (93);
INSERT INTO jsharmony.NUMBERS (N) VALUES (94);
INSERT INTO jsharmony.NUMBERS (N) VALUES (95);
INSERT INTO jsharmony.NUMBERS (N) VALUES (96);
INSERT INTO jsharmony.NUMBERS (N) VALUES (97);
INSERT INTO jsharmony.NUMBERS (N) VALUES (98);
INSERT INTO jsharmony.NUMBERS (N) VALUES (99);
INSERT INTO jsharmony.NUMBERS (N) VALUES (100);
INSERT INTO jsharmony.NUMBERS (N) VALUES (101);
INSERT INTO jsharmony.NUMBERS (N) VALUES (102);
INSERT INTO jsharmony.NUMBERS (N) VALUES (103);
INSERT INTO jsharmony.NUMBERS (N) VALUES (104);
INSERT INTO jsharmony.NUMBERS (N) VALUES (105);
INSERT INTO jsharmony.NUMBERS (N) VALUES (106);
INSERT INTO jsharmony.NUMBERS (N) VALUES (107);
INSERT INTO jsharmony.NUMBERS (N) VALUES (108);
INSERT INTO jsharmony.NUMBERS (N) VALUES (109);
INSERT INTO jsharmony.NUMBERS (N) VALUES (110);
INSERT INTO jsharmony.NUMBERS (N) VALUES (111);
INSERT INTO jsharmony.NUMBERS (N) VALUES (112);
INSERT INTO jsharmony.NUMBERS (N) VALUES (113);
INSERT INTO jsharmony.NUMBERS (N) VALUES (114);
INSERT INTO jsharmony.NUMBERS (N) VALUES (115);
INSERT INTO jsharmony.NUMBERS (N) VALUES (116);
INSERT INTO jsharmony.NUMBERS (N) VALUES (117);
INSERT INTO jsharmony.NUMBERS (N) VALUES (118);
INSERT INTO jsharmony.NUMBERS (N) VALUES (119);
INSERT INTO jsharmony.NUMBERS (N) VALUES (120);
INSERT INTO jsharmony.NUMBERS (N) VALUES (121);
INSERT INTO jsharmony.NUMBERS (N) VALUES (122);
INSERT INTO jsharmony.NUMBERS (N) VALUES (123);
INSERT INTO jsharmony.NUMBERS (N) VALUES (124);
INSERT INTO jsharmony.NUMBERS (N) VALUES (125);
INSERT INTO jsharmony.NUMBERS (N) VALUES (126);
INSERT INTO jsharmony.NUMBERS (N) VALUES (127);
INSERT INTO jsharmony.NUMBERS (N) VALUES (128);
INSERT INTO jsharmony.NUMBERS (N) VALUES (129);
INSERT INTO jsharmony.NUMBERS (N) VALUES (130);
INSERT INTO jsharmony.NUMBERS (N) VALUES (131);
INSERT INTO jsharmony.NUMBERS (N) VALUES (132);
INSERT INTO jsharmony.NUMBERS (N) VALUES (133);
INSERT INTO jsharmony.NUMBERS (N) VALUES (134);
INSERT INTO jsharmony.NUMBERS (N) VALUES (135);
INSERT INTO jsharmony.NUMBERS (N) VALUES (136);
INSERT INTO jsharmony.NUMBERS (N) VALUES (137);
INSERT INTO jsharmony.NUMBERS (N) VALUES (138);
INSERT INTO jsharmony.NUMBERS (N) VALUES (139);
INSERT INTO jsharmony.NUMBERS (N) VALUES (140);
INSERT INTO jsharmony.NUMBERS (N) VALUES (141);
INSERT INTO jsharmony.NUMBERS (N) VALUES (142);
INSERT INTO jsharmony.NUMBERS (N) VALUES (143);
INSERT INTO jsharmony.NUMBERS (N) VALUES (144);
INSERT INTO jsharmony.NUMBERS (N) VALUES (145);
INSERT INTO jsharmony.NUMBERS (N) VALUES (146);
INSERT INTO jsharmony.NUMBERS (N) VALUES (147);
INSERT INTO jsharmony.NUMBERS (N) VALUES (148);
INSERT INTO jsharmony.NUMBERS (N) VALUES (149);
INSERT INTO jsharmony.NUMBERS (N) VALUES (150);
INSERT INTO jsharmony.NUMBERS (N) VALUES (151);
INSERT INTO jsharmony.NUMBERS (N) VALUES (152);
INSERT INTO jsharmony.NUMBERS (N) VALUES (153);
INSERT INTO jsharmony.NUMBERS (N) VALUES (154);
INSERT INTO jsharmony.NUMBERS (N) VALUES (155);
INSERT INTO jsharmony.NUMBERS (N) VALUES (156);
INSERT INTO jsharmony.NUMBERS (N) VALUES (157);
INSERT INTO jsharmony.NUMBERS (N) VALUES (158);
INSERT INTO jsharmony.NUMBERS (N) VALUES (159);
INSERT INTO jsharmony.NUMBERS (N) VALUES (160);
INSERT INTO jsharmony.NUMBERS (N) VALUES (161);
INSERT INTO jsharmony.NUMBERS (N) VALUES (162);
INSERT INTO jsharmony.NUMBERS (N) VALUES (163);
INSERT INTO jsharmony.NUMBERS (N) VALUES (164);
INSERT INTO jsharmony.NUMBERS (N) VALUES (165);
INSERT INTO jsharmony.NUMBERS (N) VALUES (166);
INSERT INTO jsharmony.NUMBERS (N) VALUES (167);
INSERT INTO jsharmony.NUMBERS (N) VALUES (168);
INSERT INTO jsharmony.NUMBERS (N) VALUES (169);
INSERT INTO jsharmony.NUMBERS (N) VALUES (170);
INSERT INTO jsharmony.NUMBERS (N) VALUES (171);
INSERT INTO jsharmony.NUMBERS (N) VALUES (172);
INSERT INTO jsharmony.NUMBERS (N) VALUES (173);
INSERT INTO jsharmony.NUMBERS (N) VALUES (174);
INSERT INTO jsharmony.NUMBERS (N) VALUES (175);
INSERT INTO jsharmony.NUMBERS (N) VALUES (176);
INSERT INTO jsharmony.NUMBERS (N) VALUES (177);
INSERT INTO jsharmony.NUMBERS (N) VALUES (178);
INSERT INTO jsharmony.NUMBERS (N) VALUES (179);
INSERT INTO jsharmony.NUMBERS (N) VALUES (180);
INSERT INTO jsharmony.NUMBERS (N) VALUES (181);
INSERT INTO jsharmony.NUMBERS (N) VALUES (182);
INSERT INTO jsharmony.NUMBERS (N) VALUES (183);
INSERT INTO jsharmony.NUMBERS (N) VALUES (184);
INSERT INTO jsharmony.NUMBERS (N) VALUES (185);
INSERT INTO jsharmony.NUMBERS (N) VALUES (186);
INSERT INTO jsharmony.NUMBERS (N) VALUES (187);
INSERT INTO jsharmony.NUMBERS (N) VALUES (188);
INSERT INTO jsharmony.NUMBERS (N) VALUES (189);
INSERT INTO jsharmony.NUMBERS (N) VALUES (190);
INSERT INTO jsharmony.NUMBERS (N) VALUES (191);
INSERT INTO jsharmony.NUMBERS (N) VALUES (192);
INSERT INTO jsharmony.NUMBERS (N) VALUES (193);
INSERT INTO jsharmony.NUMBERS (N) VALUES (194);
INSERT INTO jsharmony.NUMBERS (N) VALUES (195);
INSERT INTO jsharmony.NUMBERS (N) VALUES (196);
INSERT INTO jsharmony.NUMBERS (N) VALUES (197);
INSERT INTO jsharmony.NUMBERS (N) VALUES (198);
INSERT INTO jsharmony.NUMBERS (N) VALUES (199);
INSERT INTO jsharmony.NUMBERS (N) VALUES (200);
INSERT INTO jsharmony.NUMBERS (N) VALUES (201);
INSERT INTO jsharmony.NUMBERS (N) VALUES (202);
INSERT INTO jsharmony.NUMBERS (N) VALUES (203);
INSERT INTO jsharmony.NUMBERS (N) VALUES (204);
INSERT INTO jsharmony.NUMBERS (N) VALUES (205);
INSERT INTO jsharmony.NUMBERS (N) VALUES (206);
INSERT INTO jsharmony.NUMBERS (N) VALUES (207);
INSERT INTO jsharmony.NUMBERS (N) VALUES (208);
INSERT INTO jsharmony.NUMBERS (N) VALUES (209);
INSERT INTO jsharmony.NUMBERS (N) VALUES (210);
INSERT INTO jsharmony.NUMBERS (N) VALUES (211);
INSERT INTO jsharmony.NUMBERS (N) VALUES (212);
INSERT INTO jsharmony.NUMBERS (N) VALUES (213);
INSERT INTO jsharmony.NUMBERS (N) VALUES (214);
INSERT INTO jsharmony.NUMBERS (N) VALUES (215);
INSERT INTO jsharmony.NUMBERS (N) VALUES (216);
INSERT INTO jsharmony.NUMBERS (N) VALUES (217);
INSERT INTO jsharmony.NUMBERS (N) VALUES (218);
INSERT INTO jsharmony.NUMBERS (N) VALUES (219);
INSERT INTO jsharmony.NUMBERS (N) VALUES (220);
INSERT INTO jsharmony.NUMBERS (N) VALUES (221);
INSERT INTO jsharmony.NUMBERS (N) VALUES (222);
INSERT INTO jsharmony.NUMBERS (N) VALUES (223);
INSERT INTO jsharmony.NUMBERS (N) VALUES (224);
INSERT INTO jsharmony.NUMBERS (N) VALUES (225);
INSERT INTO jsharmony.NUMBERS (N) VALUES (226);
INSERT INTO jsharmony.NUMBERS (N) VALUES (227);
INSERT INTO jsharmony.NUMBERS (N) VALUES (228);
INSERT INTO jsharmony.NUMBERS (N) VALUES (229);
INSERT INTO jsharmony.NUMBERS (N) VALUES (230);
INSERT INTO jsharmony.NUMBERS (N) VALUES (231);
INSERT INTO jsharmony.NUMBERS (N) VALUES (232);
INSERT INTO jsharmony.NUMBERS (N) VALUES (233);
INSERT INTO jsharmony.NUMBERS (N) VALUES (234);
INSERT INTO jsharmony.NUMBERS (N) VALUES (235);
INSERT INTO jsharmony.NUMBERS (N) VALUES (236);
INSERT INTO jsharmony.NUMBERS (N) VALUES (237);
INSERT INTO jsharmony.NUMBERS (N) VALUES (238);
INSERT INTO jsharmony.NUMBERS (N) VALUES (239);
INSERT INTO jsharmony.NUMBERS (N) VALUES (240);
INSERT INTO jsharmony.NUMBERS (N) VALUES (241);
INSERT INTO jsharmony.NUMBERS (N) VALUES (242);
INSERT INTO jsharmony.NUMBERS (N) VALUES (243);
INSERT INTO jsharmony.NUMBERS (N) VALUES (244);
INSERT INTO jsharmony.NUMBERS (N) VALUES (245);
INSERT INTO jsharmony.NUMBERS (N) VALUES (246);
INSERT INTO jsharmony.NUMBERS (N) VALUES (247);
INSERT INTO jsharmony.NUMBERS (N) VALUES (248);
INSERT INTO jsharmony.NUMBERS (N) VALUES (249);
INSERT INTO jsharmony.NUMBERS (N) VALUES (250);
INSERT INTO jsharmony.NUMBERS (N) VALUES (251);
INSERT INTO jsharmony.NUMBERS (N) VALUES (252);
INSERT INTO jsharmony.NUMBERS (N) VALUES (253);
INSERT INTO jsharmony.NUMBERS (N) VALUES (254);
INSERT INTO jsharmony.NUMBERS (N) VALUES (255);
INSERT INTO jsharmony.NUMBERS (N) VALUES (256);
INSERT INTO jsharmony.NUMBERS (N) VALUES (257);
INSERT INTO jsharmony.NUMBERS (N) VALUES (258);
INSERT INTO jsharmony.NUMBERS (N) VALUES (259);
INSERT INTO jsharmony.NUMBERS (N) VALUES (260);
INSERT INTO jsharmony.NUMBERS (N) VALUES (261);
INSERT INTO jsharmony.NUMBERS (N) VALUES (262);
INSERT INTO jsharmony.NUMBERS (N) VALUES (263);
INSERT INTO jsharmony.NUMBERS (N) VALUES (264);
INSERT INTO jsharmony.NUMBERS (N) VALUES (265);
INSERT INTO jsharmony.NUMBERS (N) VALUES (266);
INSERT INTO jsharmony.NUMBERS (N) VALUES (267);
INSERT INTO jsharmony.NUMBERS (N) VALUES (268);
INSERT INTO jsharmony.NUMBERS (N) VALUES (269);
INSERT INTO jsharmony.NUMBERS (N) VALUES (270);
INSERT INTO jsharmony.NUMBERS (N) VALUES (271);
INSERT INTO jsharmony.NUMBERS (N) VALUES (272);
INSERT INTO jsharmony.NUMBERS (N) VALUES (273);
INSERT INTO jsharmony.NUMBERS (N) VALUES (274);
INSERT INTO jsharmony.NUMBERS (N) VALUES (275);
INSERT INTO jsharmony.NUMBERS (N) VALUES (276);
INSERT INTO jsharmony.NUMBERS (N) VALUES (277);
INSERT INTO jsharmony.NUMBERS (N) VALUES (278);
INSERT INTO jsharmony.NUMBERS (N) VALUES (279);
INSERT INTO jsharmony.NUMBERS (N) VALUES (280);
INSERT INTO jsharmony.NUMBERS (N) VALUES (281);
INSERT INTO jsharmony.NUMBERS (N) VALUES (282);
INSERT INTO jsharmony.NUMBERS (N) VALUES (283);
INSERT INTO jsharmony.NUMBERS (N) VALUES (284);
INSERT INTO jsharmony.NUMBERS (N) VALUES (285);
INSERT INTO jsharmony.NUMBERS (N) VALUES (286);
INSERT INTO jsharmony.NUMBERS (N) VALUES (287);
INSERT INTO jsharmony.NUMBERS (N) VALUES (288);
INSERT INTO jsharmony.NUMBERS (N) VALUES (289);
INSERT INTO jsharmony.NUMBERS (N) VALUES (290);
INSERT INTO jsharmony.NUMBERS (N) VALUES (291);
INSERT INTO jsharmony.NUMBERS (N) VALUES (292);
INSERT INTO jsharmony.NUMBERS (N) VALUES (293);
INSERT INTO jsharmony.NUMBERS (N) VALUES (294);
INSERT INTO jsharmony.NUMBERS (N) VALUES (295);
INSERT INTO jsharmony.NUMBERS (N) VALUES (296);
INSERT INTO jsharmony.NUMBERS (N) VALUES (297);
INSERT INTO jsharmony.NUMBERS (N) VALUES (298);
INSERT INTO jsharmony.NUMBERS (N) VALUES (299);
INSERT INTO jsharmony.NUMBERS (N) VALUES (300);
INSERT INTO jsharmony.NUMBERS (N) VALUES (301);
INSERT INTO jsharmony.NUMBERS (N) VALUES (302);
INSERT INTO jsharmony.NUMBERS (N) VALUES (303);
INSERT INTO jsharmony.NUMBERS (N) VALUES (304);
INSERT INTO jsharmony.NUMBERS (N) VALUES (305);
INSERT INTO jsharmony.NUMBERS (N) VALUES (306);
INSERT INTO jsharmony.NUMBERS (N) VALUES (307);
INSERT INTO jsharmony.NUMBERS (N) VALUES (308);
INSERT INTO jsharmony.NUMBERS (N) VALUES (309);
INSERT INTO jsharmony.NUMBERS (N) VALUES (310);
INSERT INTO jsharmony.NUMBERS (N) VALUES (311);
INSERT INTO jsharmony.NUMBERS (N) VALUES (312);
INSERT INTO jsharmony.NUMBERS (N) VALUES (313);
INSERT INTO jsharmony.NUMBERS (N) VALUES (314);
INSERT INTO jsharmony.NUMBERS (N) VALUES (315);
INSERT INTO jsharmony.NUMBERS (N) VALUES (316);
INSERT INTO jsharmony.NUMBERS (N) VALUES (317);
INSERT INTO jsharmony.NUMBERS (N) VALUES (318);
INSERT INTO jsharmony.NUMBERS (N) VALUES (319);
INSERT INTO jsharmony.NUMBERS (N) VALUES (320);
INSERT INTO jsharmony.NUMBERS (N) VALUES (321);
INSERT INTO jsharmony.NUMBERS (N) VALUES (322);
INSERT INTO jsharmony.NUMBERS (N) VALUES (323);
INSERT INTO jsharmony.NUMBERS (N) VALUES (324);
INSERT INTO jsharmony.NUMBERS (N) VALUES (325);
INSERT INTO jsharmony.NUMBERS (N) VALUES (326);
INSERT INTO jsharmony.NUMBERS (N) VALUES (327);
INSERT INTO jsharmony.NUMBERS (N) VALUES (328);
INSERT INTO jsharmony.NUMBERS (N) VALUES (329);
INSERT INTO jsharmony.NUMBERS (N) VALUES (330);
INSERT INTO jsharmony.NUMBERS (N) VALUES (331);
INSERT INTO jsharmony.NUMBERS (N) VALUES (332);
INSERT INTO jsharmony.NUMBERS (N) VALUES (333);
INSERT INTO jsharmony.NUMBERS (N) VALUES (334);
INSERT INTO jsharmony.NUMBERS (N) VALUES (335);
INSERT INTO jsharmony.NUMBERS (N) VALUES (336);
INSERT INTO jsharmony.NUMBERS (N) VALUES (337);
INSERT INTO jsharmony.NUMBERS (N) VALUES (338);
INSERT INTO jsharmony.NUMBERS (N) VALUES (339);
INSERT INTO jsharmony.NUMBERS (N) VALUES (340);
INSERT INTO jsharmony.NUMBERS (N) VALUES (341);
INSERT INTO jsharmony.NUMBERS (N) VALUES (342);
INSERT INTO jsharmony.NUMBERS (N) VALUES (343);
INSERT INTO jsharmony.NUMBERS (N) VALUES (344);
INSERT INTO jsharmony.NUMBERS (N) VALUES (345);
INSERT INTO jsharmony.NUMBERS (N) VALUES (346);
INSERT INTO jsharmony.NUMBERS (N) VALUES (347);
INSERT INTO jsharmony.NUMBERS (N) VALUES (348);
INSERT INTO jsharmony.NUMBERS (N) VALUES (349);
INSERT INTO jsharmony.NUMBERS (N) VALUES (350);
INSERT INTO jsharmony.NUMBERS (N) VALUES (351);
INSERT INTO jsharmony.NUMBERS (N) VALUES (352);
INSERT INTO jsharmony.NUMBERS (N) VALUES (353);
INSERT INTO jsharmony.NUMBERS (N) VALUES (354);
INSERT INTO jsharmony.NUMBERS (N) VALUES (355);
INSERT INTO jsharmony.NUMBERS (N) VALUES (356);
INSERT INTO jsharmony.NUMBERS (N) VALUES (357);
INSERT INTO jsharmony.NUMBERS (N) VALUES (358);
INSERT INTO jsharmony.NUMBERS (N) VALUES (359);
INSERT INTO jsharmony.NUMBERS (N) VALUES (360);
INSERT INTO jsharmony.NUMBERS (N) VALUES (361);
INSERT INTO jsharmony.NUMBERS (N) VALUES (362);
INSERT INTO jsharmony.NUMBERS (N) VALUES (363);
INSERT INTO jsharmony.NUMBERS (N) VALUES (364);
INSERT INTO jsharmony.NUMBERS (N) VALUES (365);
INSERT INTO jsharmony.NUMBERS (N) VALUES (366);
INSERT INTO jsharmony.NUMBERS (N) VALUES (367);
INSERT INTO jsharmony.NUMBERS (N) VALUES (368);
INSERT INTO jsharmony.NUMBERS (N) VALUES (369);
INSERT INTO jsharmony.NUMBERS (N) VALUES (370);
INSERT INTO jsharmony.NUMBERS (N) VALUES (371);
INSERT INTO jsharmony.NUMBERS (N) VALUES (372);
INSERT INTO jsharmony.NUMBERS (N) VALUES (373);
INSERT INTO jsharmony.NUMBERS (N) VALUES (374);
INSERT INTO jsharmony.NUMBERS (N) VALUES (375);
INSERT INTO jsharmony.NUMBERS (N) VALUES (376);
INSERT INTO jsharmony.NUMBERS (N) VALUES (377);
INSERT INTO jsharmony.NUMBERS (N) VALUES (378);
INSERT INTO jsharmony.NUMBERS (N) VALUES (379);
INSERT INTO jsharmony.NUMBERS (N) VALUES (380);
INSERT INTO jsharmony.NUMBERS (N) VALUES (381);
INSERT INTO jsharmony.NUMBERS (N) VALUES (382);
INSERT INTO jsharmony.NUMBERS (N) VALUES (383);
INSERT INTO jsharmony.NUMBERS (N) VALUES (384);
INSERT INTO jsharmony.NUMBERS (N) VALUES (385);
INSERT INTO jsharmony.NUMBERS (N) VALUES (386);
INSERT INTO jsharmony.NUMBERS (N) VALUES (387);
INSERT INTO jsharmony.NUMBERS (N) VALUES (388);
INSERT INTO jsharmony.NUMBERS (N) VALUES (389);
INSERT INTO jsharmony.NUMBERS (N) VALUES (390);
INSERT INTO jsharmony.NUMBERS (N) VALUES (391);
INSERT INTO jsharmony.NUMBERS (N) VALUES (392);
INSERT INTO jsharmony.NUMBERS (N) VALUES (393);
INSERT INTO jsharmony.NUMBERS (N) VALUES (394);
INSERT INTO jsharmony.NUMBERS (N) VALUES (395);
INSERT INTO jsharmony.NUMBERS (N) VALUES (396);
INSERT INTO jsharmony.NUMBERS (N) VALUES (397);
INSERT INTO jsharmony.NUMBERS (N) VALUES (398);
INSERT INTO jsharmony.NUMBERS (N) VALUES (399);
INSERT INTO jsharmony.NUMBERS (N) VALUES (400);
INSERT INTO jsharmony.NUMBERS (N) VALUES (401);
INSERT INTO jsharmony.NUMBERS (N) VALUES (402);
INSERT INTO jsharmony.NUMBERS (N) VALUES (403);
INSERT INTO jsharmony.NUMBERS (N) VALUES (404);
INSERT INTO jsharmony.NUMBERS (N) VALUES (405);
INSERT INTO jsharmony.NUMBERS (N) VALUES (406);
INSERT INTO jsharmony.NUMBERS (N) VALUES (407);
INSERT INTO jsharmony.NUMBERS (N) VALUES (408);
INSERT INTO jsharmony.NUMBERS (N) VALUES (409);
INSERT INTO jsharmony.NUMBERS (N) VALUES (410);
INSERT INTO jsharmony.NUMBERS (N) VALUES (411);
INSERT INTO jsharmony.NUMBERS (N) VALUES (412);
INSERT INTO jsharmony.NUMBERS (N) VALUES (413);
INSERT INTO jsharmony.NUMBERS (N) VALUES (414);
INSERT INTO jsharmony.NUMBERS (N) VALUES (415);
INSERT INTO jsharmony.NUMBERS (N) VALUES (416);
INSERT INTO jsharmony.NUMBERS (N) VALUES (417);
INSERT INTO jsharmony.NUMBERS (N) VALUES (418);
INSERT INTO jsharmony.NUMBERS (N) VALUES (419);
INSERT INTO jsharmony.NUMBERS (N) VALUES (420);
INSERT INTO jsharmony.NUMBERS (N) VALUES (421);
INSERT INTO jsharmony.NUMBERS (N) VALUES (422);
INSERT INTO jsharmony.NUMBERS (N) VALUES (423);
INSERT INTO jsharmony.NUMBERS (N) VALUES (424);
INSERT INTO jsharmony.NUMBERS (N) VALUES (425);
INSERT INTO jsharmony.NUMBERS (N) VALUES (426);
INSERT INTO jsharmony.NUMBERS (N) VALUES (427);
INSERT INTO jsharmony.NUMBERS (N) VALUES (428);
INSERT INTO jsharmony.NUMBERS (N) VALUES (429);
INSERT INTO jsharmony.NUMBERS (N) VALUES (430);
INSERT INTO jsharmony.NUMBERS (N) VALUES (431);
INSERT INTO jsharmony.NUMBERS (N) VALUES (432);
INSERT INTO jsharmony.NUMBERS (N) VALUES (433);
INSERT INTO jsharmony.NUMBERS (N) VALUES (434);
INSERT INTO jsharmony.NUMBERS (N) VALUES (435);
INSERT INTO jsharmony.NUMBERS (N) VALUES (436);
INSERT INTO jsharmony.NUMBERS (N) VALUES (437);
INSERT INTO jsharmony.NUMBERS (N) VALUES (438);
INSERT INTO jsharmony.NUMBERS (N) VALUES (439);
INSERT INTO jsharmony.NUMBERS (N) VALUES (440);
INSERT INTO jsharmony.NUMBERS (N) VALUES (441);
INSERT INTO jsharmony.NUMBERS (N) VALUES (442);
INSERT INTO jsharmony.NUMBERS (N) VALUES (443);
INSERT INTO jsharmony.NUMBERS (N) VALUES (444);
INSERT INTO jsharmony.NUMBERS (N) VALUES (445);
INSERT INTO jsharmony.NUMBERS (N) VALUES (446);
INSERT INTO jsharmony.NUMBERS (N) VALUES (447);
INSERT INTO jsharmony.NUMBERS (N) VALUES (448);
INSERT INTO jsharmony.NUMBERS (N) VALUES (449);
INSERT INTO jsharmony.NUMBERS (N) VALUES (450);
INSERT INTO jsharmony.NUMBERS (N) VALUES (451);
INSERT INTO jsharmony.NUMBERS (N) VALUES (452);
INSERT INTO jsharmony.NUMBERS (N) VALUES (453);
INSERT INTO jsharmony.NUMBERS (N) VALUES (454);
INSERT INTO jsharmony.NUMBERS (N) VALUES (455);
INSERT INTO jsharmony.NUMBERS (N) VALUES (456);
INSERT INTO jsharmony.NUMBERS (N) VALUES (457);
INSERT INTO jsharmony.NUMBERS (N) VALUES (458);
INSERT INTO jsharmony.NUMBERS (N) VALUES (459);
INSERT INTO jsharmony.NUMBERS (N) VALUES (460);
INSERT INTO jsharmony.NUMBERS (N) VALUES (461);
INSERT INTO jsharmony.NUMBERS (N) VALUES (462);
INSERT INTO jsharmony.NUMBERS (N) VALUES (463);
INSERT INTO jsharmony.NUMBERS (N) VALUES (464);
INSERT INTO jsharmony.NUMBERS (N) VALUES (465);
INSERT INTO jsharmony.NUMBERS (N) VALUES (466);
INSERT INTO jsharmony.NUMBERS (N) VALUES (467);
INSERT INTO jsharmony.NUMBERS (N) VALUES (468);
INSERT INTO jsharmony.NUMBERS (N) VALUES (469);
INSERT INTO jsharmony.NUMBERS (N) VALUES (470);
INSERT INTO jsharmony.NUMBERS (N) VALUES (471);
INSERT INTO jsharmony.NUMBERS (N) VALUES (472);
INSERT INTO jsharmony.NUMBERS (N) VALUES (473);
INSERT INTO jsharmony.NUMBERS (N) VALUES (474);
INSERT INTO jsharmony.NUMBERS (N) VALUES (475);
INSERT INTO jsharmony.NUMBERS (N) VALUES (476);
INSERT INTO jsharmony.NUMBERS (N) VALUES (477);
INSERT INTO jsharmony.NUMBERS (N) VALUES (478);
INSERT INTO jsharmony.NUMBERS (N) VALUES (479);
INSERT INTO jsharmony.NUMBERS (N) VALUES (480);
INSERT INTO jsharmony.NUMBERS (N) VALUES (481);
INSERT INTO jsharmony.NUMBERS (N) VALUES (482);
INSERT INTO jsharmony.NUMBERS (N) VALUES (483);
INSERT INTO jsharmony.NUMBERS (N) VALUES (484);
INSERT INTO jsharmony.NUMBERS (N) VALUES (485);
INSERT INTO jsharmony.NUMBERS (N) VALUES (486);
INSERT INTO jsharmony.NUMBERS (N) VALUES (487);
INSERT INTO jsharmony.NUMBERS (N) VALUES (488);
INSERT INTO jsharmony.NUMBERS (N) VALUES (489);
INSERT INTO jsharmony.NUMBERS (N) VALUES (490);
INSERT INTO jsharmony.NUMBERS (N) VALUES (491);
INSERT INTO jsharmony.NUMBERS (N) VALUES (492);
INSERT INTO jsharmony.NUMBERS (N) VALUES (493);
INSERT INTO jsharmony.NUMBERS (N) VALUES (494);
INSERT INTO jsharmony.NUMBERS (N) VALUES (495);
INSERT INTO jsharmony.NUMBERS (N) VALUES (496);
INSERT INTO jsharmony.NUMBERS (N) VALUES (497);
INSERT INTO jsharmony.NUMBERS (N) VALUES (498);
INSERT INTO jsharmony.NUMBERS (N) VALUES (499);
INSERT INTO jsharmony.NUMBERS (N) VALUES (500);
COMMIT
GO
BEGIN TRANSACTION
GO
INSERT INTO jsharmony.NUMBERS (N) VALUES (501);
INSERT INTO jsharmony.NUMBERS (N) VALUES (502);
INSERT INTO jsharmony.NUMBERS (N) VALUES (503);
INSERT INTO jsharmony.NUMBERS (N) VALUES (504);
INSERT INTO jsharmony.NUMBERS (N) VALUES (505);
INSERT INTO jsharmony.NUMBERS (N) VALUES (506);
INSERT INTO jsharmony.NUMBERS (N) VALUES (507);
INSERT INTO jsharmony.NUMBERS (N) VALUES (508);
INSERT INTO jsharmony.NUMBERS (N) VALUES (509);
INSERT INTO jsharmony.NUMBERS (N) VALUES (510);
INSERT INTO jsharmony.NUMBERS (N) VALUES (511);
INSERT INTO jsharmony.NUMBERS (N) VALUES (512);
INSERT INTO jsharmony.NUMBERS (N) VALUES (513);
INSERT INTO jsharmony.NUMBERS (N) VALUES (514);
INSERT INTO jsharmony.NUMBERS (N) VALUES (515);
INSERT INTO jsharmony.NUMBERS (N) VALUES (516);
INSERT INTO jsharmony.NUMBERS (N) VALUES (517);
INSERT INTO jsharmony.NUMBERS (N) VALUES (518);
INSERT INTO jsharmony.NUMBERS (N) VALUES (519);
INSERT INTO jsharmony.NUMBERS (N) VALUES (520);
INSERT INTO jsharmony.NUMBERS (N) VALUES (521);
INSERT INTO jsharmony.NUMBERS (N) VALUES (522);
INSERT INTO jsharmony.NUMBERS (N) VALUES (523);
INSERT INTO jsharmony.NUMBERS (N) VALUES (524);
INSERT INTO jsharmony.NUMBERS (N) VALUES (525);
INSERT INTO jsharmony.NUMBERS (N) VALUES (526);
INSERT INTO jsharmony.NUMBERS (N) VALUES (527);
INSERT INTO jsharmony.NUMBERS (N) VALUES (528);
INSERT INTO jsharmony.NUMBERS (N) VALUES (529);
INSERT INTO jsharmony.NUMBERS (N) VALUES (530);
INSERT INTO jsharmony.NUMBERS (N) VALUES (531);
INSERT INTO jsharmony.NUMBERS (N) VALUES (532);
INSERT INTO jsharmony.NUMBERS (N) VALUES (533);
INSERT INTO jsharmony.NUMBERS (N) VALUES (534);
INSERT INTO jsharmony.NUMBERS (N) VALUES (535);
INSERT INTO jsharmony.NUMBERS (N) VALUES (536);
INSERT INTO jsharmony.NUMBERS (N) VALUES (537);
INSERT INTO jsharmony.NUMBERS (N) VALUES (538);
INSERT INTO jsharmony.NUMBERS (N) VALUES (539);
INSERT INTO jsharmony.NUMBERS (N) VALUES (540);
INSERT INTO jsharmony.NUMBERS (N) VALUES (541);
INSERT INTO jsharmony.NUMBERS (N) VALUES (542);
INSERT INTO jsharmony.NUMBERS (N) VALUES (543);
INSERT INTO jsharmony.NUMBERS (N) VALUES (544);
INSERT INTO jsharmony.NUMBERS (N) VALUES (545);
INSERT INTO jsharmony.NUMBERS (N) VALUES (546);
INSERT INTO jsharmony.NUMBERS (N) VALUES (547);
INSERT INTO jsharmony.NUMBERS (N) VALUES (548);
INSERT INTO jsharmony.NUMBERS (N) VALUES (549);
INSERT INTO jsharmony.NUMBERS (N) VALUES (550);
INSERT INTO jsharmony.NUMBERS (N) VALUES (551);
INSERT INTO jsharmony.NUMBERS (N) VALUES (552);
INSERT INTO jsharmony.NUMBERS (N) VALUES (553);
INSERT INTO jsharmony.NUMBERS (N) VALUES (554);
INSERT INTO jsharmony.NUMBERS (N) VALUES (555);
INSERT INTO jsharmony.NUMBERS (N) VALUES (556);
INSERT INTO jsharmony.NUMBERS (N) VALUES (557);
INSERT INTO jsharmony.NUMBERS (N) VALUES (558);
INSERT INTO jsharmony.NUMBERS (N) VALUES (559);
INSERT INTO jsharmony.NUMBERS (N) VALUES (560);
INSERT INTO jsharmony.NUMBERS (N) VALUES (561);
INSERT INTO jsharmony.NUMBERS (N) VALUES (562);
INSERT INTO jsharmony.NUMBERS (N) VALUES (563);
INSERT INTO jsharmony.NUMBERS (N) VALUES (564);
INSERT INTO jsharmony.NUMBERS (N) VALUES (565);
INSERT INTO jsharmony.NUMBERS (N) VALUES (566);
INSERT INTO jsharmony.NUMBERS (N) VALUES (567);
INSERT INTO jsharmony.NUMBERS (N) VALUES (568);
INSERT INTO jsharmony.NUMBERS (N) VALUES (569);
INSERT INTO jsharmony.NUMBERS (N) VALUES (570);
INSERT INTO jsharmony.NUMBERS (N) VALUES (571);
INSERT INTO jsharmony.NUMBERS (N) VALUES (572);
INSERT INTO jsharmony.NUMBERS (N) VALUES (573);
INSERT INTO jsharmony.NUMBERS (N) VALUES (574);
INSERT INTO jsharmony.NUMBERS (N) VALUES (575);
INSERT INTO jsharmony.NUMBERS (N) VALUES (576);
INSERT INTO jsharmony.NUMBERS (N) VALUES (577);
INSERT INTO jsharmony.NUMBERS (N) VALUES (578);
INSERT INTO jsharmony.NUMBERS (N) VALUES (579);
INSERT INTO jsharmony.NUMBERS (N) VALUES (580);
INSERT INTO jsharmony.NUMBERS (N) VALUES (581);
INSERT INTO jsharmony.NUMBERS (N) VALUES (582);
INSERT INTO jsharmony.NUMBERS (N) VALUES (583);
INSERT INTO jsharmony.NUMBERS (N) VALUES (584);
INSERT INTO jsharmony.NUMBERS (N) VALUES (585);
INSERT INTO jsharmony.NUMBERS (N) VALUES (586);
INSERT INTO jsharmony.NUMBERS (N) VALUES (587);
INSERT INTO jsharmony.NUMBERS (N) VALUES (588);
INSERT INTO jsharmony.NUMBERS (N) VALUES (589);
INSERT INTO jsharmony.NUMBERS (N) VALUES (590);
INSERT INTO jsharmony.NUMBERS (N) VALUES (591);
INSERT INTO jsharmony.NUMBERS (N) VALUES (592);
INSERT INTO jsharmony.NUMBERS (N) VALUES (593);
INSERT INTO jsharmony.NUMBERS (N) VALUES (594);
INSERT INTO jsharmony.NUMBERS (N) VALUES (595);
INSERT INTO jsharmony.NUMBERS (N) VALUES (596);
INSERT INTO jsharmony.NUMBERS (N) VALUES (597);
INSERT INTO jsharmony.NUMBERS (N) VALUES (598);
INSERT INTO jsharmony.NUMBERS (N) VALUES (599);
INSERT INTO jsharmony.NUMBERS (N) VALUES (600);
INSERT INTO jsharmony.NUMBERS (N) VALUES (601);
INSERT INTO jsharmony.NUMBERS (N) VALUES (602);
INSERT INTO jsharmony.NUMBERS (N) VALUES (603);
INSERT INTO jsharmony.NUMBERS (N) VALUES (604);
INSERT INTO jsharmony.NUMBERS (N) VALUES (605);
INSERT INTO jsharmony.NUMBERS (N) VALUES (606);
INSERT INTO jsharmony.NUMBERS (N) VALUES (607);
INSERT INTO jsharmony.NUMBERS (N) VALUES (608);
INSERT INTO jsharmony.NUMBERS (N) VALUES (609);
INSERT INTO jsharmony.NUMBERS (N) VALUES (610);
INSERT INTO jsharmony.NUMBERS (N) VALUES (611);
INSERT INTO jsharmony.NUMBERS (N) VALUES (612);
INSERT INTO jsharmony.NUMBERS (N) VALUES (613);
INSERT INTO jsharmony.NUMBERS (N) VALUES (614);
INSERT INTO jsharmony.NUMBERS (N) VALUES (615);
INSERT INTO jsharmony.NUMBERS (N) VALUES (616);
INSERT INTO jsharmony.NUMBERS (N) VALUES (617);
INSERT INTO jsharmony.NUMBERS (N) VALUES (618);
INSERT INTO jsharmony.NUMBERS (N) VALUES (619);
INSERT INTO jsharmony.NUMBERS (N) VALUES (620);
INSERT INTO jsharmony.NUMBERS (N) VALUES (621);
INSERT INTO jsharmony.NUMBERS (N) VALUES (622);
INSERT INTO jsharmony.NUMBERS (N) VALUES (623);
INSERT INTO jsharmony.NUMBERS (N) VALUES (624);
INSERT INTO jsharmony.NUMBERS (N) VALUES (625);
INSERT INTO jsharmony.NUMBERS (N) VALUES (626);
INSERT INTO jsharmony.NUMBERS (N) VALUES (627);
INSERT INTO jsharmony.NUMBERS (N) VALUES (628);
INSERT INTO jsharmony.NUMBERS (N) VALUES (629);
INSERT INTO jsharmony.NUMBERS (N) VALUES (630);
INSERT INTO jsharmony.NUMBERS (N) VALUES (631);
INSERT INTO jsharmony.NUMBERS (N) VALUES (632);
INSERT INTO jsharmony.NUMBERS (N) VALUES (633);
INSERT INTO jsharmony.NUMBERS (N) VALUES (634);
INSERT INTO jsharmony.NUMBERS (N) VALUES (635);
INSERT INTO jsharmony.NUMBERS (N) VALUES (636);
INSERT INTO jsharmony.NUMBERS (N) VALUES (637);
INSERT INTO jsharmony.NUMBERS (N) VALUES (638);
INSERT INTO jsharmony.NUMBERS (N) VALUES (639);
INSERT INTO jsharmony.NUMBERS (N) VALUES (640);
INSERT INTO jsharmony.NUMBERS (N) VALUES (641);
INSERT INTO jsharmony.NUMBERS (N) VALUES (642);
INSERT INTO jsharmony.NUMBERS (N) VALUES (643);
INSERT INTO jsharmony.NUMBERS (N) VALUES (644);
INSERT INTO jsharmony.NUMBERS (N) VALUES (645);
INSERT INTO jsharmony.NUMBERS (N) VALUES (646);
INSERT INTO jsharmony.NUMBERS (N) VALUES (647);
INSERT INTO jsharmony.NUMBERS (N) VALUES (648);
INSERT INTO jsharmony.NUMBERS (N) VALUES (649);
INSERT INTO jsharmony.NUMBERS (N) VALUES (650);
INSERT INTO jsharmony.NUMBERS (N) VALUES (651);
INSERT INTO jsharmony.NUMBERS (N) VALUES (652);
INSERT INTO jsharmony.NUMBERS (N) VALUES (653);
INSERT INTO jsharmony.NUMBERS (N) VALUES (654);
INSERT INTO jsharmony.NUMBERS (N) VALUES (655);
INSERT INTO jsharmony.NUMBERS (N) VALUES (656);
INSERT INTO jsharmony.NUMBERS (N) VALUES (657);
INSERT INTO jsharmony.NUMBERS (N) VALUES (658);
INSERT INTO jsharmony.NUMBERS (N) VALUES (659);
INSERT INTO jsharmony.NUMBERS (N) VALUES (660);
INSERT INTO jsharmony.NUMBERS (N) VALUES (661);
INSERT INTO jsharmony.NUMBERS (N) VALUES (662);
INSERT INTO jsharmony.NUMBERS (N) VALUES (663);
INSERT INTO jsharmony.NUMBERS (N) VALUES (664);
INSERT INTO jsharmony.NUMBERS (N) VALUES (665);
INSERT INTO jsharmony.NUMBERS (N) VALUES (666);
INSERT INTO jsharmony.NUMBERS (N) VALUES (667);
INSERT INTO jsharmony.NUMBERS (N) VALUES (668);
INSERT INTO jsharmony.NUMBERS (N) VALUES (669);
INSERT INTO jsharmony.NUMBERS (N) VALUES (670);
INSERT INTO jsharmony.NUMBERS (N) VALUES (671);
INSERT INTO jsharmony.NUMBERS (N) VALUES (672);
INSERT INTO jsharmony.NUMBERS (N) VALUES (673);
INSERT INTO jsharmony.NUMBERS (N) VALUES (674);
INSERT INTO jsharmony.NUMBERS (N) VALUES (675);
INSERT INTO jsharmony.NUMBERS (N) VALUES (676);
INSERT INTO jsharmony.NUMBERS (N) VALUES (677);
INSERT INTO jsharmony.NUMBERS (N) VALUES (678);
INSERT INTO jsharmony.NUMBERS (N) VALUES (679);
INSERT INTO jsharmony.NUMBERS (N) VALUES (680);
INSERT INTO jsharmony.NUMBERS (N) VALUES (681);
INSERT INTO jsharmony.NUMBERS (N) VALUES (682);
INSERT INTO jsharmony.NUMBERS (N) VALUES (683);
INSERT INTO jsharmony.NUMBERS (N) VALUES (684);
INSERT INTO jsharmony.NUMBERS (N) VALUES (685);
INSERT INTO jsharmony.NUMBERS (N) VALUES (686);
INSERT INTO jsharmony.NUMBERS (N) VALUES (687);
INSERT INTO jsharmony.NUMBERS (N) VALUES (688);
INSERT INTO jsharmony.NUMBERS (N) VALUES (689);
INSERT INTO jsharmony.NUMBERS (N) VALUES (690);
INSERT INTO jsharmony.NUMBERS (N) VALUES (691);
INSERT INTO jsharmony.NUMBERS (N) VALUES (692);
INSERT INTO jsharmony.NUMBERS (N) VALUES (693);
INSERT INTO jsharmony.NUMBERS (N) VALUES (694);
INSERT INTO jsharmony.NUMBERS (N) VALUES (695);
INSERT INTO jsharmony.NUMBERS (N) VALUES (696);
INSERT INTO jsharmony.NUMBERS (N) VALUES (697);
INSERT INTO jsharmony.NUMBERS (N) VALUES (698);
INSERT INTO jsharmony.NUMBERS (N) VALUES (699);
INSERT INTO jsharmony.NUMBERS (N) VALUES (700);
INSERT INTO jsharmony.NUMBERS (N) VALUES (701);
INSERT INTO jsharmony.NUMBERS (N) VALUES (702);
INSERT INTO jsharmony.NUMBERS (N) VALUES (703);
INSERT INTO jsharmony.NUMBERS (N) VALUES (704);
INSERT INTO jsharmony.NUMBERS (N) VALUES (705);
INSERT INTO jsharmony.NUMBERS (N) VALUES (706);
INSERT INTO jsharmony.NUMBERS (N) VALUES (707);
INSERT INTO jsharmony.NUMBERS (N) VALUES (708);
INSERT INTO jsharmony.NUMBERS (N) VALUES (709);
INSERT INTO jsharmony.NUMBERS (N) VALUES (710);
INSERT INTO jsharmony.NUMBERS (N) VALUES (711);
INSERT INTO jsharmony.NUMBERS (N) VALUES (712);
INSERT INTO jsharmony.NUMBERS (N) VALUES (713);
INSERT INTO jsharmony.NUMBERS (N) VALUES (714);
INSERT INTO jsharmony.NUMBERS (N) VALUES (715);
INSERT INTO jsharmony.NUMBERS (N) VALUES (716);
INSERT INTO jsharmony.NUMBERS (N) VALUES (717);
INSERT INTO jsharmony.NUMBERS (N) VALUES (718);
INSERT INTO jsharmony.NUMBERS (N) VALUES (719);
INSERT INTO jsharmony.NUMBERS (N) VALUES (720);
INSERT INTO jsharmony.NUMBERS (N) VALUES (721);
INSERT INTO jsharmony.NUMBERS (N) VALUES (722);
INSERT INTO jsharmony.NUMBERS (N) VALUES (723);
INSERT INTO jsharmony.NUMBERS (N) VALUES (724);
INSERT INTO jsharmony.NUMBERS (N) VALUES (725);
INSERT INTO jsharmony.NUMBERS (N) VALUES (726);
INSERT INTO jsharmony.NUMBERS (N) VALUES (727);
INSERT INTO jsharmony.NUMBERS (N) VALUES (728);
INSERT INTO jsharmony.NUMBERS (N) VALUES (729);
INSERT INTO jsharmony.NUMBERS (N) VALUES (730);
INSERT INTO jsharmony.NUMBERS (N) VALUES (731);
INSERT INTO jsharmony.NUMBERS (N) VALUES (732);
INSERT INTO jsharmony.NUMBERS (N) VALUES (733);
INSERT INTO jsharmony.NUMBERS (N) VALUES (734);
INSERT INTO jsharmony.NUMBERS (N) VALUES (735);
INSERT INTO jsharmony.NUMBERS (N) VALUES (736);
INSERT INTO jsharmony.NUMBERS (N) VALUES (737);
INSERT INTO jsharmony.NUMBERS (N) VALUES (738);
INSERT INTO jsharmony.NUMBERS (N) VALUES (739);
INSERT INTO jsharmony.NUMBERS (N) VALUES (740);
INSERT INTO jsharmony.NUMBERS (N) VALUES (741);
INSERT INTO jsharmony.NUMBERS (N) VALUES (742);
INSERT INTO jsharmony.NUMBERS (N) VALUES (743);
INSERT INTO jsharmony.NUMBERS (N) VALUES (744);
INSERT INTO jsharmony.NUMBERS (N) VALUES (745);
INSERT INTO jsharmony.NUMBERS (N) VALUES (746);
INSERT INTO jsharmony.NUMBERS (N) VALUES (747);
INSERT INTO jsharmony.NUMBERS (N) VALUES (748);
INSERT INTO jsharmony.NUMBERS (N) VALUES (749);
INSERT INTO jsharmony.NUMBERS (N) VALUES (750);
INSERT INTO jsharmony.NUMBERS (N) VALUES (751);
INSERT INTO jsharmony.NUMBERS (N) VALUES (752);
INSERT INTO jsharmony.NUMBERS (N) VALUES (753);
INSERT INTO jsharmony.NUMBERS (N) VALUES (754);
INSERT INTO jsharmony.NUMBERS (N) VALUES (755);
INSERT INTO jsharmony.NUMBERS (N) VALUES (756);
INSERT INTO jsharmony.NUMBERS (N) VALUES (757);
INSERT INTO jsharmony.NUMBERS (N) VALUES (758);
INSERT INTO jsharmony.NUMBERS (N) VALUES (759);
INSERT INTO jsharmony.NUMBERS (N) VALUES (760);
INSERT INTO jsharmony.NUMBERS (N) VALUES (761);
INSERT INTO jsharmony.NUMBERS (N) VALUES (762);
INSERT INTO jsharmony.NUMBERS (N) VALUES (763);
INSERT INTO jsharmony.NUMBERS (N) VALUES (764);
INSERT INTO jsharmony.NUMBERS (N) VALUES (765);
INSERT INTO jsharmony.NUMBERS (N) VALUES (766);
INSERT INTO jsharmony.NUMBERS (N) VALUES (767);
INSERT INTO jsharmony.NUMBERS (N) VALUES (768);
INSERT INTO jsharmony.NUMBERS (N) VALUES (769);
INSERT INTO jsharmony.NUMBERS (N) VALUES (770);
INSERT INTO jsharmony.NUMBERS (N) VALUES (771);
INSERT INTO jsharmony.NUMBERS (N) VALUES (772);
INSERT INTO jsharmony.NUMBERS (N) VALUES (773);
INSERT INTO jsharmony.NUMBERS (N) VALUES (774);
INSERT INTO jsharmony.NUMBERS (N) VALUES (775);
INSERT INTO jsharmony.NUMBERS (N) VALUES (776);
INSERT INTO jsharmony.NUMBERS (N) VALUES (777);
INSERT INTO jsharmony.NUMBERS (N) VALUES (778);
INSERT INTO jsharmony.NUMBERS (N) VALUES (779);
INSERT INTO jsharmony.NUMBERS (N) VALUES (780);
INSERT INTO jsharmony.NUMBERS (N) VALUES (781);
INSERT INTO jsharmony.NUMBERS (N) VALUES (782);
INSERT INTO jsharmony.NUMBERS (N) VALUES (783);
INSERT INTO jsharmony.NUMBERS (N) VALUES (784);
INSERT INTO jsharmony.NUMBERS (N) VALUES (785);
INSERT INTO jsharmony.NUMBERS (N) VALUES (786);
INSERT INTO jsharmony.NUMBERS (N) VALUES (787);
INSERT INTO jsharmony.NUMBERS (N) VALUES (788);
INSERT INTO jsharmony.NUMBERS (N) VALUES (789);
INSERT INTO jsharmony.NUMBERS (N) VALUES (790);
INSERT INTO jsharmony.NUMBERS (N) VALUES (791);
INSERT INTO jsharmony.NUMBERS (N) VALUES (792);
INSERT INTO jsharmony.NUMBERS (N) VALUES (793);
INSERT INTO jsharmony.NUMBERS (N) VALUES (794);
INSERT INTO jsharmony.NUMBERS (N) VALUES (795);
INSERT INTO jsharmony.NUMBERS (N) VALUES (796);
INSERT INTO jsharmony.NUMBERS (N) VALUES (797);
INSERT INTO jsharmony.NUMBERS (N) VALUES (798);
INSERT INTO jsharmony.NUMBERS (N) VALUES (799);
INSERT INTO jsharmony.NUMBERS (N) VALUES (800);
INSERT INTO jsharmony.NUMBERS (N) VALUES (801);
INSERT INTO jsharmony.NUMBERS (N) VALUES (802);
INSERT INTO jsharmony.NUMBERS (N) VALUES (803);
INSERT INTO jsharmony.NUMBERS (N) VALUES (804);
INSERT INTO jsharmony.NUMBERS (N) VALUES (805);
INSERT INTO jsharmony.NUMBERS (N) VALUES (806);
INSERT INTO jsharmony.NUMBERS (N) VALUES (807);
INSERT INTO jsharmony.NUMBERS (N) VALUES (808);
INSERT INTO jsharmony.NUMBERS (N) VALUES (809);
INSERT INTO jsharmony.NUMBERS (N) VALUES (810);
INSERT INTO jsharmony.NUMBERS (N) VALUES (811);
INSERT INTO jsharmony.NUMBERS (N) VALUES (812);
INSERT INTO jsharmony.NUMBERS (N) VALUES (813);
INSERT INTO jsharmony.NUMBERS (N) VALUES (814);
INSERT INTO jsharmony.NUMBERS (N) VALUES (815);
INSERT INTO jsharmony.NUMBERS (N) VALUES (816);
INSERT INTO jsharmony.NUMBERS (N) VALUES (817);
INSERT INTO jsharmony.NUMBERS (N) VALUES (818);
INSERT INTO jsharmony.NUMBERS (N) VALUES (819);
INSERT INTO jsharmony.NUMBERS (N) VALUES (820);
INSERT INTO jsharmony.NUMBERS (N) VALUES (821);
INSERT INTO jsharmony.NUMBERS (N) VALUES (822);
INSERT INTO jsharmony.NUMBERS (N) VALUES (823);
INSERT INTO jsharmony.NUMBERS (N) VALUES (824);
INSERT INTO jsharmony.NUMBERS (N) VALUES (825);
INSERT INTO jsharmony.NUMBERS (N) VALUES (826);
INSERT INTO jsharmony.NUMBERS (N) VALUES (827);
INSERT INTO jsharmony.NUMBERS (N) VALUES (828);
INSERT INTO jsharmony.NUMBERS (N) VALUES (829);
INSERT INTO jsharmony.NUMBERS (N) VALUES (830);
INSERT INTO jsharmony.NUMBERS (N) VALUES (831);
INSERT INTO jsharmony.NUMBERS (N) VALUES (832);
INSERT INTO jsharmony.NUMBERS (N) VALUES (833);
INSERT INTO jsharmony.NUMBERS (N) VALUES (834);
INSERT INTO jsharmony.NUMBERS (N) VALUES (835);
INSERT INTO jsharmony.NUMBERS (N) VALUES (836);
INSERT INTO jsharmony.NUMBERS (N) VALUES (837);
INSERT INTO jsharmony.NUMBERS (N) VALUES (838);
INSERT INTO jsharmony.NUMBERS (N) VALUES (839);
INSERT INTO jsharmony.NUMBERS (N) VALUES (840);
INSERT INTO jsharmony.NUMBERS (N) VALUES (841);
INSERT INTO jsharmony.NUMBERS (N) VALUES (842);
INSERT INTO jsharmony.NUMBERS (N) VALUES (843);
INSERT INTO jsharmony.NUMBERS (N) VALUES (844);
INSERT INTO jsharmony.NUMBERS (N) VALUES (845);
INSERT INTO jsharmony.NUMBERS (N) VALUES (846);
INSERT INTO jsharmony.NUMBERS (N) VALUES (847);
INSERT INTO jsharmony.NUMBERS (N) VALUES (848);
INSERT INTO jsharmony.NUMBERS (N) VALUES (849);
INSERT INTO jsharmony.NUMBERS (N) VALUES (850);
INSERT INTO jsharmony.NUMBERS (N) VALUES (851);
INSERT INTO jsharmony.NUMBERS (N) VALUES (852);
INSERT INTO jsharmony.NUMBERS (N) VALUES (853);
INSERT INTO jsharmony.NUMBERS (N) VALUES (854);
INSERT INTO jsharmony.NUMBERS (N) VALUES (855);
INSERT INTO jsharmony.NUMBERS (N) VALUES (856);
INSERT INTO jsharmony.NUMBERS (N) VALUES (857);
INSERT INTO jsharmony.NUMBERS (N) VALUES (858);
INSERT INTO jsharmony.NUMBERS (N) VALUES (859);
INSERT INTO jsharmony.NUMBERS (N) VALUES (860);
INSERT INTO jsharmony.NUMBERS (N) VALUES (861);
INSERT INTO jsharmony.NUMBERS (N) VALUES (862);
INSERT INTO jsharmony.NUMBERS (N) VALUES (863);
INSERT INTO jsharmony.NUMBERS (N) VALUES (864);
INSERT INTO jsharmony.NUMBERS (N) VALUES (865);
INSERT INTO jsharmony.NUMBERS (N) VALUES (866);
INSERT INTO jsharmony.NUMBERS (N) VALUES (867);
INSERT INTO jsharmony.NUMBERS (N) VALUES (868);
INSERT INTO jsharmony.NUMBERS (N) VALUES (869);
INSERT INTO jsharmony.NUMBERS (N) VALUES (870);
INSERT INTO jsharmony.NUMBERS (N) VALUES (871);
INSERT INTO jsharmony.NUMBERS (N) VALUES (872);
INSERT INTO jsharmony.NUMBERS (N) VALUES (873);
INSERT INTO jsharmony.NUMBERS (N) VALUES (874);
INSERT INTO jsharmony.NUMBERS (N) VALUES (875);
INSERT INTO jsharmony.NUMBERS (N) VALUES (876);
INSERT INTO jsharmony.NUMBERS (N) VALUES (877);
INSERT INTO jsharmony.NUMBERS (N) VALUES (878);
INSERT INTO jsharmony.NUMBERS (N) VALUES (879);
INSERT INTO jsharmony.NUMBERS (N) VALUES (880);
INSERT INTO jsharmony.NUMBERS (N) VALUES (881);
INSERT INTO jsharmony.NUMBERS (N) VALUES (882);
INSERT INTO jsharmony.NUMBERS (N) VALUES (883);
INSERT INTO jsharmony.NUMBERS (N) VALUES (884);
INSERT INTO jsharmony.NUMBERS (N) VALUES (885);
INSERT INTO jsharmony.NUMBERS (N) VALUES (886);
INSERT INTO jsharmony.NUMBERS (N) VALUES (887);
INSERT INTO jsharmony.NUMBERS (N) VALUES (888);
INSERT INTO jsharmony.NUMBERS (N) VALUES (889);
INSERT INTO jsharmony.NUMBERS (N) VALUES (890);
INSERT INTO jsharmony.NUMBERS (N) VALUES (891);
INSERT INTO jsharmony.NUMBERS (N) VALUES (892);
INSERT INTO jsharmony.NUMBERS (N) VALUES (893);
INSERT INTO jsharmony.NUMBERS (N) VALUES (894);
INSERT INTO jsharmony.NUMBERS (N) VALUES (895);
INSERT INTO jsharmony.NUMBERS (N) VALUES (896);
INSERT INTO jsharmony.NUMBERS (N) VALUES (897);
INSERT INTO jsharmony.NUMBERS (N) VALUES (898);
INSERT INTO jsharmony.NUMBERS (N) VALUES (899);
INSERT INTO jsharmony.NUMBERS (N) VALUES (900);
INSERT INTO jsharmony.NUMBERS (N) VALUES (901);
INSERT INTO jsharmony.NUMBERS (N) VALUES (902);
INSERT INTO jsharmony.NUMBERS (N) VALUES (903);
INSERT INTO jsharmony.NUMBERS (N) VALUES (904);
INSERT INTO jsharmony.NUMBERS (N) VALUES (905);
INSERT INTO jsharmony.NUMBERS (N) VALUES (906);
INSERT INTO jsharmony.NUMBERS (N) VALUES (907);
INSERT INTO jsharmony.NUMBERS (N) VALUES (908);
INSERT INTO jsharmony.NUMBERS (N) VALUES (909);
INSERT INTO jsharmony.NUMBERS (N) VALUES (910);
INSERT INTO jsharmony.NUMBERS (N) VALUES (911);
INSERT INTO jsharmony.NUMBERS (N) VALUES (912);
INSERT INTO jsharmony.NUMBERS (N) VALUES (913);
INSERT INTO jsharmony.NUMBERS (N) VALUES (914);
INSERT INTO jsharmony.NUMBERS (N) VALUES (915);
INSERT INTO jsharmony.NUMBERS (N) VALUES (916);
INSERT INTO jsharmony.NUMBERS (N) VALUES (917);
INSERT INTO jsharmony.NUMBERS (N) VALUES (918);
INSERT INTO jsharmony.NUMBERS (N) VALUES (919);
INSERT INTO jsharmony.NUMBERS (N) VALUES (920);
INSERT INTO jsharmony.NUMBERS (N) VALUES (921);
INSERT INTO jsharmony.NUMBERS (N) VALUES (922);
INSERT INTO jsharmony.NUMBERS (N) VALUES (923);
INSERT INTO jsharmony.NUMBERS (N) VALUES (924);
INSERT INTO jsharmony.NUMBERS (N) VALUES (925);
INSERT INTO jsharmony.NUMBERS (N) VALUES (926);
INSERT INTO jsharmony.NUMBERS (N) VALUES (927);
INSERT INTO jsharmony.NUMBERS (N) VALUES (928);
INSERT INTO jsharmony.NUMBERS (N) VALUES (929);
INSERT INTO jsharmony.NUMBERS (N) VALUES (930);
INSERT INTO jsharmony.NUMBERS (N) VALUES (931);
INSERT INTO jsharmony.NUMBERS (N) VALUES (932);
INSERT INTO jsharmony.NUMBERS (N) VALUES (933);
INSERT INTO jsharmony.NUMBERS (N) VALUES (934);
INSERT INTO jsharmony.NUMBERS (N) VALUES (935);
INSERT INTO jsharmony.NUMBERS (N) VALUES (936);
INSERT INTO jsharmony.NUMBERS (N) VALUES (937);
INSERT INTO jsharmony.NUMBERS (N) VALUES (938);
INSERT INTO jsharmony.NUMBERS (N) VALUES (939);
INSERT INTO jsharmony.NUMBERS (N) VALUES (940);
INSERT INTO jsharmony.NUMBERS (N) VALUES (941);
INSERT INTO jsharmony.NUMBERS (N) VALUES (942);
INSERT INTO jsharmony.NUMBERS (N) VALUES (943);
INSERT INTO jsharmony.NUMBERS (N) VALUES (944);
INSERT INTO jsharmony.NUMBERS (N) VALUES (945);
INSERT INTO jsharmony.NUMBERS (N) VALUES (946);
INSERT INTO jsharmony.NUMBERS (N) VALUES (947);
INSERT INTO jsharmony.NUMBERS (N) VALUES (948);
INSERT INTO jsharmony.NUMBERS (N) VALUES (949);
INSERT INTO jsharmony.NUMBERS (N) VALUES (950);
INSERT INTO jsharmony.NUMBERS (N) VALUES (951);
INSERT INTO jsharmony.NUMBERS (N) VALUES (952);
INSERT INTO jsharmony.NUMBERS (N) VALUES (953);
INSERT INTO jsharmony.NUMBERS (N) VALUES (954);
INSERT INTO jsharmony.NUMBERS (N) VALUES (955);
INSERT INTO jsharmony.NUMBERS (N) VALUES (956);
INSERT INTO jsharmony.NUMBERS (N) VALUES (957);
INSERT INTO jsharmony.NUMBERS (N) VALUES (958);
INSERT INTO jsharmony.NUMBERS (N) VALUES (959);
INSERT INTO jsharmony.NUMBERS (N) VALUES (960);
INSERT INTO jsharmony.NUMBERS (N) VALUES (961);
INSERT INTO jsharmony.NUMBERS (N) VALUES (962);
INSERT INTO jsharmony.NUMBERS (N) VALUES (963);
INSERT INTO jsharmony.NUMBERS (N) VALUES (964);
INSERT INTO jsharmony.NUMBERS (N) VALUES (965);
INSERT INTO jsharmony.NUMBERS (N) VALUES (966);
INSERT INTO jsharmony.NUMBERS (N) VALUES (967);
INSERT INTO jsharmony.NUMBERS (N) VALUES (968);
INSERT INTO jsharmony.NUMBERS (N) VALUES (969);
INSERT INTO jsharmony.NUMBERS (N) VALUES (970);
INSERT INTO jsharmony.NUMBERS (N) VALUES (971);
INSERT INTO jsharmony.NUMBERS (N) VALUES (972);
INSERT INTO jsharmony.NUMBERS (N) VALUES (973);
INSERT INTO jsharmony.NUMBERS (N) VALUES (974);
INSERT INTO jsharmony.NUMBERS (N) VALUES (975);
INSERT INTO jsharmony.NUMBERS (N) VALUES (976);
INSERT INTO jsharmony.NUMBERS (N) VALUES (977);
INSERT INTO jsharmony.NUMBERS (N) VALUES (978);
INSERT INTO jsharmony.NUMBERS (N) VALUES (979);
INSERT INTO jsharmony.NUMBERS (N) VALUES (980);
INSERT INTO jsharmony.NUMBERS (N) VALUES (981);
INSERT INTO jsharmony.NUMBERS (N) VALUES (982);
INSERT INTO jsharmony.NUMBERS (N) VALUES (983);
INSERT INTO jsharmony.NUMBERS (N) VALUES (984);
INSERT INTO jsharmony.NUMBERS (N) VALUES (985);
INSERT INTO jsharmony.NUMBERS (N) VALUES (986);
INSERT INTO jsharmony.NUMBERS (N) VALUES (987);
INSERT INTO jsharmony.NUMBERS (N) VALUES (988);
INSERT INTO jsharmony.NUMBERS (N) VALUES (989);
INSERT INTO jsharmony.NUMBERS (N) VALUES (990);
INSERT INTO jsharmony.NUMBERS (N) VALUES (991);
INSERT INTO jsharmony.NUMBERS (N) VALUES (992);
INSERT INTO jsharmony.NUMBERS (N) VALUES (993);
INSERT INTO jsharmony.NUMBERS (N) VALUES (994);
INSERT INTO jsharmony.NUMBERS (N) VALUES (995);
INSERT INTO jsharmony.NUMBERS (N) VALUES (996);
INSERT INTO jsharmony.NUMBERS (N) VALUES (997);
INSERT INTO jsharmony.NUMBERS (N) VALUES (998);
INSERT INTO jsharmony.NUMBERS (N) VALUES (999);
COMMIT
GO



-- Data from table "jsharmony.PPD"
SET IDENTITY_INSERT jsharmony.PPD ON
GO

BEGIN TRANSACTION
GO
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'DEVICEURL', N'PRINTBAR', N'Device URL - Bar Code Printer', N'C', NULL, '1', '1', '0', 48, N'2016-11-04 16:23:06.9929061', N'dbo', N'2017-05-09 06:40:51.2129233', N'S200010', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'DEVICEURL', N'PRINTORDER', N'Device URL - Order Printer', N'C', NULL, '1', '1', '0', 50, N'2016-11-04 16:23:31.8684010', N'dbo', N'2016-11-04 16:37:09.8462071', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'DEVICEURL', N'SCAN', N'Device URL - Document Scanner', N'C', NULL, '1', '1', '0', 46, N'2016-11-04 16:22:18.5387234', N'dbo', N'2016-11-04 16:36:44.7365876', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'EMAIL', N'NOTIF_ADMIN', N'Notifications Email - Administrative', N'C', NULL, '1', '0', '0', 18, N'2015-10-25 09:57:49.0276562', N'dbo', N'2015-10-25 09:57:49.0276562', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'EMAIL', N'NOTIF_DAMAGE', N'Notifications Email - Receive Damage', N'C', NULL, '1', '0', '0', 36, N'2015-10-25 09:57:49.0276562', N'dbo', N'2015-10-25 09:57:49.0276562', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'EMAIL', N'NOTIF_FIN', N'Notifications Email - Financial', N'C', NULL, '1', '0', '0', 19, N'2015-10-25 09:57:49.0276562', N'dbo', N'2015-10-25 09:57:49.0276562', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'EMAIL', N'NOTIF_SYS', N'Notifications Email - System', N'C', NULL, '1', '0', '1', 20, N'2015-10-25 09:57:49.0276562', N'dbo', N'2015-10-25 09:57:49.0276562', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'HOUSE', N'ADDR', N'HOUSE Address', N'C', NULL, '1', '0', '0', 21, N'2015-10-25 09:57:49.0276562', N'dbo', N'2015-10-25 09:57:49.0276562', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'HOUSE', N'BPHONE', N'HOUSE Business Phone', N'C', NULL, '1', '0', '0', 22, N'2015-10-25 09:57:49.0276562', N'dbo', N'2015-10-25 09:57:49.0276562', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'HOUSE', N'CITY', N'HOUSE City', N'C', NULL, '1', '0', '0', 23, N'2015-10-25 09:57:49.0276562', N'dbo', N'2015-10-25 09:57:49.0276562', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'HOUSE', N'CONTACT', N'HOUSE Contact', N'C', NULL, '1', '0', '0', 24, N'2015-10-25 09:57:49.0276562', N'dbo', N'2015-10-25 09:57:49.0276562', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'HOUSE', N'EMAIL', N'HOUSE Email', N'C', NULL, '1', '0', '0', 25, N'2015-10-25 09:57:49.0276562', N'dbo', N'2015-10-25 09:57:49.0276562', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'HOUSE', N'FAX', N'HOUSE Fax', N'C', NULL, '1', '0', '0', 26, N'2015-10-25 09:57:49.0276562', N'dbo', N'2015-10-25 09:57:49.0276562', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'HOUSE', N'NAME', N'HOUSE Name', N'C', NULL, '1', '0', '0', 27, N'2015-10-25 09:57:49.0276562', N'dbo', N'2015-10-25 09:57:49.0276562', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'HOUSE', N'STATE', N'HOUSE State', N'C', NULL, '1', '0', '0', 28, N'2015-10-25 09:57:49.0276562', N'dbo', N'2015-10-25 09:57:49.0276562', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'HOUSE', N'ZIP', N'HOUSE ZIP', N'C', NULL, '1', '0', '0', 29, N'2015-10-25 09:57:49.0276562', N'dbo', N'2015-10-25 09:57:49.0276562', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'SCHED', N'ENDTIME', N'End Time HH:MI (military with leading zeroes)', N'C', NULL, '1', '0', '0', 44, N'2016-09-13 13:07:43.7765162', N'dbo', N'2016-09-13 13:09:13.8089245', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'SCHED', N'STARTTIME', N'Start Time HH:MI (military with leading zeroes)', N'C', NULL, '1', '0', '0', 43, N'2016-09-13 13:06:09.3538495', N'dbo', N'2016-09-13 13:15:12.7657054', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'SQL', N'DSCOPE_DCTGR', N'Code Table - Document Types by Scope', N'C', NULL, '0', '0', '1', 59, N'2017-05-23 06:51:14.2346793', N'S200010', N'2017-05-23 07:25:32.4949255', N'S200010', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'SQL', N'GETCID', N'SQL Function - GET_C_ID', N'C', NULL, '0', '0', '1', 57, N'2017-05-22 18:38:50.0414885', N'S200010', N'2017-05-22 18:38:50.0414885', N'S200010', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'SQL', N'GETEID', N'SQL Function - GET_E_ID', N'C', NULL, '0', '0', '1', 58, N'2017-05-22 18:39:15.6797064', N'S200010', N'2017-05-22 18:39:15.6797064', N'S200010', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'SYSTEM', N'CLIENT_SYS_URL', N'Client Portal URL', N'C', NULL, '0', '0', '1', 38, N'2015-10-25 09:57:49.0276562', N'dbo', N'2017-06-18 14:35:15.4742861', N'Red Gate Software  -', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'SYSTEM', N'SRVDAYS', N'Number of days for service', N'N', NULL, '1', '0', '0', 40, N'2015-10-25 09:57:49.0276562', N'dbo', N'2015-10-25 09:57:49.0276562', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'USERS', N'HASH_SEED_C', N'Hash Seed Client Users', N'C', NULL, '0', '0', '1', 31, N'2015-10-25 09:57:49.0276562', N'dbo', N'2015-10-25 09:57:49.0276562', N'dbo', NULL);
INSERT INTO jsharmony.PPD (PPD_PROCESS, PPD_ATTRIB, PPD_DESC, PPD_TYPE, CODENAME, PPD_GPP, PPD_PPP, PPD_XPP, PPD_ID, PPD_ETstmp, PPD_EU, PPD_MTstmp, PPD_MU, PPD_SNotes) VALUES (N'USERS', N'HASH_SEED_S', N'Hash Seed System Users', N'C', NULL, '0', '0', '1', 32, N'2015-10-25 09:57:49.0276562', N'dbo', N'2015-10-25 09:57:49.0276562', N'dbo', NULL);
COMMIT
GO

SET IDENTITY_INSERT jsharmony.PPD OFF
GO



-- Data from table "jsharmony.SF"
SET IDENTITY_INSERT jsharmony.SF ON
GO

BEGIN TRANSACTION
GO
INSERT INTO jsharmony.SF (SF_ID, SF_SEQ, SF_STS, SF_Name, SF_Desc, SF_CODE, SF_ATTRIB, SF_SNotes) VALUES (1, 1, N'ACTIVE', N'TBD', N'TBD', NULL, NULL, NULL);
COMMIT
GO

SET IDENTITY_INSERT jsharmony.SF OFF
GO



-- Data from table "jsharmony.SM"
SET IDENTITY_INSERT jsharmony.SM ON
GO

BEGIN TRANSACTION
GO
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (1, 'S', 1, N'ACTIVE', NULL, N'ADMIN', NULL, N'Admin', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (2, 'C', 2, N'ACTIVE', NULL, N'CLIENT', NULL, N'Customer', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (13, 'S', 170, N'ACTIVE', 1, N'ADMINISTRATION', NULL, N'Administration', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (16, 'C', 200, N'ACTIVE', 2, N'C_DASHBOARD', NULL, N'Dashboard', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (17, 'C', 230, N'ACTIVE', 2, N'C_EQUIPMENT', NULL, N'Equipment', NULL, NULL, 'EL_C_CLIENT', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (18, 'C', 260, N'ACTIVE', 2, N'C_REPORTS', NULL, N'Reports', NULL, NULL, 'REPORTS_CLIENT', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (19, 'C', 270, N'ACTIVE', 2, N'C_ADMINISTRATION', NULL, N'Administration', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (84, 'S', 1780, N'ACTIVE', 170, N'ADMINISTRATION_AUDITTRAIL', NULL, N'Audit Trail', NULL, NULL, 'AUDL', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (85, 'S', 1781, N'ACTIVE', 170, N'ADMINISTRATION_CODETABLES', NULL, N'Code Tables', NULL, NULL, 'GCOD_HL', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (86, 'S', 1782, N'ACTIVE', 170, N'ADMINISTRATION_CODE2TABLES', NULL, N'Code2 Tables', NULL, NULL, 'GCOD2_HL', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (87, 'S', 1783, N'ACTIVE', 170, N'ADMINISTRATION_TEXTMAINTENANCE', NULL, N'Text Maint.', NULL, NULL, 'TXTL', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (88, 'S', 1784, N'ACTIVE', 170, N'ADMINISTRATION_GPARAMETERS', NULL, N'Parameters', NULL, NULL, 'GPPL', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (89, 'S', 1785, N'ACTIVE', 170, N'ADMINISTRATION_PPARAMETERS', NULL, N'User Parameters', NULL, NULL, 'PPPL', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (90, 'S', 1786, N'ACTIVE', 170, N'ADMINISTRATION_HELPMAINTENANCE', NULL, N'Help Maint.', NULL, NULL, 'HL', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (111, 'C', 2000, N'ACTIVE', 200, N'C_DASHBOARD_MAIN', NULL, N'Main', NULL, NULL, 'C_Q_DBDW', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (112, 'C', 2007, N'ACTIVE', 200, N'C_DASHBOARD_DOCUMENTS', NULL, N'Documents', NULL, NULL, 'DL_ALLCC', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (113, 'C', 2008, N'ACTIVE', 200, N'C_DASHBOARD_DOCUMENTS_ALL', NULL, N'Documents ALL', NULL, NULL, 'DL_ALLC', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (114, 'C', 2009, N'ACTIVE', 200, N'C_DASHBOARD_NOTES', NULL, N'Notes', NULL, NULL, 'N_ALL_WCSC', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (115, 'C', 2300, N'ACTIVE', 230, N'C_EQUIPMENT_ELA', NULL, N'Active Equipment', NULL, NULL, 'ELA_CLIENT', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (116, 'C', 2301, N'ACTIVE', 230, N'C_EQUIPMENT_ELC', NULL, N'Not Active Equipment', NULL, NULL, 'ELC_CLIENT', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (117, 'C', 2601, N'ACTIVE', 260, N'C_REPORTS_JOBI', NULL, N'Packing List', NULL, NULL, '_report/JOBI_CLIENT', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (118, 'C', 2700, N'ACTIVE', 270, N'C_ADMINISTRATION_USERS', NULL, N'Cust Users', NULL, NULL, 'CPEL_CLIENT', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (119, 'C', 2701, N'ACTIVE', 270, N'C_ADMINISTRATION_CONTACTS', NULL, N'Contacts', NULL, NULL, 'CTL_C_CLIENT', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (125, 'S', 10, N'ACTIVE', 1, N'DEV', NULL, N'Developer', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (126, 'S', 11, N'ACTIVE', 10, N'DEV_X_SRL', 11, N'User Roles', NULL, NULL, 'X_SRL', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (127, 'S', 12, N'ACTIVE', 10, N'DEV_X_SML', 15, N'Menu Items', NULL, NULL, 'X_SML', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (128, 'S', 13, N'ACTIVE', 10, N'DEV_X_PPDL', 21, N'Parameter Definitions', NULL, NULL, 'X_PPDL', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (129, 'S', 14, N'ACTIVE', 10, N'DEV_X_GPPL', 22, N'G Parameters', NULL, NULL, 'X_GPPL', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (130, 'S', 15, N'ACTIVE', 10, N'DEV_X_XPPL', 23, N'X Parameters', NULL, NULL, 'X_XPPL', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (132, 'S', 16, N'ACTIVE', 10, N'DEV_X_GCOD_HL', 31, N'Code List', NULL, NULL, 'X_GCOD_HL', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (133, 'S', 17, N'ACTIVE', 10, N'DEV_X_GCOD2_HL', 32, N'Code2 List', NULL, NULL, 'X_GCOD2_HL', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (134, 'S', 1700, N'ACTIVE', 170, N'ADMINISTRATION_USERS', NULL, N'System Users', NULL, NULL, 'PEL', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (135, 'S', 18, N'ACTIVE', 10, N'DEV_X_UCOD_HL', 33, N'System Code List', NULL, NULL, 'X_UCOD_HL', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (136, 'S', 19, N'ACTIVE', 10, N'DEV_X_UCOD2_HL', 34, N'System Code2 List', NULL, NULL, 'X_UCOD2_HL', NULL, NULL, NULL);
INSERT INTO jsharmony.SM (SM_ID_AUTO, SM_UTYPE, SM_ID, SM_STS, SM_ID_Parent, SM_Name, SM_Seq, SM_DESC, SM_DESCL, SM_DESCVL, SM_Cmd, SM_Image, SM_SNotes, SM_SubCmd) VALUES (137, 'S', 20, N'ACTIVE', 10, N'DEV_X_CRL', 12, N'CUser Roles', NULL, NULL, 'X_CRL', NULL, NULL, NULL);
COMMIT
GO

SET IDENTITY_INSERT jsharmony.SM OFF
GO



-- Data from table "jsharmony.SR"
SET IDENTITY_INSERT jsharmony.SR ON
GO

BEGIN TRANSACTION
GO
INSERT INTO jsharmony.SR (SR_ID, SR_SEQ, SR_STS, SR_Name, SR_Desc, SR_CODE, SR_ATTRIB, SR_SNotes) VALUES (17, 0, N'ACTIVE', N'*', N'All USers', NULL, NULL, NULL);
INSERT INTO jsharmony.SR (SR_ID, SR_SEQ, SR_STS, SR_Name, SR_Desc, SR_CODE, SR_ATTRIB, SR_SNotes) VALUES (5, 97, N'ACTIVE', N'DADMIN', N'Data Administration', NULL, NULL, NULL);
INSERT INTO jsharmony.SR (SR_ID, SR_SEQ, SR_STS, SR_Name, SR_Desc, SR_CODE, SR_ATTRIB, SR_SNotes) VALUES (33, 99, N'ACTIVE', N'DEV', N'Developer (Restricted)', NULL, NULL, NULL);
INSERT INTO jsharmony.SR (SR_ID, SR_SEQ, SR_STS, SR_Name, SR_Desc, SR_CODE, SR_ATTRIB, SR_SNotes) VALUES (1, 98, N'ACTIVE', N'SYSADMIN', N'System Administration', NULL, NULL, NULL);
INSERT INTO jsharmony.SR (SR_ID, SR_SEQ, SR_STS, SR_Name, SR_Desc, SR_CODE, SR_ATTRIB, SR_SNotes) VALUES (8, 91, N'ACTIVE', N'X_B', N'General Browse', NULL, NULL, NULL);
INSERT INTO jsharmony.SR (SR_ID, SR_SEQ, SR_STS, SR_Name, SR_Desc, SR_CODE, SR_ATTRIB, SR_SNotes) VALUES (15, 92, N'ACTIVE', N'X_X', N'General BIUD', NULL, NULL, NULL);
COMMIT
GO

SET IDENTITY_INSERT jsharmony.SR OFF
GO



-- Data from table "jsharmony.TXT"
SET IDENTITY_INSERT jsharmony.TXT ON
GO

BEGIN TRANSACTION
GO
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'1', N'2', N'TEXT', N'i am here', N'and here and there', NULL, NULL, 1, N'2015-10-25 10:18:24.4424362', 'Red Gate Software  -', N'2017-05-12 08:08:45.7182134', 'S200010');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'LABEL', N'TEMP', N'TEXT', NULL, N'ID#: %%%E_K%%%
', NULL, N'Temporary Item Barcode
%%%E_K%%% ItemID', 2, N'2015-10-25 10:18:24.4424362', 'Red Gate Software  -', N'2016-04-05 08:19:48.5997246', 'Microsoft SQL Server');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'LABEL', N'CAL', N'TEXT', NULL, N'ID#: %%%E_K%%%   By: %%%ECAL_BY%%%
', NULL, N'Label
%%%E_K%%% EquipID, %%%ECAL_BY%%% Cal. Tech, %%%ECAL_DT%%% Cal. Date, %%%NEXT_DT%%% Next Due Date', 3, N'2015-10-25 10:18:24.4424362', 'Red Gate Software  -', N'2016-04-05 08:25:34.3797062', 'S200010');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'EMAIL', N'UPCOMING_DUE', N'HTML', N'Upcoming Item Due', N'<p>Dear <%-data.C[0].CT_NAME%>,<br />
The following charges are due within the next 30 days.</p>

<p>Please visit our website below, .<br />
<a href="<%-data.C[0].PORTAL_URL%>"><%-data.C[0].PORTAL_URL%></a></p>

<p>Thank you for your business.</p>

<p>&nbsp;</p>
', NULL, N'<%-data.C[0].CT_NAME%> Customer Name
<%-data.C[0].PORTAL_URL%> Portal URL
<%=E.E_K%> Eq ID
<%=E.ET_Name%> Eq Type
<%=E.E_Name%> Eq Desc
<%=moment.utc(E.E_CAL_NEXTDt).format(''MM/DD/YYYY'')%> Due Date
<% _.each(data.C[0].E,function(E){ } %>  Eq Listing', 4, N'2015-10-25 10:18:24.4424362', 'Red Gate Software  -', N'2016-04-05 08:28:10.7568127', 'S200010');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'EMAIL', N'RCVD', N'HTML', N'STARTER - Request Received', N'<p>Dear <%-data.C_NAME%>,</p>

<p>Thank you for your order. &nbsp;Your request has been received. &nbsp;Please visit our customer portal to keep track of order status:<br />
<a href="<%-data.PORTAL_URL%>"><%-data.PORTAL_URL%></a></p>

<p>Job ID: <%-data.J_ID%></p>

<p>Sincerely,<br />
&nbsp;</p>
', NULL, N'<%-data.C_NAME%> Customer Name
<%-data.J_ID%> Job ID
<%-data.PORTAL_URL%> Portal URL', 5, N'2015-10-25 10:18:24.4424362', 'Red Gate Software  -', N'2016-04-05 08:22:18.0659088', 'S200010');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'EMAIL', N'RCVD_DAMAGE', N'HTML', N'STARTER - **DAMAGED** Item Received', N'<p>Dear <%-data.C_NAME%>,</p>

<p>We have received your request, however one or more pieces were received damaged. &nbsp;If the gage was already damaged and sent for repair, we will contact you to discuss options. &nbsp;Otherwise, you may need to contact the carrier if the package was insured. &nbsp;Please call us at (XXX) XXX-XXXX for more information.</p>

<p>Job ID: <%-data.J_ID%></p>

<p>Sincerely,<br />
&nbsp;</p>
', NULL, N'<%-data.C_NAME%> Customer Name
<%-data.J_ID%> Job ID
<%-data.PORTAL_URL%> Portal URL', 6, N'2015-10-25 10:18:24.4424362', 'Red Gate Software  -', N'2016-04-05 08:23:15.6933061', 'S200010');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'EMAIL', N'SHIP', N'HTML', N'STARTER - Job Completed', N'<p>Dear <%-data.C_NAME%>,</p>

<p>Your work request has been completed and will be shipped shortly. &nbsp;Below is an overview. &nbsp;Please visit the customer portal for more information.<br />
<a href="<%-data.PORTAL_URL%>"><%-data.PORTAL_URL%></a></p>

<p>Job ID: <%-data.J_ID%></p>

<p><%-data.SRVL%></p>

<p>Sincerely,<br />
&nbsp;</p>
', NULL, N'<%-data.C_NAME%> Customer Name
<%-data.J_ID%> Job ID
<%-data.SRVL%> Service List
<%-data.PORTAL_URL%> Portal URL', 7, N'2015-10-25 10:18:24.4424362', 'Red Gate Software  -', N'2016-04-05 08:24:04.2725473', 'S200010');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'EMAIL', N'RESETPASS', N'HTML', N'STARTER Password Reset', N'<p>Dear <%-data.PE_NAME%>,<br />
<br />
A password reset has been requested on your account. If you did not initiate the request, please contact us at <%-data.SUPPORT_EMAIL%> immediately.<br />
<br />
Please follow the link below to reset your password:<br />
<a href="<%-data.RESET_LINK%>"><%-data.RESET_LINK%></a></p>
', NULL, N'<%-data.PE_NAME%> User Name
<%-data.SUPPORT_EMAIL%> Support Email
<%-data.RESET_LINK%> Reset Link', 8, N'2015-10-25 10:18:24.4580363', 'Red Gate Software  -', N'2015-10-26 09:56:00.0751484', 'Microsoft SQL Server');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'REPORT', N'QUOTE', N'HTML', NULL, N'<p>XXX</p>
', N'BCC', N'Quote Disclaimer', 9, N'2015-10-25 10:18:24.4892341', 'Red Gate Software  -', N'2016-04-05 08:26:06.3758603', 'S200010');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'CMS', N'AGREEMENT', N'HTML', N'STARTER Agreement', N'<p>Agreement <strong>Body 1</strong></p>
', NULL, N'AMBER Agreement', 10, N'2015-10-25 10:18:24.5048356', 'Red Gate Software  -', N'2017-04-01 13:41:07.9403524', 'S200010');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'CMS', N'AGREEMENT_DONE', N'HTML', N'STARTER Agreement Done', N'<p>Thank you for completing sign-up.</p>
', NULL, N'AMBER Agreement Done', 11, N'2015-10-25 10:18:24.5048356', 'Red Gate Software  -', N'2016-04-05 08:21:31.4211023', 'S200010');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'EMAIL', N'QRWINOTIF', N'HTML', N'AMBER - Deferred Inventory Query Notification - Query: #<%-data.QRWI_ID%>', N'<p>Dear <%-data.PE_NAME%>,</p>

<p>The following items defined in Query #<%-data.QRWI_ID%> were received after&nbsp;&nbsp;<%-data.QRWI_FROM_TSTMP_FMT%>&nbsp;:<br />
<%-data.ITEM_LIST%><br />
<br />
Sincerely<br />
Amber</p>
', NULL, N'Deferred Inventory Query Notification', 19, N'2016-07-28 15:00:33.1203044', 'Microsoft SQL Server', N'2016-07-29 07:11:14.9325032', 'S200010');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'EMAIL', N'ERROREMAIL', N'HTML', N'Error in   <%-data.PROCESS%>   Process', N'Error identified in  <%-data.PROCESS%>   Process:

<%-data.TXTADMIN%>
', N'andrzejusa@gmail.com', NULL, 20, N'2016-09-27 14:32:55.9710895', 'Microsoft SQL Server', N'2016-09-27 14:32:55.9710895', 'Microsoft SQL Server');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'EMAIL', N'CONFIRM', N'HTML', N'<%-data.TO_SCHED_FMT%> <%-data.TO_TYPE_TXT%> Order Confirmation - Affordable Moving Co.
', N'<p><%-data.C_NAME%></p>

<p><%-data.TO_TYPE_TXT%> Order #<%-data.TO_ID%>&nbsp;-&nbsp;<%-data.TOE_TYPE_TXT%></p>

<p><%-data.CA_ADDR_PLUS%><br />
<%-data.CA_CITY_PLUS%></p>

<p><%-data.TOE_SCHED_STARTTM_FMT%> -&nbsp;<%-data.TOE_SCHED_ENDTM_FMT%></p>

<p><br />
Sincerely<br />
Affordable Moving Co.</p>
', NULL, N'Order Confirmation', 21, N'2016-09-27 17:28:14.4568759', 'Microsoft SQL Server', N'2016-09-28 10:21:46.8539903', 'S200010');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'EMAIL', N'ORDER_SCHED', N'HTML', N'Your Affordable Moving Company Order Information', N'<p>Dear <%-data.EMAIL_PARAMS[0].C_NAME%>,</p>

<p>Thank you for your <%-data.EMAIL_PARAMS[0].TO_TYPE_TXT%> Order. &nbsp;Your order has been scheduled for <%-data.EMAIL_PARAMS[0].TO_SCHED_FMT%>.</p>

<p>Order <%-data.EMAIL_PARAMS[0].TO_ID%> is attached.</p>

<p>Sincerely,<br />
Affordable Moving Company</p>
', NULL, N'<%-data.EMAIL_PARAMS[0].C_NAME%> Customer Name
<%-data.EMAIL_PARAMS[0].TO_ID%> Order ID
<%-data.EMAIL_PARAMS[0].TO_TYPE_TXT%> Order Type
<%-data.EMAIL_PARAMS[0].TO_SCHED_FMT%> Order Date', 40, N'2017-03-31 18:41:02.3979164', 'Microsoft SQL Server', N'2017-05-10 11:57:14.4472750', 'S200007');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'EMAIL', N'ORDER_INFO', N'HTML', N'Affordable Moving Company <%-data.EMAIL_PARAMS[0].TO_TYPE_TXT%> Order #<%-data.EMAIL_PARAMS[0].TO_ID%> Information', N'<p>Dear <%-data.EMAIL_PARAMS[0].C_NAME%>,</p>

<p><%-data.EMAIL_PARAMS[0].TO_TYPE_TXT%> Order #<%-data.EMAIL_PARAMS[0].TO_ID%> is attached.</p>

<p>Sincerely,<br />
Affordable Moving Company</p>
', NULL, N'<%-data.EMAIL_PARAMS[0].C_NAME%> Customer Name
<%-data.EMAIL_PARAMS[0].TO_ID%> Order ID
<%-data.EMAIL_PARAMS[0].TO_TYPE_TXT%> Order Type
<%-data.EMAIL_PARAMS[0].TO_SCHED_FMT%> Order Date', 41, N'2017-04-01 06:31:25.8660136', 'MS SQL Maestro', N'2017-05-10 11:54:17.6171935', 'Microsoft SQL Server');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'REPORT', N'RECEIVING', N'HTML', NULL, N'<p><span style="font-size:20px"><strong>STORAGE VALUATION</strong></span></p>

<p><span style="font-size:18px">Items stored at Affordable Moving are automatically valued at $0.60 per pound per article in the event of loss. &nbsp; Additional coverage is available at $9.00 per $1,000.00 of increased valuation <u>per month</u>.</span></p>

<p><span style="font-size:18px">Please choose "A" for Basic Valuation or "B" for Full Valuation.</span></p>

<table border="0" cellpadding="7" cellspacing="1" style="width:100%">
  <tbody>
    <tr valign="top">
      <td><span style="font-size:18px">&nbsp;&nbsp;</span></td>
      <td><span style="font-size:18px">A.</span></td>
      <td><span style="font-size:18px">I accept the valuation of $0.60 per pound per article at no additional charge.<br /><br />
      Signature: &nbsp;__________________________________________&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Date: ______________________</span></td>
    </tr>
    <tr valign="top">
      <td><span style="font-size:18px">&nbsp;&nbsp;</span></td>
      <td><span style="font-size:18px">B.</span></td>
      <td><span style="font-size:18px">I request additional valuation coverage for the items listed on this receiving report at $9.00 per $1000.00 of inreased valuation per month with a $100.00 deductible.<br /><br />
      Declared value: ______________________<br /><br />
      Signature: &nbsp;__________________________________________&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Date: ______________________</span></td>
    </tr>
  </tbody>
</table>

<p>&nbsp;</p>
', NULL, N'Storage Valuation Disclaimer', 42, N'2017-04-26 17:33:15.3384122', 'Microsoft SQL Server', N'2017-04-26 18:22:44.7629435', 'S200010');
INSERT INTO jsharmony.TXT (TXT_PROCESS, TXT_ATTRIB, TXT_TYPE, TXT_TVAL, TXT_VAL, TXT_BCC, TXT_Desc, TXT_ID, TXT_ETstmp, TXT_EU, TXT_MTstmp, TXT_MU) VALUES (N'EMAIL', N'GENERIC', N'TEXT', N'<%=data.HOUSE[0].HOUSE_NAME%> - <%=data.HOUSE[0].REPORT_NAME_TXT_FULL%> ', N'Dear <%=data.EMAIL_PARAMS[0].GEN_NAME%>,

Report is attached.

Sincerely,
<%=data.HOUSE[0].HOUSE_NAME%>
', NULL, N'<%-data.C_NAME%> Customer Name
<%-data.J_ID%> Job ID
<%-data.PORTAL_URL%> Portal URL', 52, N'2017-05-17 16:48:35.8244414', 'Microsoft SQL Server', N'2017-05-18 09:27:06.6284069', 'S200010');
COMMIT
GO

SET IDENTITY_INSERT jsharmony.TXT OFF
GO



-- Data from table "jsharmony.V"
SET IDENTITY_INSERT jsharmony.V ON
GO


SET IDENTITY_INSERT jsharmony.V OFF
GO



