/*
CREATE DATABASE %%%INIT_DB_LCASE%%%
  WITH OWNER = postgres
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'English_United States.1252'
       LC_CTYPE = 'English_United States.1252'
       CONNECTION LIMIT = -1;
*/  
/*
\connect %%%INIT_DB_LCASE%%%
*/
CREATE ROLE jsharmony_%%%INIT_DB_LCASE%%%_role_exec;
ALTER ROLE jsharmony_%%%INIT_DB_LCASE%%%_role_exec WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS VALID UNTIL 'infinity';
CREATE ROLE jsharmony_%%%INIT_DB_LCASE%%%_role_dev;
ALTER ROLE jsharmony_%%%INIT_DB_LCASE%%%_role_dev WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS VALID UNTIL 'infinity';